### ISSUE TITLE
Hassio cannot play audio through one or more plugins simultaneously

### ISSUE THREAD

**Issue by yevon** [home-assistant/hassio#1000]
**Home Assistant release with the issue:**
0.91.0

**Operating environment (HassOS/Generic):**
Ubuntu 18.04 + docker

**Supervisor logs:**

19-04-06 12:06:37 INFO (MainThread) [hassio.core] Hass.io is up and running
19-04-06 12:06:52 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home Assistant Docker!
19-04-06 12:06:52 INFO (SyncWorker_0) [hassio.docker.interface] Start homeassistant/qemux86-64-homeassistant
19-04-06 12:07:23 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-04-06 12:07:31 INFO (MainThread) [hassio.host.alsa] Update ALSA device list
19-04-06 12:07:31 WARNING (MainThread) [hassio.host.alsa] Unknown channel type: hardware dependent
19-04-06 12:07:31 WARNING (MainThread) [hassio.host.alsa] Unknown channel type: hardware dependent
19-04-06 12:07:49 INFO (MainThread) [hassio.host.alsa] Detect output device 0,3
19-04-06 12:07:49 INFO (MainThread) [hassio.host.alsa] Detect input device 1,0

** Hardware list: **
serial:
/dev/ttyS30
/dev/ttyS15
/dev/ttyS17
/dev/ttyS25
/dev/ttyS11
/dev/ttyS16
/dev/ttyS21
/dev/ttyS12
/dev/ttyS5
/dev/ttyS31
/dev/ttyS13
/dev/ttyACM0
/dev/ttyS10
/dev/ttyS0
/dev/ttyS6
/dev/ttyS7
/dev/ttyS3
/dev/ttyS2
/dev/ttyS23
/dev/ttyS28
/dev/ttyS9
/dev/ttyS1
/dev/ttyS14
/dev/ttyS20
/dev/ttyS4
/dev/ttyS8
/dev/ttyS24
/dev/ttyS26
/dev/ttyS27
/dev/ttyS29
/dev/ttyS22
/dev/ttyS18
/dev/ttyS19
input:
FC:58:FA:96:DD:4C
Logitech K600 TV
HD-Audio Generic HDMI/DP,pcm=3
HD-Audio Generic HDMI/DP,pcm=8
HD-Audio Generic HDMI/DP,pcm=9
HD-Audio Generic Mic
Video Bus
HD-Audio Generic HDMI/DP,pcm=7
Power Button
HD-Audio Generic Front Line Out
disk:
gpio:
gpiochip256
audio:
0:
name: HDA-Intel - HD-Audio Generic
type: Generic
devices:
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
1:
name: HDA-Intel - HD-Audio Generic
type: Generic_1
devices:
[object Object]
[object Object]
[object Object]
2:
name: USB-Audio - USB Camera-B4.09.24.1
type: CameraB409241
devices:
[object Object]

**Description of problem:**
I finally achieved to play some audio through hassio after last docker audio access problems, but I noticed that it is not able to play audio through 2 plugins simultaneously, only the last started one is able to play audio, the other one is muted and doesn't display any error. For example, if I start spotify and then mopidy, it is only able to play sound through mopidy.

**Comment by yevon** [comment]
Has anybody else this problem?

**Comment by TEfjLONjDON** [comment]
I have the same issue

** Hardware list: **
~ $ hassio hw info
audio:
  "0":
    devices:
    - chan_id: "0"
      chan_type: digital audio playback
    - chan_id: "0"
      chan_type: digital audio capture
    - chan_id: "1"
      chan_type: digital audio playback
    - chan_id: "2"
      chan_type: digital audio capture
    - chan_id: "0"
      chan_type: hardware dependent
    name: HDA-Intel - HDA Intel PCH
    type: PCH
  "1":
    devices:
    - chan_id: "3"
      chan_type: digital audio playback
    - chan_id: "7"
      chan_type: digital audio playback
    - chan_id: "8"
      chan_type: digital audio playback
    - chan_id: "9"
      chan_type: digital audio playback
    - chan_id: "0"
      chan_type: hardware dependent
    - chan_id: "1"
      chan_type: hardware dependent
    - chan_id: "2"
      chan_type: hardware dependent
    - chan_id: "3"
      chan_type: hardware dependent
    name: HDA-Intel - HDA NVidia
    type: NVidia
disk: []
gpio: []
input:
- HDA Intel PCH Line
- HDA NVidia HDMI/DP,pcm=8
- HDA Intel PCH Front Headphone
- HDA NVidia HDMI/DP,pcm=7
- Media Center Ed. eHome Infrared Remote Transceiver (147a:e018)
- Eee PC WMI hotkeys
- Power Button
- HDA NVidia HDMI/DP,pcm=3
- HDA Intel PCH Rear Mic
- Telink Wireless Receiver
- HDA Intel PCH Line Out
- CHICONY USB Keyboard
- HDA NVidia HDMI/DP,pcm=9
- HDA Intel PCH Front Mic
serial:
- /dev/ttyS0
- /dev/ttyS23
- /dev/ttyS25
- /dev/ttyS14
- /dev/ttyS10
- /dev/ttyS2
- /dev/ttyS9
- /dev/ttyS30
- /dev/ttyS21
- /dev/ttyS20
- /dev/ttyS13
- /dev/ttyS17
- /dev/ttyS12
- /dev/ttyS29
- /dev/ttyS6
- /dev/ttyS15
- /dev/ttyS27
- /dev/ttyS11
- /dev/ttyS7
- /dev/ttyS4
- /dev/ttyS31
- /dev/ttyS19
- /dev/ttyS16
- /dev/ttyS1
- /dev/ttyS18
- /dev/ttyS5
- /dev/ttyS26
- /dev/ttyS28
- /dev/ttyS3
- /dev/ttyS8
- /dev/ttyS22
- /dev/ttyS24

**Comment by TEfjLONjDON** [comment]
~ $ hassio ha info
arch: amd64
boot: true
custom: false
image: homeassistant/qemux86-64-homeassistant
ip_address: ***.***.***.***.
last_version: 0.105.2
machine: qemux86-64
port: 8123
ssl: true
version: 0.105.2
wait_boot: 600
watchdog: true

**Comment by TEfjLONjDON** [comment]
I am unable to play audio via any addon (first loaded addon or other wise)
