### ISSUE TITLE
Custom labels for containers

### ISSUE THREAD

**Issue by signaleleven** [home-assistant/hassio#1003]
This is either a request for help (could not find in code/documentation if this is already possible) or a feature request.

Would it be possible to add custom docker labels to containers created for addons, via the configuration?
This would make possible, for instance, to dynamically configure traefik to proxy connections to addons with web interfaces.

It was also requested by another user in https://github.com/home-assistant/hassio-addons
https://github.com/home-assistant/hassio-addons/issues/517

**Comment by signaleleven** [comment]
I'd say that the ingress functionality largely covers my use case.

**Comment by guice** [comment]
I've actually came here for this same request, but I'm not using Trafik or k8s for hassio. It would be  nice to have custom label abilities for other tools.
