### ISSUE TITLE
Almost every update I can't install it cuz the update file isn't found.

### ISSUE THREAD

**Issue by kpj5425** [home-assistant/hassio#1009]
**Home Assistant release with the issue:**
0.91.1

**Last working Home Assistant release (if known):**
0.90.2

**Operating environment (Hass.io/Docker/Windows/etc.):**
VM on Virtual Box running on Win 7

**Component/platform:**
Home Assistant itself

**Description of problem:**
Can't update every few versions

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
None
```

**Traceback (if applicable):**
```

```

**Additional information:**
19-04-07 03:48:57 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.91.1
19-04-07 03:48:57 INFO (SyncWorker_6) [hassio.docker.interface] Update Docker homeassistant/qemux86-64-homeassistant:0.90.2 to homeassistant/qemux86-64-homeassistant:0.91.1
19-04-07 03:48:57 INFO (SyncWorker_6) [hassio.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.91.1.
19-04-07 03:49:04 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-04-07 03:49:04 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-04-07 03:49:04 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-04-07 03:49:04 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
19-04-07 03:49:05 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/config access from a0d7b954_appdaemon3
19-04-07 03:49:05 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_appdaemon3
19-04-07 03:51:08 ERROR (SyncWorker_6) [hassio.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.91.1 -> 404 Client Error: Not Found ("no such image: homeassistant/qemux86-64-homeassistant:0.91.1: No such image: homeassistant/qemux86-64-homeassistant:0.91.1").

**Comment by kpj5425** [comment]
Fixed this issue! dumped VM Virtual Box and moved my system back to Rpi 3. Updates flawlessly now. Breaking changes break everything for me every time.

**Comment by cogneato** [comment]
@kpj5425 too late here, but "no such image" usually refers to a lack of space.

**Comment by kpj5425** [comment]
> @kpj5425 too late here, but "no such image" usually refers to a lack of space.

I figured that. Just thought having it on VM Virtual Box, it would have had more room than being on a Rpi3. Thanks though.

**Comment by cogneato** [comment]
It would have as much space as you provide it and this is handled differently depending on what hypervisor you are using. It is best to do that prior to install as it expands into the available space during setup. By default the ova only has around 6GB.

For VirtualBox there is a guide here <https://www.dropbox.com/s/kwb9b3ji01leg96/Installing_HASSOS_on_VirtualBox.pdf?dl=0> at step 12.

Trying to change it post installation will require more effort.
