### ISSUE TITLE
Can't install on Linux Server, eventual cause invalid pull for 'amd64-hassio-supervisor'?

### ISSUE THREAD

**Issue by daninfuchs** [home-assistant/hassio#1018]
**Home Assistant release with the issue:**
0.91.1 - but technically not an HA issue

**Operating environment (HassOS/Generic):**
Hass.IO installed to fresh Ubuntu Server (18.04.2-alt) using documented instructions from https://www.home-assistant.io/getting-started/

**Supervisor logs:**
19-04-08 00:57:56 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install homeassistant/amd64-hassio-supervisor:latest:152 -> 400 Client Error: Bad Request ("no such image: homeassistant/amd64-hassio-supervisor:latest:152: invalid reference format").

**Description of problem:**

Problem has silent presentation - install succeeds fully with all steps until clicking Hass.IO in http://HASS:8123/ frontend. Chrome fires popup; "Unable to load the panel source: /api/hassio/app/entrypoint.js."

Docker logs for HomeAssistant indicate;
2019-04-08 01:07:32 ERROR (MainThread) [homeassistant.components.hassio.http] Client error on api app/entrypoint.js request Cannot connect to host 172.30.32.2:80 ssl:None [Connection refused]

Docker logs for Supervisor reveal cause;
19-04-08 00:57:54 INFO (MainThread) [hassio.supervisor] Update Supervisor to version 152,
19-04-08 00:57:54 INFO (SyncWorker_2) [hassio.docker.interface] Pull image homeassistant/amd64-hassio-supervisor:latest tag 152.,
19-04-08 00:57:56 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install homeassistant/amd64-hassio-supervisor:latest:152 -> 400 Client Error: Bad Request ("no such image: homeassistant/amd64-hassio-supervisor:latest:152: invalid reference format").

Odd that it's trying :152 instead of :154 -- is this my core issue, or is :152 damaged in some way? Also seems to be asking for :latest:152 instead of :latest or :154 -- typo perhaps?

**Comment by daninfuchs** [comment]
Apparently it fixed itself during a third attempt. NVFM.

**Comment by daninfuchs** [comment]
Accidental closure - issue still exists. (Sorry.)

**Comment by pvizeli** [comment]
I can repush this version...

**Comment by pvizeli** [comment]
![image](https://user-images.githubusercontent.com/15338540/55705921-35b34c00-59e0-11e9-84ce-5d1bae142c2d.png)

Looks fine. Can you pull other images?

**Comment by daninfuchs** [comment]
That's all well and good, but the issue isn't that I can't pull :152 - it's that there's a crash in your supervisor when it's trying to auto-update on first initialization after first installation. I can pull :152 as well, but what I can't do is install Hass.IO on a Linux Server using etc etc re: title and initial post.

![Untitled](https://user-images.githubusercontent.com/42219549/55707790-4a202600-5999-11e9-8fd9-8dc856ec59b8.png)

**Comment by daninfuchs** [comment]
Resolved. FYI - tested on two separate systems from scratch twice last night, neither worked as of then. All would install, pull :154 during install, then try to pull :latest:152 while doing initial auto-update during first-run container initialization. Today, both work (with no interaction from me beyond reboot) but are properly pulling today's :155 build in auto-update, and only asked for :latest instead of asking the repo for :latest:152 like they were before - so, someone noticed and fixed it. Thank you, mysterious stranger!

**Comment by pvizeli** [comment]
What kind of docker version do you run?

**Comment by pvizeli** [comment]
We should check that the image name has no tag included

**Comment by fredrike** [comment]
I'm working on building an hass.io install package for Synology and came across the same issue:

```log
19-04-23 18:57:45 INFO (MainThread) [hassio.supervisor] Update Supervisor to version 160
19-04-23 18:57:45 INFO (SyncWorker_3) [hassio.docker.interface] Pull image homeassistant/amd64-hassio-supervisor:latest tag 160.
19-04-23 18:57:46 ERROR (SyncWorker_3) [hassio.docker.interface] Can't install homeassistant/amd64-hassio-supervisor:latest:160 -> 404 Client Error: Not Found ("no such image: homeassistant/amd64-hassio-supervisor:latest:160: invalid reference format").
19-04-23 18:57:46 ERROR (MainThread) [hassio.supervisor] Update of Hass.io fails!
19-04-23 18:57:46 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<HassIO.start() done, defined at /usr/local/lib/python3.7/site-packages/hassio/core.py:71> exception=SupervisorUpdateError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/hassio/core.py", line 77, in start
    elif await self.sys_supervisor.update():
  File "/usr/local/lib/python3.7/site-packages/hassio/supervisor.py", line 115, in update
    raise SupervisorUpdateError() from None
hassio.exceptions.SupervisorUpdateError
```

I'm running `Docker version 17.05.0-ce, build 9f07f0e-synology`.

**Comment by pvizeli** [comment]
We use some 17.06.0 only feature for building stuff. Could be that not all options from `build.json` will work

**Comment by fredrike** [comment]
Where is `build.json` located?

**Comment by pvizeli** [comment]
In add-on folders. But you should see any errors inside logs and most add-ons are shipped as images and don't need builded localy.
