### ISSUE TITLE
[Feature Request] Define host volumes for use inside Hassio

### ISSUE THREAD

**Issue by Bodge-IT** [home-assistant/hassio#1046]
I've looked around the install script to try and add this feature myself but its beyond my bash scripting capabilities.

Currently I'm restricted in use of Hasssio with camera and streaming features.  I really want to be able to send images through notifications to Telegram but can't access external folders outside the container.

Could you add a -v option that allows defining multiple entries for the hassio install script?

I know I can do this with my own HomeAssistant container but then I lose the options for Addons which are super useful.

**Comment by pvizeli** [comment]
Use the `share` folder to exchange data. That feature is not possible because it lost all feature of snapshots and portability.

**Comment by Bodge-IT** [comment]
I guess Ill need to use symlinks in the share folder...will that work?
