### ISSUE TITLE
Ingress on aarch64 is broken.

### ISSUE THREAD

**Issue by rbray89** [home-assistant/hassio#1048]
**Home Assistant release with the issue:**
0.91.4

**Last working Home Assistant release (if known):**
None

**Operating environment (Hass.io/Docker/Windows/etc.):**
HassOS on Odroid C2

**Component/platform:**
Ingress

**Description of problem:**
Ingress HassIO addons display `502: Bad Gateway` when attempting to open their UI.

**System Logs:**
```
19-04-21 19:40:21 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:None [Connection refused]
```

**Additional information:**

**Comment by JasonSwindle** [comment]
Same issue. All ingress add-ons are errors with 502 on HASS using Odroid-C2.

**Comment by esseki** [comment]
Same issue here on HASSOS using an ODroid C2.

**Comment by janek202** [comment]
The same thing on 0.92, Hass.io installed in Docker.
Running on Raspberry Pi 3 and Ubuntu MATE 18.04.2 LTS arm64.

**Comment by pvizeli** [comment]
It's a bug in alpine Linux available package. @frenck add a PR to fix that

**Comment by pvizeli** [comment]
If fixed now
