### ISSUE TITLE
Supervisor Auto-Update

### ISSUE THREAD

**Issue by apop880** [home-assistant/hassio#1061]
**Home Assistant release with the issue:** N/A

**Operating environment (HassOS/Generic):** N/A

**Supervisor logs:** N/A

**Description of problem:** This is a feature request to provide more transparency around Supervisor updates, and allow for disabling auto-updates and/or scheduling them for certain times of the day. See further discussion:

https://community.home-assistant.io/t/feature-request-block-supervisor-auto-updates/112743
https://github.com/home-assistant/home-assistant/issues/21738

**Comment by pvizeli** [comment]
I'll merge any PR that allows setting a time on the current day to make the update 👍 

I close that because Issue is not for feature requests.

**Comment by john-arvid** [comment]
@pvizeli 
I think this issue should be opened again (or created as a new issue). Not as a feature request but as an actual issue.
And I'm not thinking that it is an issue that we don't have the option to set what time of the day an update should be done, but I think it is an issue that there is no option to stop auto update.
As the home page of Home Assistant is stating: "Open source home automation that puts local control and privacy first." I don't feel like auto updating is in my local control.

Or is the thought that the user should block internet access or change the `/usr/src/supervisor/supervisor/tasks.py` file to stop the auto update?

**Comment by frenck** [comment]
For installation with the supervisor, this is mandatory. If you want more control @john-arvid, please use Home Assistant Container (Running Core in Docker for example) instead.

Furthermore, this issue has been closed for over a year already. Please don't dig up old/handled issues or PRs. Instead, raise a new issue in those cases.
