### ISSUE TITLE
api_password is going to deprecate. You need to use a bearer token to access /api/hassio_auth

### ISSUE THREAD

**Issue by Nicxe** [home-assistant/hassio#1063]
**Home Assistant release with the issue:**
0.92.1

**Operating environment (HassOS/Generic):**
Generic / Hassio running in a docker on a Nuc

**Description of problem:**

Everytime I restart I get this two errors in my logg
`api_password is going to deprecate. You need to use a bearer token to access /api/ from 172.30.32.2`
and
`api_password is going to deprecate. You need to use a bearer token to access /api/hassio_auth from 172.30.32.2`

I have got these errors since I removed api password from [my configuration](https://github.com/Nicxe/HASS.io/blob/master/configuration.yaml) . I can find container using IP 172.30.32.2, I seams that this is a IP used by Hassio supervisor. 

I have tried to identify if this comes from anyone of my plugins without success, I use these plugins
[Community Hass.io Add-ons: Glances](https://github.com/hassio-addons/addon-glances)
[Community Hass.io Add-ons: InfluxDB](https://github.com/hassio-addons/addon-influxdb)
[Samba](https://www.home-assistant.io/addons/samba/)
[Community Hass.io Add-ons: Visual Studio Code](https://github.com/hassio-addons/addon-vscode)
[Official deconz](https://www.home-assistant.io/addons/deco)

I have tried add trusted_networks in configuration.yaml without any success. I can not find anything that don't work

Related issue https://github.com/home-assistant/home-assistant/issues/23457#issuecomment-487266129

**Comment by isabellaalstrom** [comment]
I am also getting these warnings. Can come back with config and addons used later.

**Comment by Nicxe** [comment]
I can add that I had this error for a couple of versions. I can’t rely point to one version when this started, its been like that since I removed api password from the config. I think it was around 0.90

**Comment by Nicxe** [comment]
Thanks!
