### ISSUE TITLE
curl shell command hangs HA

### ISSUE THREAD

**Issue by Kedryn** [home-assistant/hassio#1068]
**Home Assistant release with the issue:** 

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**
Since 0.92, all my calls to shell scripts results in HA being unrensponsive, both it's web interface and it's automations.

I have 2 shell script defined since 0.89. Both are a curl to Blue Iris web api.

shell_command:
  trigger_blueiris_cam_ing_mov: 'curl -k "http://192.168.0.27:81/admin?camera=CamIng&trigger&user=admin&pw=xxxxxxx"' 
  trigger_blueiris_cam_gar_mov: 'curl -k "http://192.168.0.27:81/admin?camera=CamGar&trigger&user=admin&pw=xxxxxxx"'

When i call them from an automation, HA hangs.
They were working with previous versions.
No log lines are generated.

**Comment by pvizeli** [comment]
If you use stream component, use rest_command instead shell_command

**Comment by Kedryn** [comment]
That's works.
But shell_command hanging down HA is an  issue

**Comment by Breakerz** [comment]
same here, a simple "touch /tmp/test" jam all the HA process.  
nothing in the logs with level debug for shell_command
I tested on a VM with a new HassOS install ... and restore a snapshot. and it's worked well.

**Comment by Breakerz** [comment]
@pvizeli how can I force the rebuild of HomeAssistant container in HassIO ?

**Comment by xbmcnut** [comment]
Taken me 2 weeks to find what was causing HA to go bad when I had left home and it turns it, it is my camera presets that using curl in Shell Commands. Is there a way to fix that?

**Comment by Kedryn** [comment]
> Taken me 2 weeks to find what was causing HA to go bad when I had left home and it turns it, it is my camera presets that using curl in Shell Commands. Is there a way to fix that?

It's a workaround for the problem, but it's a better way to do that anyway. Use the rest command.

Instead of defining a shell command, use something like this (that i use for Blue Iris):

rest_command:
  trigger_blueiris_cam_ing_mov:
    url: http://192.168.0.27:81/admin?camera=CamIng&trigger&user=xxxx&pw=xxxxxxxx

**Comment by xbmcnut** [comment]
> 
> 
> > Taken me 2 weeks to find what was causing HA to go bad when I had left home and it turns it, it is my camera presets that using curl in Shell Commands. Is there a way to fix that?
> 
> It's a workaround for the problem, but it's a better way to do that anyway. Use the rest command.
> 
> Instead of defining a shell command, use something like this (that i use for Blue Iris):
> 
> rest_command:
> trigger_blueiris_cam_ing_mov:
> url: http://192.168.0.27:81/admin?camera=CamIng&trigger&user=xxxx&pw=xxxxxxxx

Yep, thanks. Trying a rest_command now but having a little issue with authentication. Seems I need to add 'digest' into the post request but not quite sure how to do that with rest.

**Comment by Breakerz** [comment]
shell_command and stream components have issues together. I disabled stream, and all my shell_command run again.

**Comment by frenck** [comment]
The main issue here seems to be found/solved/worked around, which is why I'm closing this issue.
Secondly, this is a Home Assistant issue, not Hass.io specific. Please, if needed, create a follow up issue on the main repository.
