### ISSUE TITLE
ZHA unable to start after hassio restart

### ISSUE THREAD

**Issue by tube0013** [home-assistant/hassio#1076]
**Home Assistant release with the issue:**

0.92.2
**Operating environment (HassOS/Generic):**

hassio Generic - Supervisor 162 - on Ubuntu 18.04.2 LTS
**Supervisor logs:**

**Description of problem:**
see this HA issue:
https://github.com/home-assistant/home-assistant/issues/23719

when restarting hassio, the zha component is not able to access the HUSBZB1 usb device.  if you remove the zha integration - restart hassio - re-add zha integration it works fine.

in the linked issue you will see that adding the a delay to starting zha seems to be a work around.  You will also see that testing with the homeassistant/home-assistant image did not have this issue nor did running the homeassistant/qemux86-64-homeassistant image directly.

It seems the way that hassio restarts ha does not play well with zha.  I don't know if this is because of faster hosts exiting and starting the hass docker container too quickly or some thing else.  the Zha devs don't want to add a delay to the component as this is an issue only related to hassio.

**Comment by pvizeli** [comment]
Please try version 163

**Comment by tube0013** [comment]
No difference with 163

**Comment by LazyFoxFarms** [comment]
I also have this issue when restarting hassio 0.93.0b2, supervisor 163 in dockerCE w/ Ubuntu 18.04.02 with a HUSBZB1.  Started somewhere around .91 for me after a reboot of the machine. Thanks for looking into it.

**Comment by pvizeli** [comment]
I don't know what could be the problem :(
The only difference is now, we run udev inside container, but they handle only devices and don't should affect it...

**Comment by Nemesis24** [comment]
A solution was find:
https://github.com/home-assistant/home-assistant/issues/23719#issuecomment-493666614

**Comment by frenck** [comment]
This is not a Hass.io issue. Please see for more hints and information: home-assistant/home-assistant#23719
