### ISSUE TITLE
HassIO  install stops at “udevd[9]: starting eudev-3.2.7”

### ISSUE THREAD

**Issue by KixMan28** [home-assistant/hassio#1082]
**Home Assistant release with the issue:**

Raspberry Pi 2 B Hassio image
**Operating environment (HassOS/Generic):**

HassOS
**Supervisor logs:**

NA

**Description of problem:**
I try install HassIO on my RPi2. I have downloaded the latest image file (hassos_rpi2-2.11.img.gz) for RPi2, I copied it to a 32Gb microSD card with Balena Etcher. After successful flashing I insert the card into my RPi, it starts up the boot process and then it stops at: “udevd[9]: starting eudev-3.2.7”

I am trying to install Hass.IO since yesterday, I have flashed the SD card several times, I tried adding “my-network” file with LAN or WIFI connections, but nothing helps.
I have LAN connection on my RPi. 
I can see my RPi in my router's device list, but I cannot access http://hassio.local:8123 nor http://RPi_IP_ADD:8123

Does anyone have a solution for this?

**Comment by pvizeli** [comment]
Login into your device as "root" and on CLI enter `login`. After that use `ip addr show` to confirm the IP Address.

**Comment by KixMan28** [comment]
Can you detail your answer a little bit. I am a newbie in this. What do you mean by "Login into your device as "root" and on CLI enter login"? After the installation stops at eudev-3.2.7 I try to reach my RPi with Putty on the IP address which I see in my router for the Hassio, but when I try to connect to it I get an error message that: Network error. Connection refused. If I try to ping the IP address everything works fine. 

What should I do now?

**Comment by KixMan28** [comment]
@pvizeli Could you be so kind to reply to my questions above?

Thank you for your support.

**Comment by cogneato** [comment]
@KixMan28 you can connect a keyboard and monitor directly to your pi and login as described. You hit enter and then you use root with no password to get to the Hassio CLI. From there you enter "login" to continue to the host os. From there you can use `ip addr show`

**Comment by KixMan28** [comment]
@cogneato Thank you for your explanation. It works now.

**Comment by mach77777** [comment]
> 
> 
> @cogneato Thank you for your explanation. It works now.

How did you resolve the issue? I have the same problem; Hass.io hangs during install. Specifically after eudev 3.2.7

**Comment by KixMan28** [comment]
Hi @mach77777 
After several restarts I have left my RPi running all night. In the morning I saw that I have a different message on the display. I connected a keyboard to my RPi and I tried to scroll back, but I saw only strange characters, then I pressed Enter and I typed what pvizeli recommended and it worked, so honestly I don't know what solved the issue.

I have re-imaged my MicroSD card several times. Last time I did it with Rufus. 

Maybe the solution is to wait a little bit longer (maybe 20-30 minutes) after you have the eudev message. I have installed Hass.io in the past and that time after several lines of installation messages on the display at a certain moment in time it switched to a white screen with the blue HA logo. All YouTube videos showed this screen. It looks like the newer HA versions don't have this white screen, but only the texts on the display.

I haven't find anywhere information related to this and also no other information about what else I should do once i have the eudev message on my display.

I hope I could help you. Let me know how it works for you.

**Comment by IanAdd** [comment]
starting eudev-3.2.7 is the last thing the console SHOULD say.
You need to go to a browser on a PC or whatever and start there.
Warning the instruction to enter the url hassio.local:8123 did not work for me. I had to find its IP and use that eg... 192.168.0.99:8123

**Comment by frenck** [comment]
@KixMan28 That screen shown in youtube videos is from the browser, not from the console you get when you attach a monitor to the HDMI.

HassOS is designed to run headless (without a monitor).
