### ISSUE TITLE
Confusing update notification?

### ISSUE THREAD

**Issue by PieBru** [home-assistant/hassio#1098]
Hi, in the hassio dashboard I just received a confusing notification, announcing 0.92.3 availability while having 0.93.1 installed.
Maybe it's only a typo and 0.92.3 should be 0.93.2, however I signal this as it may hide somewhere an error or a missing check.
Piero

**Comment by frenck** [comment]
This was a typo/incident.
Hass.io determines if an upgrade is available by checking if the current version doesn't match the latest version from the upstream server (even if it is a downgrade/rollback).
