### ISSUE TITLE
Ingress follows redirects in backend but it shouldn't

### ISSUE THREAD

**Issue by OttoWinter** [home-assistant/hassio#1103]
**Home Assistant release with the issue:** 0.93.2
**Operating environment (HassOS/Generic):** RPi 3b+
**Supervisor logs:** nothing related
**Description of problem:**

Hass.io ingress has a really weird quirk:

When a client requests an URL, and the backend behind ingress responds to that with a redirect, ingress follows the redirect itself and **does not** send the 302 directly to the browser as it should. This breaks some web applications, for example if the redirect followed to some sub-directory, all relative paths break.

I think some images show this the best:

I have the same setup twice:
 - The browser creates a request for `./wizard.html`
 - The backend responds with a 302 for `./?begin=true`
 - Browser should then follow the redirect.
Once with ingress enabled, once without

Here are some browser network images:

**Without Ingress**:
<img width="565" alt="Screen Shot 2019-05-30 at 12 00 05" src="https://user-images.githubusercontent.com/6833237/58625994-f3b5d080-82d3-11e9-9b0f-1741164d2f7b.png">
<img width="350" alt="Screen Shot 2019-05-30 at 12 03 36" src="https://user-images.githubusercontent.com/6833237/58626007-fd3f3880-82d3-11e9-8dfb-6896392191b4.png">

**With Ingress**:
<img width="603" alt="Screen Shot 2019-05-30 at 12 00 15" src="https://user-images.githubusercontent.com/6833237/58626017-05977380-82d4-11e9-88f0-629907b0825d.png">
<img width="448" alt="Screen Shot 2019-05-30 at 12 00 30" src="https://user-images.githubusercontent.com/6833237/58626031-0af4be00-82d4-11e9-80d8-1e0a71abead4.png">

**Comment by OttoWinter** [comment]
Looks like `allow_redirects=False` should be added here:

https://github.com/home-assistant/hassio/blob/b4665f3907b3a3b50b6f54264807d2dfd375b780/hassio/api/ingress.py#L160-L162

https://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.request

**Comment by pvizeli** [comment]
Cool, thanks for debugging. I'm happy to find a solution for that problem. Will create a PR to HA and hass.io do not follow the URL
