### ISSUE TITLE
Support WM8960 audio

### ISSUE THREAD

**Issue by probonopd** [home-assistant/hassio#1122]
**Home Assistant release with the issue:**

0.93.1

**Operating environment (HassOS/Generic):**

HassOS

**Supervisor logs:**

(nothing related)

**Description of problem:**

WM8960 audio chip is not recognized. It is used in product such as
* https://docs.snips.ai/the-maker-kit/dev-kit
* http://wiki.seeedstudio.com/ReSpeaker_2_Mics_Pi_HAT/
* https://www.waveshare.com/wiki/WM8960_Audio_HAT

I have attached a Waveshare WM8960 Hi-Fi Sound Card HAT but nothing happens, doesn't seem to be recognized.

Following the instructions on https://www.waveshare.com/w/upload/5/54/WM8960_Audio_HAT_User_Manual_EN.pdf,

```
git clone https://github.com/waveshare/WM8960-Audio-HAT
cd WM8960-Audio-HAT
sudo ./install.sh
```

leads to 

```
cat: can't open '/proc/device-tree/model': No such file or directory
Sorry, this drivers only works on raspberry pi
```

How do I enable this?

**Comment by probonopd** [comment]
Also,

```
core-ssh:~/WM8960-Audio-HAT# aplay -l
-bash: aplay: command not found
```

**Comment by probonopd** [comment]
Not doing anything is _never_ a vaild reason to mark something as "wontfix". @stale please go away.

**Comment by probonopd** [comment]
Not doing anything is never a vaild reason to mark something as "wontfix". @Stale please go away.

**Comment by probonopd** [comment]
An issue should not automatically be marked as stale because it has not had recent activity. It should not be closed if no further activity occurs. Thank you for considering to work on this issue.

**Comment by pvizeli** [comment]
It's the wrong repository and only for bugs and not feature requests.

I don't think that we support such thing easy on HassOS. Maybe you should use raspbian with generic installer to run Hass.io and your card will work.

**Comment by probonopd** [comment]
Thanks for the clarification @pvizeli. Which is the correct issue tracker for feature requests?
