### ISSUE TITLE
Hassio in docker onto RPi4 

### ISSUE THREAD

**Issue by georgelza** [home-assistant/hassio#1141]
Hi all, not directly a issue, more a request.
Currently have a Hassio running in Docker on a RPi3b
Any chance we can get a how to migrate to RPi4 document compiled.
Understand the easiest might be do to a Raspbian upgrade in place, but Raspberry community is implying rather do a full fresh install, which imply if thats the route, new SD card then what's all involved to migrate from SD to new SD...

G

**Comment by pvizeli** [comment]
Take a snapshot and restore it on new system. One of the amazing feature of Hass.io that you can almost restore everthing on different Hardware.

**Comment by georgelza** [comment]
take note I don't have a bare metal Hassio deployment. see my  one above, this is Hassio inside docker on Stretch. 
is there a document/link that defines how to do this.
G

**Comment by pvizeli** [comment]
That's not an official way to run Hass.io and there is also no support. You should next time simple run the installer script and you are fine with any movments ;)

**Comment by georgelza** [comment]
hmmm, actually it is a method laid out by Hass.io community on their site as an alternative...
, but not to worry.
thanks
G

**Comment by kitos9112** [comment]
Guys,

Probably slightly off-topic but I don't want to mess around with other issues being created. I'm new to hassio and wanted to install it on my fresh Rpi-4 however it's not yet listed on https://github.com/home-assistant/home-assistant.io/blob/current/source/hassio/installation.markdown

I could just run the container Docker version of it but I think it might be more logical to run the standalone full OS version of it as I will have a dedicated Rpi.

Any timeline or suggestion about achieving so?

Thanks!

**Comment by georgelza** [comment]
As a new build, pretty easy, Deploy Buster (Rpi4 OS), deploy Docker, and then follow the Hass.io Docker deployment guide on the Home-Assistant site.
G

**Comment by georgelza** [comment]
PS: took me about a hour.
G

**Comment by kitos9112** [comment]
Thanks for your prompt response @georgelza 

I'll give it a go in the coming days, I need to find time though! Any special care while running this application in a Docker container apart from inherited Docker thumb rules?

Cheers

**Comment by georgelza** [comment]
Biggest thing is to get docker installed...
2nd thing.. check your swop space allocated to the OS. I kept on running out, based on default build, I increase the swop to 1GB, I'd say if you can, when building the OS, look at increasing it, before installing any software.
G

**Comment by kitos9112** [comment]
I bet you can increase the SWAP partition at any time by modifying this variable in the files mentioned in the URL below.

https://wpitchoune.net/tricks/raspberry_pi3_increase_swap_size.html

**Comment by georgelza** [comment]
True/Correct, you can, I just mentioned do it now, before installing anything, so that you don't forget, end with a slow down, HA freeze later and wonder why,
G

**Comment by kitos9112** [comment]
Wonderful - Will give it a go then. I just burnt the latest Buster image in my SD, but I'll start from scratch in case I regret it later :)

Cheers @georgelza
