### ISSUE TITLE
Network / port should contain also IP address

### ISSUE THREAD

**Issue by hejnm1am** [home-assistant/hassio#1165]
Addons that have WebUI (Grafana, InfluxDB, etc.) can configure WebUI port.
For example in case of Grafana, there is **80/tcp: 3000** configuration option.

For Linux setups (not on dedicated hardware), there is a need to limit this to localhost IP address only (limit to dst-IP).
E.g. when starting docker you can put option **-p 127.0.0.1:3000:80**

However there is no way how to configure this in hassio.

Could you please add this option? Or is it possible to do by modifying some configuration file?
If I modify addons.json with

> "network": {
>         "80/tcp": "127.0.0.1:3000"
>       }
> 

the modification gets overwritten.

Docker modifies iptables firewall by default so there is no easy way to limit this by setting iptables firewall. You can disable this but you will loose this functionality for other Docker containers.
https://community.home-assistant.io/c/feature-requests

**Comment by pvizeli** [comment]
Set the port on UI to None and you can only reach it from internal virtual network
