### ISSUE TITLE
Unable to load Hassio(RPI3B+) from latest image baseline hassos_rpi3-2.12.img

### ISSUE THREAD

**Issue by zViking** [home-assistant/hassio#1181]
Unabble to load Hassio from latest image baseline hassos_rpi3-2.12.img

**Home Assistant release with the issue:**
hassos_rpi3-2.12.img

**Operating environment (HassOS/Generic):**
RPI3B+

**Supervisor logs:**
N/A

**Description of problem:**
Hassio load does not complete, problem since @ 4 July.
Please create new image baseline.

**Comment by pvizeli** [comment]
I don't had any issue on this
