### ISSUE TITLE
Raspberry Pi4 4GB and hassio see "915MB of total MEM"

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/hassio#1182]
> **Home Assistant release with the issue:**
> 
> Latest - 0.96.5
> **Operating environment (HassOS/Generic):**
> 
> HassOS
> **Supervisor logs:**
> 
> Unable to access
> 
> **Description of problem:**
> I've recently migrated my install from a Raspi3 to a 4,.
> 
>as title
using the latest 64 bit image.

this is the output of free -m

```
core-ssh:/data/backup_to_git# free -m
              total        used        free      shared  buff/cache   available
Mem:            915         428         110           3         376         543
Swap:           228          44         184
```

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassos/issues/439
