### ISSUE TITLE
ERROR (MainThread) [hassio.utils.gdbus] Can't parse  "systemd-user-sessions.service"

### ISSUE THREAD

**Issue by RaveGun** [home-assistant/hassio#1198]
**Home Assistant release with the issue:**

0.97.1

**Operating environment (HassOS/Generic):**

Ubuntu 16.04.6 LTS

**Supervisor logs:**

`9-08-11 08:14:04 ERROR (MainThread) [hassio.utils.gdbus] Can't parse '[[["sys-subsystem...`

**Description of problem:**
This issue is quite old and it goes like this.

During the whatever the hassio.utils.gdbus is doing, it is getting a huge json line back with the info about all the systemctl services. I guess it runs `systemctl status`.

This, on my Intel NUC + Ubuntu returns for the `systemctl status ondemand.service` something like this:
`Starting LSB: Set the CPU Frequency Scaling governor to "ondemand"`

This leads to a nested double quotes in the json that cannot be parsed.
`["ondemand.service", "LSB: Set the CPU Frequency Scaling governor to "ondemand"", "loaded", "active", "exited", "", "/org/freedesktop/systemd1/unit/ondemand_2eservice", 0, "", "/"]`

I don't think I know enough about any of the parts involved fix this. If the governor would return the status without the quotes the problem will be fixed. If I disable/remove the service it will also fix the issue I guess but I don't want to do this.

Is there an ignore list for the queried services?

This is only annoying because it generates a lot of log output and when I try to browse this on my mobile phone it hangs and lags a lot.

And did I mentioned that it is displayed in RED :)

**Comment by pvizeli** [comment]
I add https://github.com/home-assistant/hassio/pull/1203 that allow you to become the full string and we can try to fix/train the regex with this information

**Comment by RaveGun** [comment]
Hi,

This is what it is shown in the system log:
`19-08-19 22:14:11 INFO (MainThread) [hassio.host.services] Update service information
19-08-19 22:14:11 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1`

Shall I also upload the here the 70k worth of `Can't parse...` line from the system log?
Or a PasteBin link?

Thanks.

**Comment by pvizeli** [comment]
We work on a new integration of dbus, they should fix the issue

**Comment by pvizeli** [comment]
@RaveGun please send me a paste bin

**Comment by RaveGun** [comment]
Hello,

I did this from my phone but it should be ok:
https://pastebin.com/6AHbL1dj

Have a good day.

**Comment by pvizeli** [comment]
Thanks. Sorry, I need the raw output. You can get it with `hassio su options --logging debug`

**Comment by RaveGun** [comment]
Hi,

This will not work because everything is running on docker and the hassio is not available.

The pastebin has also the raw information at the bottom. That's if the output on the hassio log is raw enough.

Otherwise I don't know how to generate more output.

**Comment by pvizeli** [comment]
I fix it. Thanks anyway for help. In debug mode, you have more output and the raw value for Gvariant which is the output of gdbus and we parse that into json.
