### ISSUE TITLE
'raspistill' was not found

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/hassio#120]
HASS 0.49.1, Hassio (1.0 ?) tested on both a pi3 and a pi zero with connected pi cameras, when the camera is added to config get the error:

`[homeassistant.components.camera.rpi_camera] 'raspistill' was not found`

**Comment by pvizeli** [comment]
Yeah, the support for that will come with home-assistant 0.51 in hass.io

**Comment by robmarkcole** [comment]
Still seeing this in 0.51 on pi zero w. If I can help out let me know

**Comment by rdenadai** [comment]
Well, running home assistant directly on raspibian works very nice... Will try to test a way to install in resin.io and after make a PR to hass.io

**Comment by pvizeli** [comment]
I think the path to `raspistill` is wrong. I think it need a update on home-assistant side to add the binary path like ffmpeg. https://pkgs.alpinelinux.org/contents?file=raspistill&path=&name=&branch=v3.6&repo=&arch=

**Comment by rdenadai** [comment]
Uhm... i see... this /opt/vc/bin/raspistill is very strange... perhaps some typo? i mean this /vc/

**Comment by pvizeli** [comment]
I think that is alpine Linux specific. The best fix is to allow modify the binary of this component. So you can set it to `/opt/vc/bin/raspistill` or we make a simlink to /usr/local/bin with dockerfile

**Comment by bcanning84** [comment]
Any update on this issue yet?? I've recently updated to HASS 0.52 on Hassio but am still receiving:
 [homeassistant.components.camera.rpi_camera] 'raspistill' was not found

**Comment by pvizeli** [comment]
I don't know but you can make a PR to https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/camera/rpi_camera.py for allow Manual set the binary or make a PR to dockerfile that make a simlink for raspistill

**Comment by Mafaldone** [comment]
I have the same issue, the command raspistill is not found. I searched but no file exists with that name.

**Comment by robmarkcole** [comment]
Afraid I am still seeing this in HA 0.52.1, although perhaps this fix is not released yet?

**Comment by pvizeli** [comment]
with next home-assistant update :+1:  0.52.1 was already out before we merge this...

**Comment by Mafaldone** [comment]
@robmarkcole I'm still getting the same error. Could you please check it again on hassio raspberry pi 3? I think docker image is not up to date, but I might be wrong.

**Comment by robmarkcole** [comment]
Prob not updated yet, soon I'm sure :)

**Comment by gollo** [comment]
You will see it when you see Homeassistant 0.53 in your hassio install,
which normally shortly follows a "normal" homeassistant release.

**Comment by robmarkcole** [comment]
I'm now seeing 'Image not available' under 0.53 on Pi-zero-W

![image](https://user-images.githubusercontent.com/11855322/30260262-388516a2-96be-11e7-9c47-093ef40d8cf3.png)

**Comment by gollo** [comment]
Have you any log output to share?

**Comment by Yabk** [comment]
I'm seeing the same thing on pi3


Here are some logs: [logs.txt](https://github.com/home-assistant/hassio/files/1292200/logs.txt)

**Comment by memodeladej** [comment]
rasppberry 3, Hass.io , version 0.53.1  I have the same problem

**Comment by aguinane** [comment]
Same issue in Hass.io v0.53.1. Nothing in the log looked relevant:

```
2017-09-15 10:27:14 WARNING (MainThread) [homeassistant.setup] Setup of media_player is taking over 10 seconds. 
2017-09-15 10:27:20 WARNING (MainThread) [homeassistant.setup] Setup of tts is taking over 10 seconds. 
2017-09-15 10:27:26 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds. 
```

**Comment by kotopoulos10** [comment]
i am getting the same problem as well in v0.57.3 any workaround or solution?

**Comment by knutella** [comment]
Same issue Home Assistant 0.61.1 and pi3

**Comment by doscas** [comment]
Same issue.
Last version: 0.62.1 on a pi3

**Comment by Weberan89** [comment]
Samie issue.
Last version: 0.63.2 on a pi3

**Comment by NedSin** [comment]
Same here ...

Fresh Installed HASS.IO

**Comment by jaatuli** [comment]
Same issue. Version 0.63.3
![image](https://user-images.githubusercontent.com/15844851/36600417-dea76e9e-18ba-11e8-9e06-5906b7c1d7c3.png)

**Comment by robmarkcole** [comment]
Please there is no need to repeat posting the same info here
