### ISSUE TITLE
Add-ons won't start - can't find USB device

### ISSUE THREAD

**Issue by marcelodavanzo** [home-assistant/hassio#1265]
**Home Assistant release with the issue:**
0.97.2

**Operating environment (HassOS/Generic):**
Hass.io running in Docker on a Synology NAS DS218+

**Supervisor logs:**
```
19-08-25 22:30:13 INFO (SyncWorker_0) [hassio.docker.interface] Stop addon_a0d7b954_vscode application
19-08-25 22:30:15 INFO (SyncWorker_0) [hassio.docker.interface] Clean addon_a0d7b954_vscode application
19-08-25 22:30:20 ERROR (SyncWorker_4) [hassio.docker] Can't start addon_a0d7b954_vscode: 404 Client Error: Not Found ("linux runtime spec devices: error gathering device information while adding custom device "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1996743-if00": lstat /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1996743-if00: no such file or directory")
```

**Description of problem:**
I've plugged a Conbee II stick to my NAS and managed to get it working with marthoc/deCONZ container and communicating with Home Assistant. The problem now is that some add-ons (VSCode for example) cannot be started as they get hung up on the error above.

It looks like a symlink is necessary between /dev/ttyACM0 and the /dev/serial/by-id device above but I can't find a way to do it.

Either that or Hass.io should expose the /dev/serial/by-id device to docker containers.

When I unplug the stick and restart home assistant, the problematic add-ons start just fine so this is definitely the culprit.

How can I fix this issue?

**Comment by pvizeli** [comment]
This installation on Synology is a community-driven project. Please ask on the forum or on the Github project of this installation method.

**Comment by haakonstorm** [comment]
I'm getting the same error after restore of backup after HA crash: (latest HA as of today, rpi4, raspbee HAT for zigbee)

```
[hassio.docker] Can't start addon_core_deconz: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/bus/usb": no such file or directory
```
Will keep looking for answers, but this was the first that popped up via google.
