### ISSUE TITLE
Every time I use systemd Hassio throws an error

### ISSUE THREAD

**Issue by cbarratt** [home-assistant/hassio#127]
I'm using Hass IO on a bare Ubuntu 16.04.3 LTS machine via docker. 

I'm getting this same error every time i use systemd, this occurs even when I'm not touching any of the hassio services too. i.e im restarting X service and i'll see the below:

`systemd[1]: [/etc/systemd/system/hassio-hc.service:1] Missing '='.`

**Comment by frenck** [comment]
@cbarratt This issue is almost a year old, and I'm unable to reproduce it.
Is this still an issue for you?

**Comment by cbarratt** [comment]
Hey, I actually just stopped using the hassio and reverted back to a standard homeassistant install
