### ISSUE TITLE
CoreDNS keep failing, no external web API call working.

### ISSUE THREAD

**Issue by MatteGary** [home-assistant/hassio#1271]
**Home Assistant release with the issue:**
0.98.1

**Operating environment (HassOS/Generic):**
HassOS 2.12 running on a RasPi 3

**Supervisor logs:**
`19-09-01 10:56:51 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-01 10:56:51 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
19-09-01 10:56:51 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-09-01 10:56:51 INFO (SyncWorker_15) [hassio.docker.interface] Clean hassio_dns application
19-09-01 10:56:54 INFO (SyncWorker_15) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
19-09-01 10:57:11 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-01 10:57:11 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
19-09-01 10:57:11 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-09-01 10:57:11 INFO (SyncWorker_4) [hassio.docker.interface] Clean hassio_dns application
19-09-01 10:57:14 INFO (SyncWorker_4) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
19-09-01 10:57:31 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-01 10:57:31 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
....`

**Description of problem:**
I'm running HassIO on Raspi3, with Supervisor 184 and HA 0.98.1.
I'm still having issue with dns even after having tried everything i found on community.
This is what system logs look like after a while, with CoreDNS plugin keeping going in error.
If I try eny action related to a web call (like calling a Particle API, or a DarkSky API), error show up in HA logs.

I'm using PiHole as DNS resolver, running on another machine, and I have configured it on this RasPi 3, together with fixed ip.

What do I need to make it work again?
What information do you need from my side to help the investigation?

Thanks

**Comment by MatteGary** [comment]
Additional information:
when running a command that calls a Particle API, this is one of the error showing up in HA logs. As you can see, it is mentioning socket issue in resolving and address



local variable 'request' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 103, in async_service_handler
    headers=headers,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.particle.io:443 ssl:None [Try again]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 349, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 371, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/homeassistant/homeassistant/components/template/cover.py", line 350, in async_close_cover
    await self._close_script.async_run(context=self._context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 151, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 235, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 318, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 98, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 142, in service_handler
    await script.async_turn_on(variables=service.data, context=service.context)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 214, in async_turn_on
    raise err
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 209, in async_turn_on
    await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 151, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 235, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 318, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 98, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 115, in async_service_handler
    _LOGGER.error("Client error %s.", request.url)
UnboundLocalError: local variable 'request' referenced before assignment

**Comment by pvizeli** [comment]
can you post the output of `hassio dns info` and input of `/PATH_TO_MY_SHARE/dns/corefile` ?

**Comment by MatteGary** [comment]
Here is the output of hassio dns info command

host: 172.30.32.3
latest_version: "1"
locals:
- dns://192.168.1.125
servers:
- dns://1.1.1.1
- dns://9.9.9.9
version: "1"

My local network is 192.168.1.1/24 and my PiHole ip host is 192.168.1.1

**Comment by MatteGary** [comment]
I don’t find the path to dns folder you requested, can you be more precise? Thanks

**Comment by pvizeli** [comment]
Default is `/usr/share/hassio`

What is inside `hassio dns logs`?

**Comment by MatteGary** [comment]
If i run

hassio dns logs

Nothing is shown...

And i don’t have a folder in /usr/share named hassio.

Sorry i mistyped earlier (i’m on business trip and writing from mobile), my pihole is at 192.168.1.125, my router is at 192.168.1.1

**Comment by pvizeli** [comment]
Do you have debug access?

Yes: the file is on `/mnt/data/supervisor/dns/corefile` and please send me the output of `journalctl -f` on point the coredns stop.

**Comment by pvizeli** [comment]
`hassio dns logs` if we get the correct moment, he should print somethings, hopefully also the error

**Comment by MatteGary** [comment]
![image](https://user-images.githubusercontent.com/7734219/64159763-00017a80-ce3b-11e9-8e15-f3216d1d3dfe.png)

I cannot run the journalctl command nor find the corefile file... 
I'll try to replicate a web api call issue and see in hassio dns logs

**Comment by MatteGary** [comment]
I don't see anything in logs even by running

`hassio dns logs --log-level Verb`

**Comment by pvizeli** [comment]
yes, journalctl and corefile work only with debug access.

I should log the ouput to log file on error. For now, you should able to get an output with `docker logs -f hassio_dns` if you disable the protection mode on your community ssh add-on and restart it. You need repeat the command until the container is created

**Comment by MatteGary** [comment]
I enabled debug_mode in ssh connection, and I run the command `docker logs -f hassio_dns` for a while (every now and then for 20 min), but nothing shows up.

I guess it is oddly strange that I cannot collect any information in order to help you analyze this issue, right?

**Comment by MatteGary** [comment]
I've tried to update HA to 0.98.2, this is the HassIO System logs showing more error

19-09-03 15:08:03 INFO (SyncWorker_3) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
19-09-03 15:08:11 INFO (SyncWorker_16) [hassio.docker.interface] Stop homeassistant application
19-09-03 15:08:12 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-03 15:08:12 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
19-09-03 15:08:12 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-09-03 15:08:12 INFO (SyncWorker_18) [hassio.docker.interface] Clean hassio_dns application
19-09-03 15:08:16 INFO (SyncWorker_18) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
19-09-03 15:08:32 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-03 15:08:32 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
19-09-03 15:08:32 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-09-03 15:08:32 INFO (SyncWorker_8) [hassio.docker.interface] Clean hassio_dns application
19-09-03 15:08:35 INFO (SyncWorker_8) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
19-09-03 15:08:45 ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/services/mqtt/publish: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection reset by peer]
19-09-03 15:08:45 ERROR (MainThread) [hassio.api.proxy] Error on API for request services/mqtt/publish
19-09-03 15:08:45 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
19-09-03 15:08:45 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API connection is closed
19-09-03 15:08:50 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:08:50 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:08:50 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:08:52 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-03 15:08:52 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
19-09-03 15:08:52 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-09-03 15:08:52 INFO (SyncWorker_12) [hassio.docker.interface] Clean hassio_dns application
19-09-03 15:08:55 INFO (SyncWorker_12) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
19-09-03 15:08:55 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:08:55 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:08:55 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:00 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:00 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:00 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:05 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:05 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:05 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:11 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:11 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:11 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:11 INFO (SyncWorker_16) [hassio.docker.interface] Clean homeassistant application
19-09-03 15:09:12 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-03 15:09:12 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
19-09-03 15:09:12 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-09-03 15:09:12 INFO (SyncWorker_3) [hassio.docker.interface] Clean hassio_dns application
19-09-03 15:09:15 INFO (SyncWorker_17) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.98.2
19-09-03 15:09:16 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:16 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:16 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:17 INFO (SyncWorker_3) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
19-09-03 15:09:21 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:21 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:21 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:26 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:26 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:26 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:31 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:31 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:31 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:32 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-03 15:09:32 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
19-09-03 15:09:32 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-09-03 15:09:32 INFO (SyncWorker_14) [hassio.docker.interface] Clean hassio_dns application
19-09-03 15:09:35 INFO (SyncWorker_14) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
19-09-03 15:09:36 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:36 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:36 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:39 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
19-09-03 15:09:39 ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-09-03 15:09:39 INFO (MainThread) [hassio.auth] Home Assistant not running, check cache
19-09-03 15:09:39 INFO (MainThread) [hassio.auth] Cache hit for mqtt
19-09-03 15:09:41 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:41 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:41 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:46 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:46 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:46 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:51 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:51 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:51 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:09:52 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-03 15:09:52 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
19-09-03 15:09:52 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-09-03 15:09:52 INFO (SyncWorker_9) [hassio.docker.interface] Clean hassio_dns application
19-09-03 15:09:55 INFO (SyncWorker_9) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
19-09-03 15:09:56 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:09:56 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:09:56 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:10:01 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:10:01 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:10:01 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:10:06 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:10:06 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:10:06 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
19-09-03 15:10:10 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-09-03 15:10:10 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.98.2
19-09-03 15:10:10 INFO (SyncWorker_17) [hassio.docker.interface] Cleanup images: ['homeassistant/raspberrypi3-homeassistant:0.98.1']
19-09-03 15:10:11 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-09-03 15:10:11 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-09-03 15:10:12 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-09-03 15:10:12 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
19-09-03 15:10:12 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-09-03 15:10:12 INFO (SyncWorker_14) [hassio.docker.interface] Clean hassio_dns application
19-09-03 15:10:12 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running

**Comment by pvizeli** [comment]
You can send me an email with your instance URL and login (admin) data, and I will look into the issue.

Otherwiese you need get debug access: https://developers.home-assistant.io/docs/en/hassio_debugging.html#ssh-access-to-the-host

After that you can get the log of issue with `journalctl -f` and the input of the files: `/mnt/data/supervisor/dns/*`

**Comment by pvizeli** [comment]
There was an issue with image. A repull solved it

**Comment by violuke** [comment]
I've having the same issue. How can I repull the image? Thanks

**Comment by skateman** [comment]
@pvizeli I tried to repull the image, but it has the same hash `e5edbd61b477` on `aarch64` and it's still failing

**Comment by srynearson** [comment]
I believe I am having a similar issue. What do you mean by repull the image?

`20-03-31 23:21:54 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-31 23:21:54 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-31 23:21:54 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-31 23:21:54 INFO (SyncWorker_32) [supervisor.docker.interface] Clean hassio_dns application
20-03-31 23:21:54 INFO (SyncWorker_32) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3
20-03-31 23:22:14 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-31 23:22:14 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-31 23:22:14 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-31 23:22:14 INFO (SyncWorker_10) [supervisor.docker.interface] Clean hassio_dns application
20-03-31 23:22:14 INFO (SyncWorker_10) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3
20-03-31 23:22:34 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-31 23:22:34 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-31 23:22:34 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-31 23:22:34 INFO (SyncWorker_10) [supervisor.docker.interface] Clean hassio_dns application
20-03-31 23:22:35 INFO (SyncWorker_10) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3
20-03-31 23:22:54 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-31 23:22:54 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-31 23:22:54 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-31 23:22:54 INFO (SyncWorker_6) [supervisor.docker.interface] Clean hassio_dns application
20-03-31 23:22:54 INFO (SyncWorker_6) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3
20-03-31 23:23:14 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-31 23:23:14 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-31 23:23:14 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-31 23:23:14 INFO (SyncWorker_0) [supervisor.docker.interface] Clean hassio_dns application
20-03-31 23:23:14 INFO (SyncWorker_0) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3
20-03-31 23:23:34 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-31 23:23:34 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-31 23:23:34 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-31 23:23:34 INFO (SyncWorker_18) [supervisor.docker.interface] Clean hassio_dns application
20-03-31 23:23:35 INFO (SyncWorker_18) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3
20-03-31 23:23:54 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-31 23:23:54 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-31 23:23:54 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-31 23:23:54 INFO (SyncWorker_13) [supervisor.docker.interface] Clean hassio_dns application
20-03-31 23:23:54 INFO (SyncWorker_13) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3
20-03-31 23:24:14 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-31 23:24:14 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-31 23:24:14 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-31 23:24:14 INFO (SyncWorker_23) [supervisor.docker.interface] Clean hassio_dns application
20-03-31 23:24:15 INFO (SyncWorker_23) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3`

**Comment by pvizeli** [comment]
`ha dns update --version 3`

**Comment by skateman** [comment]
@pvizeli well, it version 3 is doing the same thing on aarch64 :confused:

**Comment by skateman** [comment]
Same thing happens with the `aarch64-hassio-cli` container, but I don't know where to report that...

**Comment by srynearson** [comment]
> `ha dns update --version 3`
That command gave me the following error. 
Error: Version 3 is already in use.

**Comment by srynearson** [comment]
> > `ha dns update --version 3`
> > That command gave me the following error.
> > Error: Version 3 is already in use.

Well, I say that didnt work because of the error.. but I am no longer getting the DNS errors in the logs.. weird. Thanks you!

**Comment by pvizeli** [comment]
@skateman if  you run HassOS please open a issue on OS repository and we look what the issue is.
If you run the supervised installation, you need take you linux knowloage and search the error to fix the issue 👍

**Comment by skateman** [comment]
@pvizeli yeah, I was able to trace it back to a bug in docker itself https://github.com/moby/moby/issues/20550
