### ISSUE TITLE
rpi-rf module not found

### ISSUE THREAD

**Issue by xeroiv** [home-assistant/hassio#128]
When I installed hass.io I edited the configuration.yaml to include my rf switch component ( https://home-assistant.io/components/switch.rpi_rf/ ). However when I restarted home assistant it failed to load completely and I was greeted with an error in my log file.

`2017-08-02 00:55:39 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform rpi_rf Traceback (most recent call last): File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 164, in _async_setup_platform SLOW_SETUP_MAX_WAIT, loop=self.hass.loop) File "/usr/lib/python3.6/asyncio/tasks.py", line 352, in wait_for return fut.result() File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result raise self._exception File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run result = self.fn(*self.args, **self.kwargs) File "/usr/lib/python3.6/site-packages/homeassistant/components/switch/rpi_rf.py", line 50, in setup_platform import rpi_rf ModuleNotFoundError: No module named 'rpi_rf'`

Is there a way to include the rpi-rf module into the hass.io base image?

**Comment by pvizeli** [comment]
Should be fix in next base image

**Comment by xeroiv** [comment]
rpi-rf module now loads in hassio 0.51

**Comment by pvizeli** [comment]
yeah next home-assistant image

**Comment by snelweg** [comment]
> yeah next home-assistant image/release not hassio
What does that mean?
No support in Hassio?
Is there a workaround to get rf working on Hassio?

**Comment by pvizeli** [comment]
We support it: https://github.com/home-assistant/hassio-build/blob/master/homeassistant/generic/Dockerfile#L18

**Comment by disrupted** [comment]
@snelweg I would like to know as well. trying to sniff the rf codes using the rpi_rf_receive.py script but I am getting a `ModuleNotFoundError: No module named 'rpi_rf'`error

**Comment by snelweg** [comment]
I deleted hass.io and used the 'normal'  route with Raspbian .
Now everything works and I am happy.

Will give hass.io another go in a few weeks, hopefully it will work beter then (or there is better documentation.)
(Really thankfull for both Hass.io and homeassistant, but there are still some things to be irroned out before hass.io will go mainstream.)
