### ISSUE TITLE
RFC: Pre_start script

### ISSUE THREAD

**Issue by rbflurry** [home-assistant/hassio#1282]
Currently I am trying to run a socat command prior to homeassistant container startup. For more on why see here (https://community.home-assistant.io/t/add-network-protocol-support-to-zigbee-and-zwave-integrations/136056)

I know this can be done using my own dockerfile or another solution but I wanted to see if this was within scope of hassio so that way I can continue to use the great features and updates provided by the maintainers.  I have found other dockerfiles of users that are straying from hassio for this functionally, 

I am proposing that if a file in /config or some other location called pre_start.sh exists those commands are run prior to 
`python3 -m homeassistant --config /config`

something like updating https://github.com/home-assistant/hassio/blob/dev/entry.sh to:

```
#!/bin/bash
set -e

udevd --daemon
udevadm trigger

if test -f "/config/pre_start.sh"  -a  $HOSTNAME = "homeassistant" ; then
  /config/pre_start.sh
fi

if CMD="$(command -v "$1")"; then
  shift
  exec "$CMD" "$@"
else
  echo "Command not found: $1"
  exit 1
fi

```

Thank you.

**Comment by pvizeli** [comment]
You can open an https://github.com/home-assistant/architecture requests

**Comment by rbflurry** [comment]
Done. https://github.com/home-assistant/architecture/issues/285
