### ISSUE TITLE
DNS resolution problem because host core-samba (Add-On) has no own docker IP

### ISSUE THREAD

**Issue by tyborall** [home-assistant/hassio#1295]
**Home Assistant release with the issue:** 0.990b1 (problem exists since Hass.io DNS was introduced)
**Last working Home Assistant release (if known):** not known
**Operating environment (Hass.io/Docker/Windows/etc.):** Hass.io
**Component/platform:** Hass.io DNS
**Description of problem:** It's easy to reproduce. Install MariaDB Add-On and Samba Add-On. Just set the hostname for connection in the Maria DB Add-On from "%" to "homeassistant" and you will see in the error log, that host "core-samba" is not allowed to connect. All components with Maria DB connection will fail then.
The problem is that in the /etc/hosts on the Host system homeassistant and core-samba share the same IP and because "core-samba" is written to the /etc/hosts after "homeassistant" and as it will read in sequential order the internal (docker) IP resolves to core-samba. That's why the internal DNS is broken if you work with internal hostnames.
**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
**Traceback (if applicable):**
**Additional information:**

**Comment by pvizeli** [comment]
![image](https://user-images.githubusercontent.com/15338540/65515137-fd94bc80-dede-11e9-8d25-36913e4d7a02.png)

I can't see any issue. It is allowed to respond to a reverse DNS lookup with multiple hostnames. Look like the issue is on mariadb they did not support the RFC for DNS lookups.

**Comment by tyborall** [comment]
Hi Pascal. You are absolutely right that it is allowed to respond with multiple RDNS hostnames. But many applications always use the last in the sequential order if they don't support it natively.
As the MariaDB is the official add-on and it should be possible to restrict by hostname why not just give all of the containers an own docker IP? It will fix this issue at the end and I see no other issues when giving each of the docker container an unique own IP?

**Comment by pvizeli** [comment]
Maybe we can inject somethings on add-on start into hosts file
