### ISSUE TITLE
Error when adding a esphome flashed sonoff device

### ISSUE THREAD

**Issue by xadonxander** [home-assistant/hassio#1296]
I get the following error when trying clicking the configure button in the discovered devices area.

http://192.168.1.4:8123/frontend_latest/chunk.43dcfc6e5b8d18714299.js:1007:141 TypeError: e.model is undefined

I am not sure what is causing this issue. I have other esphome devices up and running.

**Comment by frenck** [comment]
This was an issue with the 0.99 release and has been fixed in Home Assistant 0.99.2.
