### ISSUE TITLE
Configure new devices discovered [SOLVED] 

### ISSUE THREAD

**Issue by diego065** [home-assistant/hassio#1297]
After the installation of the new versione (188, Home Assistant 0.99.0), when a new device is automatically discovered the button "configure" doesn't work and it is impossibile to add the device! This happened to me for example with esphome devices, ikea and google cast.

Thanks in advance

**Comment by xadonxander** [comment]
Please check your log and see if you are getting the same error I am. If so I already opened a ticket for it.

**Comment by diego065** [comment]
This is the error I get:
`https://192.168.1.145:8123/frontend_latest/chunk.43dcfc6e5b8d18714299.js:1007:164 Uncaught TypeError: Cannot read property 'item' of undefined`

**Comment by diego065** [comment]
Solved in the new versione (0.99.2)
Thanks
