### ISSUE TITLE
Endpoint with name already exists in network host

### ISSUE THREAD

**Issue by lukasleitsch** [home-assistant/hassio#1309]
I have an issue with starting the addon glance. I created an issue in the addon repo. Unfortunately it seems it's not an issue of the addon. Maybe it's a issue with hass.io.

https://github.com/hassio-addons/addon-glances/issues/33

The addon doesn't start in my setup. Raspberry Pi 3B+ with the current version of Hass.io. After loading the addon the following error appears in the system log of Hass.io. The logs of the plugin don't show any entries.

```
19-09-25 19:04:40 ERROR (SyncWorker_13) [hassio.docker] Can't start addon_a0d7b954_glances: 403 Client Error: Forbidden ("endpoint with name addon_a0d7b954_glances already exists in network host")
```
Running `hassio supervisor repair` doesn't solve the issue.

I hope you can help me with this issue. Thanks

**Comment by cogneato** [comment]
Have you tried a reboot of the whole device? (not a restart of Home Assistant?)

**Comment by lukasleitsch** [comment]
Yes, i did some reboots of the whole device.

I don't know why but now it works again.
