### ISSUE TITLE
Git Pull Addon - Fails to clone repo to config directory

### ISSUE THREAD

**Issue by riweston** [home-assistant/hassio#131]
I receive the following error;

`'''starting version 3.2.2
[Info] cleanup config folder and clone from repositorie
[Error] can't clone https://github.com/$repo.git into /config`

**Comment by bbbenji** [comment]
Confirming I can duplicate this issue.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-addons/pull/166
