### ISSUE TITLE
New install cannot obtain ipv4 address

### ISSUE THREAD

**Issue by tomlut** [home-assistant/hassio#1310]
**Home Assistant release with the issue:**

Latest NUC image. 0.99.3 I suppose I cant tell because it wont connect to the network
**Operating environment (HassOS/Generic):**

HassOS NUC image on an Intel i5 PC
**Supervisor logs:**

Cannot access.

**Description of problem:**
Brand new install of Hassio on an M.2 drive in a spare PC I have. I want to set this up as backup hardware to be run up with my latest snapshot in case of hardware failure of my main system while I am away for a year.

However I can not get this install to obtain an ipv4 address by DHCP or by assigning a static address. Things I've tried: https://community.home-assistant.io/t/hassio-network-issues/139626

**Comment by LukasQ** [comment]
> The BIOS update fixed the problem though.
So, CLOSED, right?

**Comment by tomlut** [comment]
Unfortunately not.

The BIOS update allowed me to run the PC headless (it wouldn't start without a monitor attached before the update). 

After the update I could run Hassio headless on Ubuntu Server LTS perfectly but still could not get the Hassio image installed direct to the M.2 drive to run. It would not pick up an IPv4 address when installed that way.

**Comment by LukasQ** [comment]
So, Hassio is working if you use the manual Setup on Ubuntu base, but not if you clone the image to your m.2ssd, right?
There is an issue with SSD Setup, see: https://github.com/home-assistant/hassos/issues/164

**Comment by tomlut** [comment]
Correct. However as it is the NUC (not Raspberry Pi) image, so I'm not sure the link you posted is relevant. 

I installed a previous version of the NUC image (around May 2019) on the SDD of a different PC and it works perfectly. Which begs the question: Is it the new image or different hardware at fault?

As it is going to be impossible to tell without me reinstalling the NUC image on my main Home Assistant instance (the one that worked) and as I have a working system on Ubuntu I'm going to close this.
