### ISSUE TITLE
OpenVPN installation in HASS via SSH is removed after every reboot

### ISSUE THREAD

**Issue by manju-rn** [home-assistant/hassio#1317]
**Home Assistant release with the issue:**

99.2

**Last working Home Assistant release (if known):**
None

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hass.io on RPI3B+
**Component/platform:**

**Description of problem:**
Through SSH into Hass.io, i installated the OpenVPN. This works great as I am able to download and configure my VPN providers. However, whenever I restart the Hass.io  the OpenVPN installation is gone.  I mean there is no /etc/OpenVPN  folder which was existing earlier.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**

**Comment by frenck** [comment]
@manju-rn That is expected behavior, the SSH add-on gives you access to a (stateless) container, not to an operating system.

Add-ons provide the means for things like this.

**Comment by manju-rn** [comment]
okay. So how to I SSH to operating system - Alipne Linux in this case?  Because my RPI3B+ is installed with Hass.io and there is no seperate SSH access to Alpine

**Comment by frenck** [comment]
If you use HassOS, there is debug access available to the operating system, however, HassOS is an embedded Linux and does not provide you the means to install those things on the host system.

Again: This is where add-ons come in. There are VPN add-ons available that allow you to do those things.
