### ISSUE TITLE
Issues with auto_uart in an LXC container

### ISSUE THREAD

**Issue by parrel** [home-assistant/hassio#1320]
**Home Assistant release with the issue:**
0.99.2

**Operating environment (HassOS/Generic):**
Installed on a Proxmox host within an LXC container running Ubuntu 18.06 (generic)

**Supervisor logs:**
Log of device that does not exist in container
```
19-10-03 09:56:15 ERROR (SyncWorker_12) [hassio.docker] Can't start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/mem": no such file or directory")
```

Example of hardware tab in hassio
```
serial:
/dev/ttyS24
/dev/ttyS30
/dev/ttyS20
/dev/ttyS0
/dev/ttyS16
/dev/ttyS14
/dev/ttyS31
(more here but stripped it a bit)
```

**Description of problem:**

The issue I'm experiencing is that all HassIO addons with the config option `auto_uart` set to  `true` will not start. See the log of the `/dev/*` device that not exists. 

I found that all the devices that the Hardware tab shows, are devices of my host, but not of the LXC container. That's why I'm getting the 500 error.

On host:
```
root@terra:~# ls -lh /dev/tty*
crw-rw-rw- 1 root tty     5,  0 Oct  2 19:57 /dev/tty
crw--w---- 1 root tty     4,  0 Oct  2 19:57 /dev/tty0
crw--w---- 1 root tty     4,  1 Oct  2 19:57 /dev/tty1
crw--w---- 1 root tty     4, 10 Oct  2 19:57 /dev/tty10
crw--w---- 1 root tty     4, 11 Oct  2 19:57 /dev/tty11
crw--w---- 1 root tty     4, 12 Oct  2 19:57 /dev/tty12
crw--w---- 1 root tty     4, 13 Oct  2 19:57 /dev/tty13
```

In LXC container:
```
root@hassio:/# ls -lh /dev/tty*
crw-rw-rw- 1 root root 5, 0 Sep 27 12:50 /dev/tty
lrwxrwxrwx 1 root root    8 Sep 27 12:50 /dev/tty1 -> lxc/tty1
lrwxrwxrwx 1 root root    8 Sep 27 12:50 /dev/tty2 -> lxc/tty2
```

A temporary fix for me was to disable the `auto_uart` option in the sourcecode of a plugin, but this takes away the ease of updating etc. (https://github.com/esphome/issues/issues/624)

Is there a way to support LXC containers, so that only the devices in the LXC container are mapped to the docker containers? If not, is there a way to disable the `auto_uart` option without modifying the source of the addon?

Thanks!

**Comment by pvizeli** [comment]
Auto uart don't map `/dev/mem`. They read the active serial devices from udev. `/dev/mem` is mostly used for GPIO handling.

**Comment by parrel** [comment]
Oh, then the `"gpio": true` option is also causing this issue. 

I tried to map the `dev/mem` device to my LXC container, and it didn't give this error anymore:
```
19-10-03 09:56:15 ERROR (SyncWorker_12) [hassio.docker] Can't start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/mem": no such file or directory")
```

But instead of `/dev/mem` I got something like `/dev/ttyS28`

```
19-10-03 09:56:15 ERROR (SyncWorker_12) [hassio.docker] Can't start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/ttyS28": no such file or directory")
```

**Comment by parrel** [comment]
I did some digging and found out that my issue might be in pyudev. 

https://github.com/home-assistant/hassio/blob/b0dd043975b663f8d6574f3287442f9449717f09/hassio/misc/hardware.py#L41

A fix for me would be to check below this line (and the other lines with `self.context.list_devices()`), if the device exists with `os.path.lexists()`.

Example:
`import os`
``` python
for device in self.context.list_devices(subsystem="tty"):
    exists = os.path.lexists(device.device_node) 
    if exists and ("ID_VENDOR" in device.properties or RE_TTY.search(device.device_node)):
      dev_list.add(device.device_node)

return dev_list
```

Would it be possible to add this 'existance' check, or will it cause issues?

**Comment by blademckain** [comment]
@parrel 
how did you map  the /dev/mem inside the lxc container?
can you show me the commands?

**Comment by pvizeli** [comment]
We don't support LXC - please don't use that or make no issue reports if you do that
