### ISSUE TITLE
HUSBZ-1 does not function at at all

### ISSUE THREAD

**Issue by ryan-durbin** [home-assistant/hassio#133]
Version 50.2

GoControl Linear HUSBZ-1 does work when plugged into a rPi3.

`lsusb`
`Bus 001 Device 002: ID 0424:9514`
`Bus 001 Device 001: ID 1d6b:0002`
`Bus 001 Device 003: ID 0424:ec00`
`Bus 001 Device 004: ID 10c4:8a2a`

`ls /dev`
`char     full     mqueue   ptmx     random   stderr   stdout   urandom`
`fd       kmsg     null     pts      shm      stdin    tty      zero`

When I unplug and plug it back in I get this

`dmesg`
`[  711.676441] usb 1-1.5: USB disconnect, device number 4`
`[  711.677797] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0`
`[  711.678088] cp210x 1-1.5:1.0: device disconnected`
`[  711.683246] cp210x ttyUSB1: cp210x converter now disconnected from ttyUSB1`
`[  711.683475] cp210x 1-1.5:1.1: device disconnected`
`[  715.236070] usb 1-1.5: new full-speed USB device number 5 using dwc_otg`
`[  715.343224] usb 1-1.5: New USB device found, idVendor=10c4, idProduct=8a2a`
`[  715.343251] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=5`
`[  715.343267] usb 1-1.5: Product: HubZ Smart Home Controller`
`[  715.343283] usb 1-1.5: Manufacturer: Silicon Labs`
`[  715.343297] usb 1-1.5: SerialNumber: C0F007B8`
`[  715.348649] cp210x 1-1.5:1.0: cp210x converter detected`
`[  715.355046] usb 1-1.5: cp210x converter now attached to ttyUSB0`
`[  715.358094] cp210x 1-1.5:1.1: cp210x converter detected`
`[  715.360235] usb 1-1.5: cp210x converter now attached to ttyUSB1`
`[  716.985825] cp210x ttyUSB1: failed to set baud rate to 300`
`[  730.048683] cp210x ttyUSB1: failed to set baud rate to 300`

**Comment by pvizeli** [comment]
Hass config?

**Comment by jaredjensen** [comment]
Did you ever get this working?  I'm having the same issue with the same setup.

**Comment by ryan-durbin** [comment]
Yes I did at one point. The device will never show up properly in your pi, even /dev will be empty. Just ignore that and enter the device into into your configuration.yaml like it says to do. Just works.. don't ask why... Lol

⁣Sent from BlueMail ​

**Comment by jaredjensen** [comment]
It's encouraging that yours worked.  Following the instructions, I created /etc/udev/rules.d/99-usb-serial.rules:
```
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="8a2a", SYMLINK+="zwave"
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="8a2a", SYMLINK+="zigbee"
```

And updated my configuration.yaml:
```
zwave:
  usb_path: /dev/zwave

zigbee:
  device: /dev/zigbee
```

But the HA dashboard still reports "The following components and platforms could not be set up: zigbee, zwave" after a restart.  I'll keep futzing with it.

**Comment by jaredjensen** [comment]
I got it working without aliases by modifying my configuration.yaml:
```
zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: zigbee.db
```

**Comment by ryan-durbin** [comment]
Yeah that looks familiar, good work! I can't explain why it works, it just does...

⁣Sent from BlueMail ​

**Comment by marc-gist** [comment]
this ever get fixed? i can't get it to work... z-wave appears to be, but no zigbee

**Comment by bradfitz** [comment]
@jaredjensen, your udev rules aren't doing what you expect. They were both matching and ending up with the symlinks both pointing to the same node (the last configuration presented by the USB device).

I ended up with a `/etc/udev/rules.d/99-usb-serial.rules` of:

```
# For Linear HUSBZB-1. Creates:
#      /dev/zwave0zig1_00  (for zwave)
#      /dev/zwave0zig1_01   (for zigbee)
SUBSYSTEMS=="usb", ENV{.LOCAL_ifNum}="$attr{bInterfaceNumber}"
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="8a2a", SYMLINK+="zwave0zig1_%E{.LOCAL_ifNum}"
```

I used a verbose name as a hint to myself in the future about which config is zwave (0) vs zigbee (1).

I additionally have two other Z-Wave USB sticks, which I match more simply with:

```
# Z-Stick Gen2
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="0001", SYMLINK+="zwavegen2"

# Z-Stick Gen5
SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="zwavegen5"
```

**Comment by frenck** [comment]
Closing this issue, reasoning: This issue predates HassOS.
If this is still an issue, feel free to open a new one with some recent logs.

Thanks 👍
