### ISSUE TITLE
Allow privilege SYS_RAWIO

### ISSUE THREAD

**Issue by radhus** [home-assistant/hassio#134]
I'm trying to use write an addon for some GPIO connected devices on my Raspberry Pi using the RPi.GPIO Python plugin. However, it needs access to /dev/mem and it's not sufficient to specify it with `"devices":["/dev/mem:/dev/mem:rwm"]`, because it leads to the following error:

`RuntimeError: No access to /dev/mem.  Try running as root!`

I think we need to set SYS_RAWIO on the container to allow this, but only NET_ADMIN and SYS_ADMIN is allowed in the validation script, see line 40:
https://github.com/home-assistant/hassio/blob/dev/hassio/addons/validate.py#L40

Can we add SYS_RAWIO to the allowed list as well? I haven't been able to test if that solves everything, otherwise I would've sent a PR instead :)

**Comment by pvizeli** [comment]
Yeah you can make a PR. A new release go out this evening

**Comment by torvitas** [comment]
Hi,
my addon wont start if I add "privileged": ["SYS_RAWIO"], to config.json.
I wasn't able to find a way to debug this.
Greetings, Sascha
