### ISSUE TITLE
Supervisor does not run in Privileged mode.

### ISSUE THREAD

**Issue by marah314** [home-assistant/hassio#1374]
**Home Assistant release with the issue:**
0.99.3

**Operating environment (HassOS/Generic):**
HassOS 2.10

**Supervisor logs:**
![IMG_1820](https://user-images.githubusercontent.com/56310449/68982686-54947f00-0808-11ea-83fb-90a1d19dcf7e.PNG)
![IMG_1821](https://user-images.githubusercontent.com/56310449/68982702-6118d780-0808-11ea-9f2f-1dd8b6c3cac9.PNG)

**Description of problem:**
I´m running on a Pi 3B+. And get from time to time the error: "ERROR (MainThread) [hassio.supervisor] Supervisor does not run in Privileged mode. Hassio runs with limited functionality." It is not possible to reach the GUI (web or app) and also not possible to access via ssh. The only solution to get it running again is to restart the Pi.

**Comment by frenck** [comment]
Please update HassOS to the latest version.

**Comment by marah314** [comment]
Thanks for feedback. I've updated HA to version 0.101.3, but I assume you actually mean that I should update HassOS (from 2.10)? I thought that HassOS would update along with HA to the "preferred" version, but maybe that's not the case?
Not sure how I update HassOS

**Comment by marah314** [comment]
I Found where to update HassOS and are now on version 2.12. After rebooting I get the same error.

starting version 3.2.8
19-11-16 20:20:26 INFO (MainThread) [__main__] Initialize Hass.io setup
19-11-16 20:20:27 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/armhf-hassio-supervisor with version 192
**_19-11-16 20:20:27 ERROR (MainThread) [hassio.supervisor] Supervisor does not run in Privileged mode. Hassio runs with limited functionality!_**
19-11-16 20:20:27 INFO (MainThread) [__main__] Setup HassIO
19-11-16 20:20:27 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
19-11-16 20:20:28 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
19-11-16 20:20:28 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: de.pengutronix.rauc - /
19-11-16 20:20:28 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
19-11-16 20:20:28 INFO (MainThread) [hassio.host.info] Update local host information
19-11-16 20:20:28 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
19-11-16 20:20:28 INFO (MainThread) [hassio.host.services] Update service information
19-11-16 20:20:28 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
19-11-16 20:20:29 INFO (MainThread) [hassio.host.network] Update local network DNS information
19-11-16 20:20:29 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
19-11-16 20:20:29 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
19-11-16 20:20:29 INFO (MainThread) [hassio.host.services] Reload local service hassos-apparmor.service
19-11-16 20:20:29 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
19-11-16 20:20:29 INFO (SyncWorker_1) [hassio.docker.interface] Attach to homeassistant/armhf-hassio-dns with version 1
19-11-16 20:20:29 INFO (MainThread) [hassio.dns] Update resolv from Supervisor
19-11-16 20:20:29 WARNING (MainThread) [hassio.dns] Can't write local resolv: [Errno 13] Permission denied: '/etc/resolv.conf'
19-11-16 20:20:29 INFO (MainThread) [hassio.misc.forwarder] Start DNS port forwarding to 172.30.32.3
19-11-16 20:20:29 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-11-16 20:20:29 INFO (SyncWorker_2) [hassio.docker.interface] Clean hassio_dns application
19-11-16 20:20:34 INFO (SyncWorker_2) [hassio.docker.dns] Start DNS homeassistant/armhf-hassio-dns with version 1
19-11-16 20:20:34 INFO (SyncWorker_0) [hassio.docker.interface] Attach to homeassistant/raspberrypi3-homeassistant with version 0.101.3
19-11-16 20:20:35 INFO (MainThread) [hassio.hassos] Detect HassOS 2.12 on host system
19-11-16 20:20:35 INFO (SyncWorker_4) [hassio.docker.hassos_cli] Found HassOS CLI homeassistant/armhf-hassio-cli with version 14
19-11-16 20:20:36 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/7be23ff5 repository
19-11-16 20:20:36 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
19-11-16 20:20:36 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
19-11-16 20:20:37 INFO (MainThread) [hassio.store] Load add-ons from store: 63 all - 63 new - 0 remove
19-11-16 20:20:37 INFO (MainThread) [hassio.addons] Found 9 installed add-ons
19-11-16 20:20:37 INFO (SyncWorker_3) [hassio.docker.interface] Attach to homeassistant/armhf-addon-deconz with version 3.6
19-11-16 20:20:37 INFO (SyncWorker_6) [hassio.docker.interface] Attach to dwelch2101/dropbox-sync-armhf with version 1.3.0
19-11-16 20:20:37 INFO (SyncWorker_15) [hassio.docker.interface] Attach to homeassistant/armv7-addon-check_config with version 3.1
19-11-16 20:20:37 INFO (SyncWorker_1) [hassio.docker.interface] Attach to hassioaddons/node-red-armv7 with version 5.0.2
19-11-16 20:20:37 INFO (SyncWorker_5) [hassio.docker.interface] Attach to homeassistant/armv7-addon-samba with version 8.2
19-11-16 20:20:37 INFO (SyncWorker_14) [hassio.docker.interface] Attach to homeassistant/armv7-addon-ssh with version 6.4
19-11-16 20:20:37 INFO (SyncWorker_0) [hassio.docker.interface] Attach to hassioaddons/mqtt with version v1.1.0
19-11-16 20:20:37 INFO (SyncWorker_10) [hassio.docker.interface] Attach to homeassistant/armv7-addon-duckdns with version 1.10
19-11-16 20:20:37 INFO (SyncWorker_11) [hassio.docker.interface] Attach to homeassistant/armv7-addon-configurator with version 3.6
19-11-16 20:20:38 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
19-11-16 20:20:38 INFO (MainThread) [hassio.snapshots] Found 3 snapshot files
19-11-16 20:20:38 INFO (MainThread) [hassio.discovery] Load 1 messages
19-11-16 20:20:38 INFO (MainThread) [hassio.ingress] Load 0 ingress session
19-11-16 20:20:38 INFO (MainThread) [hassio.secrets] Load Home Assistant secrets: 1
19-11-16 20:20:38 INFO (MainThread) [__main__] Run Hass.io
19-11-16 20:20:38 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
19-11-16 20:20:38 INFO (MainThread) [hassio.addons] Phase 'initialize' start 0 add-ons
19-11-16 20:20:38 INFO (MainThread) [hassio.addons] Phase 'system' start 1 add-ons
19-11-16 20:20:41 INFO (SyncWorker_18) [hassio.docker.addon] Start Docker add-on homeassistant/armhf-addon-deconz with version 3.6
19-11-16 20:20:46 INFO (MainThread) [hassio.addons] Phase 'services' start 5 add-ons
19-11-16 20:20:56 INFO (SyncWorker_4) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-samba with version 8.2
19-11-16 20:21:00 INFO (SyncWorker_19) [hassio.docker.addon] Start Docker add-on dwelch2101/dropbox-sync-armhf with version 1.3.0
19-11-16 20:21:00 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on hassioaddons/mqtt with version v1.1.0
19-11-16 20:21:01 INFO (SyncWorker_13) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-ssh with version 6.4
19-11-16 20:21:01 INFO (SyncWorker_3) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-duckdns with version 1.10
19-11-16 20:21:06 INFO (SyncWorker_1) [hassio.docker.interface] Start homeassistant/raspberrypi3-homeassistant
19-11-16 20:21:10 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_mqtt
19-11-16 20:21:16 WARNING (MainThread) [hassio.api.security] No API token provided for /api/config
19-11-16 20:21:29 WARNING (MainThread) [hassio.api.security] No API token provided for /api/config
19-11-16 20:22:29 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-11-16 20:22:29 INFO (MainThread) [hassio.addons] Phase 'application' start 2 add-ons
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options username
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options password
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options ssl
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options certfile
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options keyfile
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options allowed_networks
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options banned_ips
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options banlimit
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options notify_service
19-11-16 20:22:29 WARNING (MainThread) [hassio.addons.validate] Unknown options port
19-11-16 20:22:36 INFO (SyncWorker_18) [hassio.docker.addon] Start Docker add-on hassioaddons/node-red-armv7 with version 5.0.2
19-11-16 20:22:39 INFO (SyncWorker_3) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-configurator with version 3.6
19-11-16 20:22:44 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
19-11-16 20:22:44 INFO (MainThread) [hassio.core] Hass.io is up and running
19-11-16 20:22:45 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nodered
19-11-16 20:22:56 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_nodered

**Comment by pvizeli** [comment]
This warning is not an issue. I should avoid it.
