### ISSUE TITLE
Can't upgrade to 0.102.2 

### ISSUE THREAD

**Issue by tzfrs** [home-assistant/hassio#1385]
**Home Assistant release with the issue:**
0.101.2

**Operating environment (HassOS/Generic):**
Running HassOS on Raspberry Pi 3.

**Supervisor logs:**
These are the logs after pressing the Upgrade button

```
19-11-27 14:17:42 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
19-11-27 14:17:52 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.102.2
19-11-27 14:17:52 INFO (SyncWorker_12) [hassio.docker.interface] Update image homeassistant/raspberrypi3-homeassistant:0.101.2 to homeassistant/raspberrypi3-homeassistant:0.102.2
19-11-27 14:17:52 INFO (SyncWorker_12) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.102.2.
19-11-27 14:17:58 ERROR (SyncWorker_12) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.102.2 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").
19-11-27 14:17:59 WARNING (MainThread) [hassio.homeassistant] Update Home Assistant image fails
```

**Description of problem:**
0.101.2 is the first version I installed. I installed it with the official docs on a Raspberry Pi including hassOS

Now, I saw that a new update is available. Because it supports Almond, I want to update! However, as you can see in the logs, it fails with the error message

`ERROR (SyncWorker_12) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.102.2 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")`

**Steps I tried to solve**

* Restarted the Raspberrry Pi
* Restarted the Supervisor (which is up2date btw)
* Checked disk space (43% usage for root `/`)

I saw this link https://community.home-assistant.io/t/update-problem/103892/39 which suggests wiping and restoring from snapshot. Is this the only way to fix this issue? :/

**Comment by frenck** [comment]
`mnt/data/docker/overlay2/l: invalid argument`

Looks like you are experiencing corruption of your Docker storage. You can try fixing it by running `hassio supervisor repair` from the SSH commandline.

**Comment by tzfrs** [comment]
Thank you for your answer @frenck. I did it, the command completed sucessfully and I can now press the update button again without it failing right after a few seconds. However, I still have some questions and would be awesome if you could answer them :)

* What does the supervisor do that a repair fixes the corruption of the Docker storage?
* How did you know that the Docker storage was corrupted? Yes, there's a docker path in the error message, but how did you know? And how do you know the supervisor fixes this?
* The update is running now. Is there any way I can monitor the update? The loading cirlce is just spinning and spinning. How do I know what progress it does? If I connect my Raspberry by HDMI it doesn't post any other logs, so is it somehow possible to see the current logs? Can I freely navigate inside hassio overview or just in the ssh session? 

Thank you in advance and thank you once again for helping me. 👍

**Comment by tzfrs** [comment]
Once again, thank you @frenck. The upgrade has now succeeded and I'm running 0.102.2!

**Comment by frenck** [comment]
The overlay is a known issue, unfortunately, it happens quite a bit (especially on underpowered Raspberry Pi's as it seems), hence the repair was built.

It is basically a big cleanup/remove and re-install action for everything Docker (you config is stored outside of Docker, so that is never lost this way).

Glad you got it resolved! :+1:
