### ISSUE TITLE
Python-Miio update attempt on every server reboot at shutdown and start

### ISSUE THREAD

**Issue by TriptonPt** [home-assistant/hassio#1387]
There seems to be an update twice at every reboot (on shutdown and start) for python-miio .

After running the command manually I concluded it's already the version it's trying to upgrade to but each time the command is run it takes over 1 minute before I get the error stating it's already the latest version !

This results in what is aproximately 3 minutes of extra time for restarting HA !

Here is the command that is run on every reboot ( both on shutdown and start) :

/usr/local/bin/python3 -m pip install python-miio==0.4.7 --no-cache-dir --upgrade --constraint /usr/src/homeassistant/homeassistant/package_constraints.txt --find-links https://wheels.home-assistant.io/alpine-3.10/armv7/ --prefer-binary

Hassio Version 102.1

No custom packages related to xiaomi miio in any way

According to coders of Miio integration this is probably a hassio bug !

**Comment by frenck** [comment]
Commented on original issue home-assistant/home-assistant#29210.

This is not the correct place for this problem. Let's continue the discussion on the original issue.
