### ISSUE TITLE
How to select from custom docker images and optionally include devices

### ISSUE THREAD

**Issue by snowzach** [home-assistant/hassio#1389]
I have a question that I'm trying to figure out how to help people with my add-on... 

I have a system DOODS that has a number of docker images and possible USB devices.

I have docker images for several variants of AMD64 which different CPU instructions. I also have USB devices that can be used. I don't want to maintain a ton of different copies of the same add-on.. I would like the user to be able to select the docker image from their config. I would also like to be able to include or not include devices. Hyper-V doesn't support USB passthrough so my default config with devices chokes on Hyper-V. 

It really would be ideal to allow customizing this stuff from the user config vs having to maintain a myriad of different Add-Ons for each possible configuration. 

There has to be a better way to do this... What am I missing?

**Comment by pvizeli** [comment]
Dynamic device options are not support currently. There was some requests and people they want implement that. I look forward for this.

We can try to discover a fix with udev if you want implement it?

**Comment by snowzach** [comment]
I am not sure I follow. The issue is that for this add-on there may or may not be a device. The problem is that you cannot change the device config to say there isn't a device. The add-on properly discovers the device regardless of the name. The udev fix doesn't help me at all. I would rather be able to customize the config to specify devices and docker image tags as I also need to be able to specify different possible docker image tags depending on cpu flags supported.

**Comment by pvizeli** [comment]
That means, this will be only possible if someone work on this. I close this PR now because we don't allow feature requests as issue. If you want work on this feature feel free to reopen it for discusion about the implementation.
