### ISSUE TITLE
Pleas address Bluetooth issues on Raspberry Pi

### ISSUE THREAD

**Issue by hteggi** [home-assistant/hassio#1390]
**Home Assistant release with the issue:**
Not known.

**Operating environment (HassOS/Generic):**
Hassos 3.5, hassio 192, Home Assistant 0.102.3
Please provide details about your environment.
Raspberry PI 3B 

**Description of problem:**
Not sure if this is the correct place to post this but after searching for a solution my bluetooth problems I suspect this must be a system problem and not a component problem and that's why I post it as an issue here.

My problem is that Mi Flora plant, Xiaomi BLE Temperature/Humidity and https://github.com/gkreitz/homeassistant-airthings stop getting data after about 7 hours. To get data again I have to restart hassos and then they work for about 7 hours again. Mi Flora plant, Xiaomi BLE was working well for quite some time but I am not sure when they broke but think it was about 1 year or more ago. The custom airthings component I have only used for a few days but it is exact same behavior as the two others. And when searching for a solution I come over so many threads regarding these issues and BLE tracker issues but no solution. From what I see there is a lot of experienced users have investigated this problem for long time but nobody has found a solution so I hope that somebody with the right skills could have a look at this.

I have limited skills and need detailed instructions to perform troubleshooting.

Thanks a lot for this great automation software.
Regards
Henning

**Comment by pvizeli** [comment]
try 3.6

**Comment by hteggi** [comment]
Airthings custom component has been running since yesterday after upgrade to 3.6 so this looks very good. Will test with Miflora and Xiaomi Mi Temperature and Humidity tomorrow.

**Comment by pvizeli** [comment]
The issue was an defect bluetooth driver from RPi. They need 6month to revert it
