### ISSUE TITLE
Hassio Supervisor 192 still showing as the current release from CLI, even after 193 has been relased for over a month.

### ISSUE THREAD

**Issue by dap35** [home-assistant/hassio#1401]
**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**
HassOS (32 bit) installed on Rpi3
HassOS 2.12 , Hassio 192, HA 103.0

**Supervisor logs:**
19-12-17 01:47:53 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
19-12-17 01:48:08 INFO (MainThread) [hassio.api.security] /hassos/info access from core_ssh
19-12-17 01:48:44 INFO (MainThread) [hassio.api.security] /hassos/update access from core_ssh
19-12-17 01:48:44 WARNING (MainThread) [hassio.hassos] Version 2.12 is already installed
19-12-17 01:48:50 INFO (MainThread) [hassio.api.security] /hassos/update/cli access from core_ssh
19-12-17 01:48:50 WARNING (MainThread) [hassio.hassos] Version 15 is already installed for CLI
19-12-17 01:49:32 INFO (MainThread) [hassio.api.security] /hassos/update/cli access from core_ssh
19-12-17 01:49:32 WARNING (MainThread) [hassio.hassos] Version 15 is already installed for CLI
19-12-17 01:54:47 INFO (MainThread) [hassio.api.security] /supervisor/update access from core_ssh
19-12-17 01:58:20 INFO (MainThread) [hassio.api.security] /supervisor/info access from core_ssh
19-12-17 02:01:25 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
core-ssh:~# 

**Description of problem:**

GitHub repository has shown 193 as the current release since November, but attempts to upgrade go nowhere.

**Comment by frenck** [comment]
192 is the stable release version, 193 is a stable candidate, which has not been promoted to stable yet.

Thus this is expected behavior.
