### ISSUE TITLE
Update not completed and option to update gone

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/hassio#142]
When attempting to Update from 0.50.2 to 0.51 on both a pi-zero and a pi-3, the Update appeared to have finished but the OS has not been updated and the option to update has disappeared from the dashboard. Have restarted both but still on 0.50.2 and no option to update

**Comment by pvizeli** [comment]
Yeah it is the hassio update a not homeassistant update :)

**Comment by pvizeli** [comment]
hassio = supervisor
