### ISSUE TITLE
hdmi_cec not working in Hass.io - "No adapters found"

### ISSUE THREAD

**Issue by elmurato** [home-assistant/hassio#143]
Hello all!
Unfortunately the hdmi_cec component is not working for me in Hass.io. Before the migration from Hassbian it was working without any problems. Now I get following warnings in the log:
```
2017-08-10 07:53:13 WARNING (<concurrent.futures.thread.ThreadPoolExecutor object at 0x72e71ff0>_0) [pycec] Not initialized. Waiting for init. 
2017-08-10 07:53:13 WARNING (<concurrent.futures.thread.ThreadPoolExecutor object at 0x73d18f10>_0) [pycec.cec] No adapters found
2017-08-10 07:53:14 WARNING (<concurrent.futures.thread.ThreadPoolExecutor object at 0x72e71ff0>_0) [pycec] Not initialized. Waiting for init. 
2017-08-10 07:53:15 WARNING (<concurrent.futures.thread.ThreadPoolExecutor object at 0x72e71ff0>_0) [pycec] Not initialized. Waiting for init. 
2017-08-10 07:53:16 WARNING (<concurrent.futures.thread.ThreadPoolExecutor object at 0x72e71ff0>_0) [pycec] Not initialized. Waiting for init. 
2017-08-10 07:53:17 WARNING (<concurrent.futures.thread.ThreadPoolExecutor object at 0x72e71ff0>_0) [pycec] Not initialized. Waiting for init.
```

The last few messages are being repeated each second. Regarding the documentation libcec should be installed by default. But I was not able to check this via the SSH addon (cec-client not found - I think because the SSH addon is a docker container itself, right?)

- Raspberry Pi 3
- Supervisor: 0.52
- Home-Assistant: 0.51.2
- Host OS: 1.0

This is my config:
```
hdmi_cec:
  osd_name: HASSIO
  devices:
    KD65XD7504: 0.0.0.0
    PS4PRO: 2.0.0.0
    STRDH540: 3.0.0.0
    RASPBERRYPI: 3.1.0.0
```
Any help would be highly appreciated. Please let me know if you need more data from me. Thanks!

**Comment by frenck** [comment]
Sorry, I'm just throwing in a wild suggestion: My guess is that the Docker does not pass the `/dev/vchiq` device into the container...

**Comment by pvizeli** [comment]
Try: `curl -d '{"devices": ["vchiq"]}' http://hassio/homeassistant/options`

**Comment by elmurato** [comment]
I will try that as soon as I'm home. I'm running Let's Encrypt + DuckDNS. So should your command be like this:
`curl -d '{"devices": ["vchiq"]}' https://<subdomain>.duckdns.org/homeassistant/options`
?

**Comment by elmurato** [comment]
@pvizeli 
Ok I think you meant to enter that command via SSH. Did it now, no error returned, so the command was successful. Restarted Home Assistant, but no luck. Same warning message that no adapter was found :(

**Comment by pvizeli** [comment]
HomeAssistant docker run with full privileged mode and have install all raspberrypi packages: https://pkgs.alpinelinux.org/contents?branch=v3.6&name=raspberrypi&arch=armhf&repo=main

**Comment by elmurato** [comment]
I also found this information:

> No cec devices are found on raspberry pi since libcec isn't compiled with raspberry pi enabled. Recompiling libcec with flags -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib fixes the issue

[https://hub.docker.com/r/homeassistant/raspberrypi3-homeassistant/](https://hub.docker.com/r/homeassistant/raspberrypi3-homeassistant/)

Could this be a problem with the Home-Assistant Docker image? Should this issue be posted to Home-Assistant?

**Comment by mflores180** [comment]
When I type this :curl -d ‘{“devices”: [“vchiq”]}’ http://hassio/homeassistant/options
I get this : {“result”: “ok”, “data”: {}}core-ssh:~#

**Comment by pvizeli** [comment]
@elmurato https://github.com/home-assistant/hassio-build/tree/master/homeassistant please follow our docker guidelines and not only copy past that stuff.

@mflores180 that was only a test and not for productive

**Comment by daniel9522** [comment]
@pvizeli could you please help i have the same problem but i have no idea on what to do by reading the chat above 
would appreciate any help, thanks

**Comment by bryantebeek** [comment]
Same problem here, would be great if it could be fixed. Libcec is not compiled for Raspberry Pi.

**Comment by frenck** [comment]
Seems like there are RPi specific build flags missing in the APK provided by Alpine Linux...?

**Comment by gollo** [comment]
That is the case from what I can see
```
root@hassio:~# docker exec -ti homeassistant /bin/bash
bash-4.3# cec-client -l
libCEC version: 4.0.2, git revision: v3.5.0+4185-e4cc4b7, compiled on Sat Apr 22 00:39:57 UTC 2017 by buildozer@build-3-6-armhf.nethq.org on Linux 4.4.19 (armv8l), features: P8_USB, DRM, P8_detect, randr
Found devices: NONE
```

Note there is no RPI in the list of features.
Also adding /dev/vhciq shouldn't be needed as the container runs privileged anyway.  Alpine based docker images [exist](https://hub.docker.com/r/romerod/rpi-alpine-libcec-py/) with the support compiled in, but I'm not sure how to integrate that into the hassio homeassistant docker image without breaking other archs.  Perhaps it needs to go into ./base_image/armhf/Dockerfile? 
In any case I have raised [#7754](http://bugs.alpinelinux.org/issues/7754) with Alpine to hopefully get the support compiled into the official package.

**Comment by elmurato** [comment]
Thank you @gollo ! Now we have the confirmation. So I see 2 ways how this could be fixed:

- Wait for fixed Alpine Linux (see above)
- Add build of libcec with RPI config inside:
  - https://github.com/home-assistant/hassio-build/blob/master/homeassistant/machine/raspberrypi
  - https://github.com/home-assistant/hassio-build/blob/master/homeassistant/machine/raspberrypi2
  - https://github.com/home-assistant/hassio-build/blob/master/homeassistant/machine/raspberrypi3
  - (see https://github.com/jonaseck2/raspberrypi3-homeassistant/blob/master/Dockerfile for a possible fix)

@gollo Could you maybe test this, since you know what you're doing with Docker :D 
Or maybe someone could guide me how to test this? I already have a "real" SSH access to resinOS.

**Comment by pvizeli** [comment]
You can add this into machine docker files. For Tests you can use the buildscripts and make a vm (look into how to a build server) to run that step.

https://github.com/home-assistant/hassio-build

**Comment by elmurato** [comment]
Thank you so much @gollo! Hope that your pull request will be approved and merged soon. Good job!

**Comment by Schmackos** [comment]
Was this ever merged? On 0.55 I have the exact same issue. Hope to get a response or somone to point me to the right solution.

**Comment by gollo** [comment]
This was merged a couple of releases ago, and is working ok for me.  Can
you send a log?

**Comment by pvizeli** [comment]
You need a raspberry image on a raspberry hardware

**Comment by Schmackos** [comment]
Thanks for the quick turn-around.

Running HASS.IO on RPI3

https://www.dropbox.com/s/7odznw49e8u2ccu/Screenshot%202017-10-17%2000.27.11.png?dl=0

**Comment by gollo** [comment]
Are you able to run 

```root@hassio:~# docker exec homeassistant /usr/bin/cec-client -l```

you have to be root in the host OS with hassio/homeassistant running to do this.  If you can it should look like

```libCEC version: 4.0.2, git revision: libcec-4.0.2, compiled on Sun Oct  8 07:28:28 UTC 2017 by root@ee5963fbf88a on Linux 4.9.48-v7+ (armv7l), features: P8_USB, DRM, P8_detect, RPi
Found devices: 1

device:              1
com port:            RPI
vendor id:           2708
product id:          1001
firmware version:    1
type:                Raspberry Pi
```

**Comment by Schmackos** [comment]
No, not able to run. Wondering if I am logged in as root?

core-ssh:~# docker exec homeassistant /usr/bin/cec-client -l
-ash: docker: not found

**Comment by gollo** [comment]
Yes, unfortunately you can't use the SSH add-on for this, it has to be access to the host (see below).

Does this configuration work for you for example with hassbian?  Have you proven this to work with your pi/hdmi combination with other software (just plain raspbian)?

If the answer to that is yes, then, if you think you can, follow this for access directly to the host OS

https://home-assistant.io/developers/hassio/debugging/

From there you can run the above docker command.

Anyone else feel free to offer debugging ideas!

**Comment by pvizeli** [comment]
Can you post the output of `cec_scan` addon?

**Comment by codymhorton** [comment]
Hi sorry to post on an older thread but I'm having the same issue as I mentioned here: https://community.home-assistant.io/t/help-with-hdmi-cec-config/31290.  I do get info when I cec-client -l:

`libCEC version: 4.0.2, git revision: libcec-4.0.2, compiled on Mon Oct 23 20:47:13 UTC 2017 by root@ee5963fbf88a on Linux 4.9.48-v7+ (armv7l), features: P8_USB, DRM, P8_detect, RPi
Found devices: 1

device:              1
com port:            RPI
vendor id:           2708
product id:          1001
firmware version:    1
type:                Raspberry Pi
`
but when I run cec_scan I get error vc_cec could not be initialised over and over.

Can anyone help me with this? I can get any info you need I've already enabled debugger mode. I'm using a PI 3 with hass.io. Thanks!!!!

**Comment by ezstar** [comment]
same issue

**Comment by shekhardivekar** [comment]
Does anyone know solution? Facing same problem.

**Comment by Dsn072** [comment]
Same issue here. 

I use the actual Hassio. 

Systemlog: 

`Not initialized. Waiting for init.
`
HDMI Cec Scan Addon: 

`starting` version 3.2.2
opening a connection to the CEC adapter...
ERROR:   [             108]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [             108]	Open - vc_cec could not be initialised
ERROR:   [             108]	could not open a connection (try 1)``

**Comment by harveydobson** [comment]
I have the same issue.

Using Hassio OS, tried latest, had this issue, tried upgrading to the beta on the off-chance it would work, same issue. 

HassOS 1.10
Hass.io supervisor version 👍 
 130

Fresh install today onto Raspberry Pi 3B (32bit however - as this was the recommended option)

Logged into docker container:
```
bash-4.4# cec-client -l
libCEC version: 4.0.2, git revision: libcec-4.0.2, compiled on Wed Sep 12 15:04:24 UTC 2018 by root@3dc421e74991 on Linux 4.4.120-mainline-rev1 (armv7l), features: P8_USB, DRM, P8_detect, RPi
Found devices: 1

device:              1
com port:            RPI
vendor id:           2708
product id:          1001
firmware version:    1
type:                Raspberry Pi
```

Hassio HDMI CEC Add On log output:

```
starting version 3.2.2
opening a connection to the CEC adapter...
ERROR:   [              91]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [              91]	Open - vc_cec could not be initialised
ERROR:   [              91]	could not open a connection (try 1)
ERROR:   [            1091]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            1091]	Open - vc_cec could not be initialised
ERROR:   [            1091]	could not open a connection (try 2)
ERROR:   [            2092]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            2092]	Open - vc_cec could not be initialised
ERROR:   [            2092]	could not open a connection (try 3)
ERROR:   [            3092]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            3093]	Open - vc_cec could not be initialised
ERROR:   [            3093]	could not open a connection (try 4)
ERROR:   [            4093]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            4093]	Open - vc_cec could not be initialised
ERROR:   [            4093]	could not open a connection (try 5)
ERROR:   [            5094]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            5094]	Open - vc_cec could not be initialised
ERROR:   [            5094]	could not open a connection (try 6)
ERROR:   [            6094]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            6094]	Open - vc_cec could not be initialised
ERROR:   [            6095]	could not open a connection (try 7)
ERROR:   [            7095]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            7095]	Open - vc_cec could not be initialised
ERROR:   [            7095]	could not open a connection (try 8)
ERROR:   [            8096]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            8096]	Open - vc_cec could not be initialised
ERROR:   [            8096]	could not open a connection (try 9)
ERROR:   [            9096]	RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
ERROR:   [            9096]	Open - vc_cec could not be initialised
ERROR:   [            9096]	could not open a connection (try 10)
unable to open the device on port RPI
ERROR:   [           10097]	could not start CEC communications
```
