### ISSUE TITLE
Unable to update to 0.50.2 - 404 Client Error: Not Found ("No such image: homeassistant/raspberrypi3-homeassistant:0.51.2").

### ISSUE THREAD

**Issue by djmcp** [home-assistant/hassio#151]
When attempting update, receive the following error:

`404 Client Error: Not Found ("No such image: homeassistant/raspberrypi3-homeassistant:0.51.2").`

Applicable log info:

```
17-08-14 19:36:58 INFO (SyncWorker_4) [hassio.dock] Update docker 0.50.2 with homeassistant/raspberrypi3-homeassistant:0.51.2
17-08-14 19:36:58 INFO (SyncWorker_4) [hassio.dock] Pull image homeassistant/raspberrypi3-homeassistant tag 0.51.2.
17-08-14 19:37:38 ERROR (SyncWorker_4) [hassio.dock] Can't install homeassistant/raspberrypi3-homeassistant:0.51.2 -> 404 Client Error: Not Found ("No such image: homeassistant/raspberrypi3-homeassistant:0.51.2").
```
I have restarted both home assistant and the host raspberry pi 3 multiple times as well as attempted update from both front-end and cmd line via 'hassio homeassistant update'.  Both error with the same info about 'No such image'.  Space doesn't seem to be an issue as I have several gigs free.  I've been unable to locate a solution via the forums, subreddit, or general googling.

**Comment by djmcp** [comment]
I keep hearing that this is a space issue but I'm not understanding why that would be the case given that both SMB drive mapping and executing df directly from an ssh session show a ton of free space.

```
core-ssh:~# df -h
Filesystem                Size      Used Available Use% Mounted on
none                     13.3G      3.0G      9.6G  24% /
tmpfs                   486.1M      4.0K    486.1M   0% /dev
tmpfs                   486.1M         0    486.1M   0% /sys/fs/cgroup
/dev/mmcblk0p6           13.3G      3.0G      9.6G  24% /data
/dev/mmcblk0p6           13.3G      3.0G      9.6G  24% /config
/dev/mmcblk0p6           13.3G      3.0G      9.6G  24% /ssl
/dev/mmcblk0p6           13.3G      3.0G      9.6G  24% /addons
/dev/mmcblk0p6           13.3G      3.0G      9.6G  24% /backup
/dev/mmcblk0p6           13.3G      3.0G      9.6G  24% /share
/dev/mmcblk0p6           13.3G      3.0G      9.6G  24% /etc/resolv.conf
/dev/mmcblk0p6           13.3G      3.0G      9.6G  24% /etc/hostname
/dev/mmcblk0p6           13.3G      3.0G      9.6G  24% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   486.1M      4.0K    486.1M   0% /proc/timer_list
tmpfs                   486.1M      4.0K    486.1M   0% /proc/timer_stats
tmpfs                   486.1M      4.0K    486.1M   0% /proc/sched_debug
tmpfs                   486.1M         0    486.1M   0% /sys/firmware
core-ssh:~# 
```

**Comment by dennismadsen** [comment]
Did you find a solution? I'm having the same issue now trying to update to 0.57.1.

**Comment by cormacc** [comment]
I'm also having this issue trying to update from 0.56.2 to 0.57.2 (Raspberry PI 2). Deleted my home_assistant-v2 db  which had hit about 450 m and now have 1gb free on the sd card. Update still fails with the 404 error

**Comment by djmcp** [comment]
I didn't have any luck with the update from 50.2 to 51.2.  I ended up saving off my config and reimaging hass.io on the SD card.  I haven't had any trouble upgrading since then.

**Comment by goyney** [comment]
I am having this happen as well. I reimaged my SD card with a fresh install a couple versions ago and it is happening again. The update process has NEVER worked from the UI. The only time I have ever gotten it to successfully work is from the terminal. Now, neither work.

**Comment by pvizeli** [comment]
What is the size of SD card?

**Comment by grahamwetzler** [comment]
I'm having the same problem. However I'm not using a Pi. I'm running the generic Linux install on an Ubuntu 16.04 LXC container.

```
18-01-01 16:14:33 INFO (MainThread) [__main__] Initialize Hassio setup
18-01-01 16:14:33 INFO (MainThread) [__main__] Setup HassIO
18-01-01 16:14:33 INFO (SyncWorker_0) [hassio.dock.supervisor] Attach to supervisor homeassistant/amd64-hassio-supervisor with version 0.78
18-01-01 16:14:33 INFO (MainThread) [hassio.host_control] Send 'info' to HostControl.
18-01-01 16:14:33 INFO (MainThread) [hassio.host_control] Receive from HostControl: { "type": "generic", "version": "0.3", "last_version": "0.3", "hostname": "hass-io", "features": ["shutdown", "reboot", "update"], "os": "GNU/Linux" }.
18-01-01 16:14:33 INFO (SyncWorker_1) [hassio.dock.interface] Attach to image homeassistant/qemux86-64-homeassistant with version landingpage
18-01-01 16:14:33 INFO (MainThread) [hassio.addons.git] Load addon /data/addons/core repository
18-01-01 16:14:33 INFO (MainThread) [hassio.addons] Load addons: 19 all - 19 new - 0 remove
18-01-01 16:14:33 INFO (MainThread) [hassio.addons] Startup initialize run 0 addons
18-01-01 16:14:33 INFO (MainThread) [hassio.snapshots] Found 0 snapshot files
18-01-01 16:14:33 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/home-assistant/hassio-addons repository
18-01-01 16:14:33 INFO (MainThread) [__main__] Run HassIO
18-01-01 16:14:33 INFO (MainThread) [hassio.dns] Start DNS port forwarding for host add-ons
18-01-01 16:14:33 INFO (MainThread) [hassio.updater] Fetch update data from https://raw.githubusercontent.com/home-assistant/hassio/master/version.json
18-01-01 16:14:33 INFO (MainThread) [hassio.core] Start hassio api on 172.30.32.2
18-01-01 16:14:33 INFO (MainThread) [hassio.core] HassIO reboot detected
18-01-01 16:14:33 INFO (MainThread) [hassio.homeassistant] Setup HomeAssistant
18-01-01 16:14:33 INFO (SyncWorker_3) [hassio.dock.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.60.
18-01-01 16:14:33 INFO (MainThread) [hassio.addons] Load addons: 19 all - 0 new - 0 remove
18-01-01 16:15:22 ERROR (SyncWorker_3) [hassio.dock.interface] Can't install homeassistant/qemux86-64-homeassistant:0.60 -> 404 Client Error: Not Found ("no such image: homeassistant/qemux86-64-homeassistant:0.60: No such image: homeassistant/qemux86-64-homeassistant:0.60").
18-01-01 16:15:22 WARNING (MainThread) [hassio.homeassistant] Error on install HomeAssistant. Retry in 60sec
```

```
root@hass-io:~# df -h
Filesystem                        Size  Used Avail Use% Mounted on
/dev/mapper/pve-vm--100--disk--1  7.9G  3.1G  4.4G  42% /
none                              492K     0  492K   0% /dev
tmpfs                              16G     0   16G   0% /dev/shm
tmpfs                              16G  8.3M   16G   1% /run
tmpfs                             5.0M     0  5.0M   0% /run/lock
tmpfs                              16G     0   16G   0% /sys/fs/cgroup
shm                                64M     0   64M   0% /var/lib/docker/containers/806e372716ef2564e8fef2f467b7b5b693e03bfebed95c5d7444da03fbc089d0/shm
shm                                64M     0   64M   0% /var/lib/docker/containers/d5d8f9f92fef576a1c95cb0eadeeb6cd948bd297e5303d17851cb55a9118bca6/shm
```

**Comment by yannick9906** [comment]
Any solution here yet? I ran into the same issue updating to 0.61.1 from 0.59.2 (since 0.60 also failed)

```
core-ssh:~# hassio supervisor logs

Error decoding json invalid character '\x1b' looking for beginning of value: 18-01-18 23:51:12 INFO (SyncWorker_4) [hassio.docker.interface] Restart homeassistant/raspberrypi2-homeassistant
18-01-18 23:51:39 INFO (SyncWorker_11) [hassio.docker.interface] Update docker 0.59.2 with homeassistant/raspberrypi2-homeassistant:0.61.1
18-01-18 23:51:39 INFO (SyncWorker_11) [hassio.docker.interface] Pull image homeassistant/raspberrypi2-homeassistant tag 0.61.1.
18-01-18 23:54:17 ERROR (SyncWorker_11) [hassio.docker.interface] Can't install homeassistant/raspberrypi2-homeassistant:0.61.1 -> 404 Client Error: Not Found ("No such image: homeassistant/raspberrypi2-homeassistant:0.61.1").
```

**Comment by sandro-defender** [comment]
# same here :( any solutions ? 
`18-01-27 10:31:15 INFO (SyncWorker_1) [hassio.docker.interface] Update docker 0.59.2 with homeassistant/raspberrypi3-homeassistant:0.61.1
18-01-27 10:31:15 INFO (SyncWorker_1) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.61.1.
18-01-27 10:31:22 ERROR (SyncWorker_1) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.61.1 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi3-homeassistant:0.61.1: No such image: homeassistant/raspberrypi3-homeassistant:0.61.1").`

**Comment by frenck** [comment]
@sandro-defender Have you ensured/checked you have enough disk space available?

**Comment by sandro-defender** [comment]
yes i have lot of free space :( 28% used out of 32 gb

**Comment by ciotlosm** [comment]
@sandro-defender check all partitions for space. There should be more than just one.

**Comment by ciotlosm** [comment]
It was shown earlier if you check posts `core-ssh:~# df -h`

**Comment by sandro-defender** [comment]
`Filesystem                Size      Used Available Use% Mounted on
none                     28.1G      4.5G     22.1G  17% /
tmpfs                   486.1M     60.0K    486.1M   0% /dev
tmpfs                   486.1M         0    486.1M   0% /sys/fs/cgroup
/dev/mmcblk0p3          294.1M    216.7M     61.9M  78% /dev/init
/dev/mmcblk0p6           28.1G      4.5G     22.1G  17% /config
/dev/mmcblk0p6           28.1G      4.5G     22.1G  17% /ssl
/dev/mmcblk0p6           28.1G      4.5G     22.1G  17% /addons
/dev/mmcblk0p6           28.1G      4.5G     22.1G  17% /backup
/dev/mmcblk0p6           28.1G      4.5G     22.1G  17% /share
/dev/mmcblk0p6           28.1G      4.5G     22.1G  17% /data
/dev/mmcblk0p6           28.1G      4.5G     22.1G  17% /etc/resolv.conf
/dev/mmcblk0p6           28.1G      4.5G     22.1G  17% /etc/hostname
/dev/mmcblk0p6           28.1G      4.5G     22.1G  17% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   486.1M     60.0K    486.1M   0% /proc/timer_list
tmpfs                   486.1M     60.0K    486.1M   0% /proc/timer_stats
tmpfs                   486.1M     60.0K    486.1M   0% /proc/sched_debug
tmpfs                   486.1M         0    486.1M   0% /sys/firmware`


seems like everyone have this 

> **/dev/mmcblk0p3**

 partition full how can i acscess it and delete ?

**Comment by Joshfindit** [comment]
This has been going on for a long time. 

Suggestion: Can there be a quick disk-space check before updates are done? That way the logged error could be "Out of disk space on <path>", and maybe even a suggestion to run `docker prune -a`, or a `du` readout of any large folders

**Comment by Joshfindit** [comment]
@frenck as you mention in [this issue](https://github.com/home-assistant/hassio-supervisor/issues/420) it can have multiple known causes. Would it be fair to check for at least a couple of those before failing to a misleading `404`?
