### ISSUE TITLE
Cleanup of intermediate containers on Docker build

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio#160]
## Problem/Motivation

There are a lot of unused containers left behind when building add-ons locally.

This is also reported by other users in the forum:
https://community.home-assistant.io/t/unused-containers-images-not-deleted-by-hass-io/23866

The problem with this is that Hass.io is aimed at smaller devices (e.g., Raspberry PI) and those devices tend to have limited disk space available. Currently, there is no way for the user to clean them up (unless SSH / Docker magic / Portainer).

## Expected behavior

I'd expect to keep the Docker environment as clean as possible.

## Actual behavior

A lot of unused containers & images are left behind.

## Steps to reproduce

Build an add-on (especially one that fails to build in the end).

## Proposed changes

The Docker SDK has an option to force the removal of intermediate containers, even after unsuccessful builds. 

I want to propose a change to this line:
https://github.com/home-assistant/hassio/blob/f9b12a2eb25d7de64b1a2ba1ad3dab6a27128e8f/hassio/dock/addon.py#L206

Add an extra argument to the `build()`method: `forcerm=True`.

Documentation reference: http://docker-py.readthedocs.io/en/stable/images.html?highlight=forcerm

**Comment by pvizeli** [comment]
https://www.pivotaltracker.com/story/show/150387365
https://www.pivotaltracker.com/story/show/150387367

**Comment by JohnMcLear** [comment]
Not sure why this is closed...  It's still a problem...  Can we move to get this re-opened please?

**Comment by agners** [comment]
@JohnMcLear this issue is from 2017, and there are two PRs associated which fix the issue from back then. So it got resolved then.

Meanwhile, our add-on build looks quite a bit different and uses Docker BuildKit since 2025 (see #5974). The build does delete old versions etc.

Can you open a new issue along with specific information what left overs you see today? Thanks.
