### ISSUE TITLE
Build a more generic DNS updater?

### ISSUE THREAD

**Issue by l00mi** [home-assistant/hassio#164]
Something based on https://github.com/Neilpang/acme.sh/tree/master/dnsapi would be really nice.

**Comment by nalipaz** [comment]
I have a start on inadyn but it is failing on armhf and aarch64 for some reason.
https://github.com/nalipaz/hassio-addons/inadyn

My shippable build:
https://app.shippable.com/github/nalipaz/hassio-addons/runs/59/summary/console

**Comment by pvizeli** [comment]
Look to our builder:
https://github.com/home-assistant/hassio-build/tree/master/builder

You need setup crosscompile features or use our build tools

**Comment by nalipaz** [comment]
@pvizeli I think I have it figured out. It isn't the build script that is the problem, rather it is the docker version used on TravisCI and Shippable that I was having issue with. Neither seem to support `ARG` as the first line in Dockerfile. I have worked out a solution using `sed` but both shippable and travis are having issues right now, so I am waiting to publish.

As to the build tools, I did initially use those but when running a compile of an application I was running into timeouts on the build servers I was trying to integrat with. However, when I build using a matrix in the build file it spins up four different threads and avoids the one long-running job that times out.

**Comment by nalipaz** [comment]
I have finished building my Dynamic DNS addon built on Inadyn:
https://github.com/nalipaz/hassio-addons/

Add my repo to your Hass.io if you want to try it out.

**Comment by pvizeli** [comment]
Looks amazing. Please add it to Forum too

**Comment by nalipaz** [comment]
@pvizeli already did, thanks

**Comment by frenck** [comment]
@l00mi Does the add-on provided by @nalipaz fulfill your needs?

**Comment by l00mi** [comment]
@frenck Kinda, actually I try to use a DNS with Cloudflare. So that is why I proposed initially https://github.com/Neilpang/acme.sh/tree/master/dnsapi which are simple SHELL scripts. 

But inadyn is definitely also a solution, except: https://github.com/troglobit/inadyn/issues/182 (-: So I hope I find some time over the Christmas break.

**Comment by frenck** [comment]
Ok, I will keep this issue open in that case.
