### ISSUE TITLE
Add support for stopping Home Assistant to API

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio#175]
## Problem/Motivation

Currently, there is no way to actually stop Home Assistant.
It would be nice to do so if the user wants it to stop.

For example, using OZWCP is made impossible at this moment in time, since using OZWCP requires HA to be terminated.

## Proposed changes

- Adding a `stop` and `start` call to the API.
- Adding the API call's to the CLI present in the SSH add-on.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio/pull/182
