### ISSUE TITLE
Proposed way to start a hassio-addon periodically?

### ISSUE THREAD

**Issue by l00mi** [home-assistant/hassio#179]
Better to keep the addon running and periodically run the script / program, or is there a way to restart the add-on periodically?

**Comment by pvizeli** [comment]
At the moment only with hassio API call. I task a crontab/watchdog for add-ons

**Comment by l00mi** [comment]
So currently I would create a cron entry in the homeassistant container?

**Comment by pvizeli** [comment]
Or automation. You can call the api over the proxy /api/hassio/...

**Comment by l00mi** [comment]
Hmm that sounds promising, where is this API located? How do I authenticate?

**Comment by pvizeli** [comment]
done with automation and 0.55
