### ISSUE TITLE
External connection problem

### ISSUE THREAD

**Issue by nottix** [home-assistant/hassio#181]
Hi,

i have installed the latest stable version of hassio and now my home assistant instance has problems contacting external services like tado, dasksky, telegram and other services.

I mean this is due to DNS configuration problem on Docker container.
This is the DNS configuration:

> nameserver 127.0.0.11
> options ndots:0

There are the errors:

Telegram
`telegram.vendor.ptb_urllib3.urllib3.exceptions.NewConnectionError: <telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xb3d51310>: Failed to establish a new connection: [Errno -
3] Try again`

Darksky
`ERROR (SyncWorker_3) [homeassistant.components.sensor.darksky] Unable to connect to Dark Sky. HTTPSConnectionPool(host='api.darksky.net', port=443): Max retries exceeded with url: /forecas
t/a5be25c8af305dfb608a7cb16e3efdf2/41.8120494,12.4467456?units=si (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb55b0430>: Failed to establish a new
connection: [Errno -3] Try again',))`

**Comment by frenck** [comment]
@nottix Are you still experiencing this issue?

**Comment by nottix** [comment]
@frenck I reinstalled HASS on Rasp3 instead of Rasp1 and everything it's ok now.

**Comment by frenck** [comment]
Ok, Then I'll go ahead and close this one.
Feel free to re-open in case the problem occurs again.
