### ISSUE TITLE
Bootstrap addons/configuration from files in boot partition.

### ISSUE THREAD

**Issue by aequitas** [home-assistant/hassio#188]
It would be nice if you could place a configuration file in the boot partition (like with the network config and root ssh keys) which allow to specify the addons you want to have installed at boot. This will allow for a quicker setup/recovery then having to this manually through the web interface or having to rely on restoring backups.

As a sidenote to have the hass initial configuration directory copied/moved from the boot sector as well allows to completely setup a hassio system in one go.

If I can find time I can dive into this if you think this feature would be worth the effort of merging.

**Comment by pvizeli** [comment]
The problem is, that the boot partition is only 40mb. So we can this also not use to add a snapshot file on it. If you use a mariadb, the snapshot can be over 200MB.

But Yeah, it would be nice to find a flow for faster restore/recovery. So I'm open for this and ideas how that can work 👍

**Comment by aequitas** [comment]
True, my intent is not to restore complete backup of stateful collected data like that in the database, but more the configuration state which will probably be limited to a few kb of yaml files. This allows to treat a RPi device like a stateless component who's functionality can quickly be restored. Since my experience with these devices is that the SD card sadly to often/unexpected fail or cause data corruption.
