### ISSUE TITLE
Startup failures after HostOS 1.1 update

### ISSUE THREAD

**Issue by gollo** [home-assistant/hassio#194]
This happened after upgrading the HostOS via the hassio panel.  Please see attached logs.  The supervisor starts but keeps trying to start the components and fails.

```root@hassio:~# cat /proc/device-tree/model 
Raspberry Pi Model B Rev 1
```

[supervisor.txt](https://github.com/home-assistant/hassio/files/1313353/supervisor.txt

**Comment by pvizeli** [comment]
I think the homeassistant container image going corrupt. I see that before (but only 1-2 times) but I don't kow why. Maybe SDcard.

For fix make a downgrade of hass container and a upgrade or remove the Image and he pull it agen:
```
curl -d '{"version": "0.53"}' http://hassio/homeassistant/update
curl -d '{"version": "0.53.1"}' http://hassio/homeassistant/update
```

**Comment by pvizeli** [comment]
Oh I see that is for all containers excepts Supervisor, strange.

I think the image storage is corrupt. I have no rpi from first generation. I have test it all with rpi3 but I have a old rpi2. I will try a test with rpi2.

I think you need a fresh setup...

**Comment by pvizeli** [comment]
If you run it on a productive System, you can rollback the update:
```
$ hassio-hc
update 1.0
```
or Hass.io CLI:
```
curl -d '{"version": "1.0"}' http://hassio/host/update
```

**Comment by gollo** [comment]
Turns out not enough memory.  Adding swap fixed it, to be investigated in future.
