### ISSUE TITLE
Help with an Install please

### ISSUE THREAD

**Issue by droidforever** [home-assistant/hassio#199]
I have a ubuntu server that is running a resin os.  Would I be able to install a resinos docker instance of  hassiom, example this one "pvizeli/resinos-hassio" on this machine?  Been messing with it a couple days and so far I have been unable to succeed except with the curl install of the amd64 hassio build.  Thank you in advance for your assistance.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-build/tree/master/install

**Comment by frenck** [comment]
@droidforever Did the answer by pvizeli help?
(in other words, can this issue be closed?)
