### ISSUE TITLE
Audio not playing through headphone jack when HDMI connected

### ISSUE THREAD

**Issue by dj21d** [home-assistant/hassio#208]
Hello,

My HDMI port seems to be overriding the headphone jack for audio output when connected. The headphone jack works fine when I do not have an HDMI cable plugged in. I use it for HDMI-CEC on my TV so it is necessary.

My google assistant configs are as such:
```
{
  "mic": "1,0",
  "speaker": "0,0",
  "client_secrets": "google_assistant.json"
}
```

I have tried changing the speaker to 0,1 or 0,2 with no success. Here is a list of my devices.
```
hassio host hardware
{
  "serial": [],
  "input": [
    "C-Media Electronics Inc.       USB PnP Sound Device"
  ],
  "disk": [],
  "audio": {
    "0": {
      "name": "bcm2835 - bcm2835 ALSA",
      "type": "ALSA",
      "devices": {
        "0": "digital audio playback",
        "1": "digital audio playback"
      }
    },
    "1": {
      "name": "USB-Audio - USB PnP Sound Device",
      "type": "Device",
      "devices": {
        "0": "digital audio capture"
      }
    }
  }
}
```

I'm running home assistant 0.54 on a raspberry pi 3b

**Comment by pvizeli** [comment]
We can try to run `amixer cset numid=3 1` to force the jackoutput and make a config options like `rpi3_force_jack` to enable this line. Do you think that would work?

**Comment by dj21d** [comment]
Since I'm running hassio I don't seem to have that function available.

**Comment by pvizeli** [comment]
But we make it available if that fix the problem

**Comment by dj21d** [comment]
Sounds like a good idea. If there is anything I can do to test this plan let me know.

**Comment by dj21d** [comment]
Has there been any update on this issue?

**Comment by dj21d** [comment]
Checking in on this again

**Comment by dj21d** [comment]
@vlumikero The Google Assistant add-on I was having trouble with has added the option to change the audio output between HDMI and Headphone so this is no longer an issue for me
