### ISSUE TITLE
Edimax Switch - latest firmware uses different auth 

### ISSUE THREAD

**Issue by Jshah01** [home-assistant/hassio#209]
I got an Edimax switch today and upgraded to the latest version (2.04).
Looks like they changed their auth so it's not working on hassio.  
Check code and comment here https://gist.github.com/derbot/15f444d679c672ae3edc03f4b5b3897b

**Comment by pvizeli** [comment]
Please open a PR to Home-Assistant repository. Thanks for reporting.
