### ISSUE TITLE
 Hassio HomeAssistant 0.54 & 0.55 - Issue Cannot Install HABridge Add-on (Not Resolved) 

### ISSUE THREAD

**Issue by ibexcentral** [home-assistant/hassio#210]
Hi,

I am running Hassio 1.1 but also tried on 1.0 same issue, I tried this on HomeAssistant 0.54 & 0.55:

https://github.com/notoriousbdg/hassio-addons

When I try to install Ha Bridge Add-on on a fresh install of Hassio with HomeAssistant v0.54 or 0.55 on RaspberryPi3, the Install button turns red immediately the Supervisor log as follows:

17-10-08 10:45:55 INFO (SyncWorker_1) [hassio.dock.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.55
17-10-08 10:47:17 INFO (SyncWorker_14) [hassio.dock.addon] Start build 27e642c6/armhf-addon-ha-bridge:4.5.6p2
17-10-08 10:47:18 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File “/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py”, line 422, in start
resp = yield from self._request_handler(request)
File “/usr/lib/python3.6/site-packages/aiohttp/web.py”, line 306, in _handle
resp = yield from handler(request)
File “/usr/lib/python3.6/site-packages/hassio/api/util.py”, line 31, in wrap_api
answer = await method(api, *args, **kwargs)
File “/usr/lib/python3.6/site-packages/hassio/api/addons.py”, line 176, in install
addon.install(version=version), loop=self.loop)
File “/usr/lib/python3.6/site-packages/hassio/addons/addon.py”, line 467, in install
if not await self.docker.install(version):
File “/usr/lib/python3.6/site-packages/hassio/dock/util.py”, line 18, in wrap_api
return await method(api, *args, **kwargs)
File “/usr/lib/python3.6/concurrent/futures/thread.py”, line 55, in run
result = self.fn(*self.args, **self.kwargs)
File “/usr/lib/python3.6/site-packages/hassio/dock/addon.py”, line 198, in _install
return self._build(tag)
File “/usr/lib/python3.6/site-packages/hassio/dock/addon.py”, line 211, in _build
image = self.docker.images.build(**build_env.get_docker_args(tag))
File “/usr/lib/python3.6/site-packages/docker/models/images.py”, line 175, in build
raise BuildError(chunk[‘error’])
docker.errors.BuildError: Please provide a source image with from prior to run
17-10-08 10:47:19 INFO (SyncWorker_6) [hassio.dock.addon] Start build 27e642c6/armhf-addon-ha-bridge:4.5.6p2
17-10-08 10:47:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File “/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py”, line 422, in start
resp = yield from self._request_handler(request)
File “/usr/lib/python3.6/site-packages/aiohttp/web.py”, line 306, in _handle
resp = yield from handler(request)
File “/usr/lib/python3.6/site-packages/hassio/api/util.py”, line 31, in wrap_api
answer = await method(api, *args, **kwargs)
File “/usr/lib/python3.6/site-packages/hassio/api/addons.py”, line 176, in install
addon.install(version=version), loop=self.loop)
File “/usr/lib/python3.6/site-packages/hassio/addons/addon.py”, line 467, in install
if not await self.docker.install(version):
File “/usr/lib/python3.6/site-packages/hassio/dock/util.py”, line 18, in wrap_api
return await method(api, *args, **kwargs)
File “/usr/lib/python3.6/concurrent/futures/thread.py”, line 55, in run
result = self.fn(*self.args, **self.kwargs)
File “/usr/lib/python3.6/site-packages/hassio/dock/addon.py”, line 198, in _install
return self._build(tag)
File “/usr/lib/python3.6/site-packages/hassio/dock/addon.py”, line 211, in _build
image = self.docker.images.build(**build_env.get_docker_args(tag))
File “/usr/lib/python3.6/site-packages/docker/models/images.py”, line 175, in build
raise BuildError(chunk[‘error’])
docker.errors.BuildError: Please provide a source image with from prior to run
17-10-08 10:47:24 INFO (SyncWorker_5) [hassio.dock.addon] Start build 27e642c6/armhf-addon-ha-bridge:4.5.6p2
17-10-08 10:47:24 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File “/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py”, line 422, in start
resp = yield from self._request_handler(request)
File “/usr/lib/python3.6/site-packages/aiohttp/web.py”, line 306, in _handle
resp = yield from handler(request)
File “/usr/lib/python3.6/site-packages/hassio/api/util.py”, line 31, in wrap_api
answer = await method(api, *args, **kwargs)
File “/usr/lib/python3.6/site-packages/hassio/api/addons.py”, line 176, in install
addon.install(version=version), loop=self.loop)
File “/usr/lib/python3.6/site-packages/hassio/addons/addon.py”, line 467, in install
if not await self.docker.install(version):
File “/usr/lib/python3.6/site-packages/hassio/dock/util.py”, line 18, in wrap_api
return await method(api, *args, **kwargs)
File “/usr/lib/python3.6/concurrent/futures/thread.py”, line 55, in run
result = self.fn(*self.args, **self.kwargs)
File “/usr/lib/python3.6/site-packages/hassio/dock/addon.py”, line 198, in _install
return self._build(tag)
File “/usr/lib/python3.6/site-packages/hassio/dock/addon.py”, line 211, in _build
image = self.docker.images.build(**build_env.get_docker_args(tag))
File “/usr/lib/python3.6/site-packages/docker/models/images.py”, line 175, in build
raise BuildError(chunk[‘error’])
docker.errors.BuildError: Please provide a source image with from prior to run
17-10-08 10:48:32 INFO (SyncWorker_0) [hassio.dock.addon] Start build 27e642c6/armhf-addon-ha-bridge:4.5.6p2
17-10-08 10:48:32 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File “/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py”, line 422, in start
resp = yield from self._request_handler(request)
File “/usr/lib/python3.6/site-packages/aiohttp/web.py”, line 306, in _handle
resp = yield from handler(request)
File “/usr/lib/python3.6/site-packages/hassio/api/util.py”, line 31, in wrap_api
answer = await method(api, *args, **kwargs)
File “/usr/lib/python3.6/site-packages/hassio/api/addons.py”, line 176, in install
addon.install(version=version), loop=self.loop)
File “/usr/lib/python3.6/site-packages/hassio/addons/addon.py”, line 467, in install
if not await self.docker.install(version):
File “/usr/lib/python3.6/site-packages/hassio/dock/util.py”, line 18, in wrap_api
return await method(api, *args, **kwargs)
File “/usr/lib/python3.6/concurrent/futures/thread.py”, line 55, in run
result = self.fn(*self.args, **self.kwargs)
File “/usr/lib/python3.6/site-packages/hassio/dock/addon.py”, line 198, in _install
return self._build(tag)
File “/usr/lib/python3.6/site-packages/hassio/dock/addon.py”, line 211, in _build
image = self.docker.images.build(**build_env.get_docker_args(tag))
File “/usr/lib/python3.6/site-packages/docker/models/images.py”, line 175, in build
raise BuildError(chunk[‘error’])
docker.errors.BuildError: Please provide a source image with from prior to run

**Comment by pvizeli** [comment]
They addon is not compatible with new build system: https://home-assistant.io/developers/hassio/addon_config/#add-on-extended-build
