### ISSUE TITLE
Mi Flora broken due to missing gatttool

### ISSUE THREAD

**Issue by sharukins** [home-assistant/hassio#211]
Home-assistant 0.55
Host OS 1.1
supervisor 0.69
Hass.io image for raspberry pi 3

polling of Mi flora devices fails due to missing gatttool:
```
/bin/sh: gatttool: not found
2017-10-08 21:34:57 INFO (SyncWorker_6) [homeassistant.components.sensor.miflora] Polling error [Errno Could not read data from Mi Flora sensor %s] C4:7C:8D:63:7E:6D
```

**Comment by sharukins** [comment]
the bluez-deprecated package does not contain gatttool (or doesn't copy it to /usr/bin

I just stated a pull request to resolve this:
[https://github.com/alpinelinux/aports/pull/2504](https://github.com/alpinelinux/aports/pull/2504)

**Comment by sharukins** [comment]
this might solve the issue: [https://github.com/alpinelinux/aports/pull/2504](https://github.com/alpinelinux/aports/pull/2504)

**Comment by sharukins** [comment]
okay, so gatttool is not being installed by default on compilation of bluez but is located in attrib/gatttool after compilation

**Comment by pvizeli** [comment]
I was not able to install a runable gatttool on alpine linux. But if you able to do this, please help us and add it to our home-assistant docker.

**Comment by sharukins** [comment]
I will investigate this further, but it would be more future proof to stop using gatttool in the first hand because it's deprecated since at least three years.
I might open a feature request for the mi flora component to be rewritten using some other tool (e.g. bluepy)

I thought about just copying the gatttool binary from raspbian to /usr/bin/ but that would be a crude hack and not applicable for the base-image.

Do you by any chance have knowledge about the alpine packaging system?
I would need a way to copy a file from the source directory instead of the one where 'make install' puts its stuff.

**Comment by pvizeli** [comment]
That will not work while raspbian use glibc and alpine use musl as c library. So you need recompile the source and link it with musl.

Our dockerfiles are here:
https://github.com/home-assistant/hassio-build/tree/master/homeassistant

**Comment by sharukins** [comment]
sorry, I have absolutely no idea of docker
but I found a way to copy the binary from the source directory to /usr/bin on installation of the bluez-deprecated package. Hope [this](https://github.com/alpinelinux/aports/pull/2512) gets merged.

**Comment by sharukins** [comment]
my commit for bluez-deprecated has been merged. The next version of Alpine will include gatttool. Do we need a temporary solution until then? I suppose the next version is due to in December.

**Comment by pvizeli** [comment]
Maybe it is static compiled. So we can download that packages and extract the gattool into bin?

**Comment by sharukins** [comment]
I'm checking with the bluez maintainer of alpine if this patch is viable for a backport which would save us the additional work.

**Comment by pvizeli** [comment]
We can fetch the edge package and extract this bin file. Or yes the maintainer update the 3.6 package

**Comment by sharukins** [comment]
I don't have high hopes that this will be included to 3.6, as backports for Alpine are almost exclusively for security patches.
We could also install bluez from edge, but it's problaby safer to just use the binary from the edge file.
I can include this into a docker file tomorrow but I'm not sure which one is appropriate.

**Comment by pvizeli** [comment]
Yes at it to the end of base and make a notice that it it solve in alpine:3.7

**Comment by pvizeli** [comment]
I had remove it. It have not work while it was not static compiled. He need library that was not included.

**Comment by pvizeli** [comment]
I see two changes:
1) We compile it inside dockerbuild with correct version
2) We add libreadline.so.7 to image

For tests:
```bash
docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock homeassistant/armhf-builder --homeassistant-base --armhf --docker-hub homeassistant -r https://github.com/home-assistant/hassio-build -b master -t homeassistant/base --test --local-docker
```

So you can build it (It use cache, so it is fast...) And he do not push it `--test` and you can run it with:
```
docker run --rm -ti homeassistant/armhf-homeassistant-base:VERSION bash
```

**Comment by sharukins** [comment]
I will try a local compilation first

**Comment by sharukins** [comment]
```
root@hassio:~# docker run --rm -ti homeassistant/armhf-homeassistant-base:20171021 bash
starting version 3.2.2
bash-4.3# gatttool 
Usage:
  gatttool [OPTION*]

Help Options:
  -h, --help                                Show help options
  --help-all                                Show all help options
  --help-gatt                               Show all GATT commands
  --help-params                             Show all Primary Services/Characteristics arguments
  --help-char-read-write                    Show all Characteristics Value/Descriptor Read/Write arguments

Application Options:
  -i, --adapter=hciX                        Specify local adapter interface
  -b, --device=MAC                          Specify remote Bluetooth address
  -t, --addr-type=[public | random]         Set LE address type. Default: public
  -m, --mtu=MTU                             Specify the MTU size
  -p, --psm=PSM                             Specify the PSM for GATT/ATT over BR/EDR
  -l, --sec-level=[low | medium | high]     Set security level. Default: low
  -I, --interactive                         Use interactive mode


bash-4.3# gatttool -I
[                 ][LE]> 
[                 ][LE]> exit
bash-4.3# exit
exit

```
got it running, I just need to figure out which packages I can remove again afterwards

**Comment by sharukins** [comment]
`root@hassio:~# docker run --rm -ti homeassistant/armhf-homeassistant-base:20171021 bash
starting version 3.2.2
bash-4.3# gatttool --device=C4:7C:8D:63:62:72 --char-read -a 0x03
socket(SEQPACKET, L2CAP): Address family not supported by protocol (97)
`
I'm actually not sure if this doesn't work or if the command I type is wrong...

**Comment by sharukins** [comment]
sorry, for the spam.
Can I install addons via console?
I think at the moment gatttool doesn't work because I need to install the bluetooth addon for RPi 3 first

**Comment by pvizeli** [comment]
Yes: https://github.com/home-assistant/hassio/blob/dev/API.md#restful-for-api-addons

**Comment by sharukins** [comment]
Sorry, but I absolutely don't get how this is supposed to work. This is way beyond my scope and skill.

**Comment by pvizeli** [comment]
You can install it over the UI?

**Comment by sharukins** [comment]
when I test using 
`docker run --rm -ti homeassistant/armhf-homeassistant-base:VERSION bash`
I'm obviously dropped to a shell.
I can call gatttool from there but it throws and error:
`gatttool --device=C4:7C:8D:63:40:A7 --char-read -a 0x03
socket(SEQPACKET, L2CAP): Address family not supported by protocol (97)`
which I assume means that there is a problem with bluetooth.

**Comment by pvizeli** [comment]
oh sorry. use `--privileged` and `--network host`

**Comment by sharukins** [comment]
`root@hassio:~# docker run --rm -ti --privileged --network host homeassistant/armhf-homeassistant-base:20171021 bash`
`bash-4.3# gatttool --device=C4:7C:8D:63:7E:53 --char-read -a 0x03`
`Characteristic value/descriptor: 46 6c 6f 77 65 72 20 63 61 72 65`
works

**Comment by pvizeli** [comment]
nice

**Comment by sharukins** [comment]
what an odysee.. sorry that I needed so much help.
I created a pull request, hope that it's acceptable.

**Comment by pvizeli** [comment]
Yeah look great. I add a small comment but we should it merge

**Comment by sharukins** [comment]
👍

**Comment by dasmaeh** [comment]
Looks like this is an issue again with homeassistant 0.60 / hassio 0.79 / Bluetooth BCM43xx Addon 0.7

`/bin/sh: gatttool: not found
2018-01-07 10:37:52 DEBUG (SyncWorker_17) [homeassistant.components.sensor.miflora] Flower 1 (test) Battery = 0
`

**Comment by sharukins** [comment]
The fix has been removed due to Alpine Linux 3.7 being released. Missing package bluez-deprecated has been [added.](https://github.com/home-assistant/hassio-build/commit/d76b24bacd68278f28cd2465167f20098fd1f58b) Therefore MiFlora should be back up and running with the next version.

**Comment by pvizeli** [comment]
I have the gatttool inside image of 0.60.1

**Comment by sharukins** [comment]
confirmed, MiFlora works
