### ISSUE TITLE
can't access webpage

### ISSUE THREAD

**Issue by SaminKainat** [home-assistant/hassio#224]
i have changed the wifi settings of my hassio img file for raspberri pi 2 as follows

[connection]
id=resin-wifi
type=wifi

[wifi]
hidden=true
mode=infrastructure
ssid=**************

[wifi-security]
auth-alg=WPA -Personal
key-mgmt=wpa-psk
psk=*********

[ipv4]
address1=*******
dns=***********;******;
dns-search=
method=manual

[ipv6]
addr-gen-mode=stable-privacy
method=auto

but still can't access the website.
what could be the reason of this?

**Comment by endor-force** [comment]
Are you trying to access it via ip address, i.e http://xxx.xxx.xxx.xxx:8123 or http://hassio.local:8123?

Personally i am using the ip to connect since the hassio.local is not working in my network..

**Comment by SaminKainat** [comment]
i have resolved this issue. thanks for your reply.

Nowadays, i am stuck in another issue. the switch in home assistant is not retaining its state.
it moves back to off state ever time i turn it on/off. 
Everything else is working fine i.e. publishing and subscribing is successfully done.
This is my configuration file.

switch:
  - platform: mqtt
    name: "office Switch"
    state_topic: "home/office/switch1"
    command_topic: "home/office/switch1/set"
    availability_topic: "home/office/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true

**Comment by pvizeli** [comment]
Please open a PR in home-assistant repository but I think you device don't update the state on mqtt und you should use `optimistic: true`
