### ISSUE TITLE
error msg displayed on Snapshots page

### ISSUE THREAD

**Issue by ferdydek** [home-assistant/hassio#226]
Home-assistant 0.55.2
Host OS 1.1
supervisor 0.72
Hass.io image for raspberry pi 3
--------------------------------------

when accessing `https://<IP>:<PORT>/hassio/snapshot` part of error is thrown out in unexpected way.

![image](https://user-images.githubusercontent.com/5775168/31732820-afdd4464-b431-11e7-9c9f-3201cb0f325a.png)

I didn't notice any issues with creating or listing the snapshots.

**Comment by mellowmerlin** [comment]
Still present in 0.56.2. Unable to restore snapshots

**Comment by cstuder** [comment]
Still present in Home Assistant 0.57.2 (Supervisor 0.74). Multiple browsers. 

A quick test showed no problem creating, listing and restoring snapshots.

**Comment by pvizeli** [comment]
Yeah I cant fix that. Please open a issue on polymer repository for home-assistant, the UI developers are not present in this repository :)
