### ISSUE TITLE
HUSBZB-1 doesn’t appear in installed NUC image

### ISSUE THREAD

**Issue by marthoc** [home-assistant/hassio#227]
Using the HASSIO 1.1 NUC image on a Chromebox M004U (an unsupported configuration, I realize). Everything works perfectly, except I can’t get the system to recognize the HUSBZB-1 stick and create /dev/tty entries. The same stick is recognized on both CentOS and Debian installs on the same box and tty entries are created on those oses. 

Output of lsusb:

```
core-ssh:/lib# lsusb
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 003: ID 10c4:8a2a
Bus 002 Device 001: ID 1d6b:0003
Bus 001 Device 002: ID 13d3:3393
```
Relevant output of dmesg:
```
[    1.845747] usb 1-5: new full-speed USB device number 3 using xhci_hcd
```
Output of hassio host hardware:
```
{
  "serial": [],
  "input": [
    "HDA Intel PCH Headphone",
    "HDA Intel HDMI HDMI/DP,pcm=8",
    "HDA Intel PCH Mic",
    "Power Button",
    "HDA Intel HDMI HDMI/DP,pcm=7",
    "Video Bus",
    "HDA Intel HDMI HDMI/DP,pcm=3"
  ],
  "disk": [
    "/dev/sda3",
    "/dev/sda1",
    "/dev/sda4",
    "/dev/sda2",
    "/dev/sda",
    "/dev/sda5",
    "/dev/sda6"
  ],
  "audio": {
    "0": {
      "name": "HDA-Intel - HDA Intel HDMI",
      "type": "HDMI",
      "devices": {
        "3": "digital audio playback",
        "7": "digital audio playback",
        "8": "digital audio playback"
      }
    },
    "1": {
      "name": "HDA-Intel - HDA Intel PCH",
      "type": "PCH",
      "devices": {
        "0": "digital audio capture"
      }
    }
  }
}
```

Any ideas or suggestions? Thanks!

**Comment by tboyce021** [comment]
I'm having the same issue. No suggestions on this?

**Comment by pvizeli** [comment]
This not work?
https://home-assistant.io/hassio/zwave/

**Comment by tboyce021** [comment]
Nope. No device ever shows up in /dev for it. I had it working with the regular Docker image before switching to Hass.io. So I at least know it's not a hardware issue.

**Comment by marthoc** [comment]
My experience is the same as @tboyce021. Stick works fine on a regular install with Docker, but not with hassio.

**Comment by sumitrajancse** [comment]
You are talking about GoControl Linear HUSBZB-1.  It works perfectly with hass.io. 
Please use the CLI > hassio host hardware.
For My setup it shows like this 
`core-ssh:~# hassio host hardware
{
  "serial": [
    "/dev/ttyUSB0",
    "/dev/ttyUSB1"
  ],
  "input": [],
  "disk": [],
  "gpio": [
    "gpiochip100",
    "gpiochip0"
  ],
  "audio": {
    "0": {
      "name": "bcm2835 - bcm2835 ALSA",
      "type": "ALSA",
      "devices": {
        "0": "digital audio playback",
        "1": "digital audio playback"
      }
    },
    "1": {
      "name": "USB-Audio - AK5371",
      "type": "AK5371",
      "devices": {
        "0": "digital audio capture"
      }
    }
  }
}
`

Please try to change the USB port and then reboot your rpi . It should work

**Comment by tboyce021** [comment]
@sumitrajancse, this isn't on an rpi, it's on the Intel NUC. It's not listed in the host hardware.

**Comment by tboyce021** [comment]
FYI, my host hardware looks identical to the one in the OP here. There's nothing listed under "serial". I can also see the output in dmesg when I plug it in, but I can't get it to show up in the list of devices and HA can't access it if I put the relevant entries in the config anyway.

**Comment by tboyce021** [comment]
I tried using the `curl` command to add the mappings myself:
```
curl -d '{"devices": ["ttyUSB0", "ttyUSB1"]}' http://hassio/homeassistant/options
```
I get an "ok" response:
```
{"result": "ok", "data": {}}
```
But I still haven't managed to get it working after doing that. What's exactly is that supposed to do? I still don't see anything listed under "serial" devices and HA can't reach it. Is it supposed to show up immediately if it works? Do I need to restart first? Does it actually persist after a restart?

**Comment by tboyce021** [comment]
Any other suggestions on this? I still can't get it working with the latest updates. I see a ton of stuff in `serial` now, but I don't think any of them are the USB stick:

```
core-ssh:~# hassio host hardware
{
    "result": "ok",
    "data": {
        "serial": [
            "/dev/ttyS29",
            "/dev/ttyS15",
            "/dev/ttyS18",
            "/dev/ttyS23",
            "/dev/ttyS24",
            "/dev/ttyS5",
            "/dev/ttyS4",
            "/dev/ttyS16",
            "/dev/ttyS3",
            "/dev/ttyS28",
            "/dev/ttyS26",
            "/dev/ttyS25",
            "/dev/ttyS12",
            "/dev/ttyS20",
            "/dev/ttyS2",
            "/dev/ttyS21",
            "/dev/ttyS8",
            "/dev/ttyS14",
            "/dev/ttyS17",
            "/dev/ttyS22",
            "/dev/ttyS19",
            "/dev/ttyS7",
            "/dev/ttyS31",
            "/dev/ttyS6",
            "/dev/ttyS9",
            "/dev/ttyS0",
            "/dev/ttyS11",
            "/dev/ttyS30",
            "/dev/ttyS13",
            "/dev/ttyS27",
            "/dev/ttyS1",
            "/dev/ttyS10"
        ],
        "input": [
            "HDA Intel HDMI HDMI/DP,pcm=7",
            "HDA Intel HDMI HDMI/DP,pcm=3",
            "HDA Intel PCH Mic",
            "Power Button",
            "HDA Intel PCH Headphone",
            "HDA Intel HDMI HDMI/DP,pcm=8",
            "Video Bus"
        ],
        "disk": [
            "/dev/sda3",
            "/dev/sda1",
            "/dev/sda4",
            "/dev/sda6",
            "/dev/sda2",
            "/dev/sda5",
            "/dev/sda"
        ],
        "gpio": [],
        "audio": {
            "0": {
                "name": "HDA-Intel - HDA Intel HDMI",
                "type": "HDMI",
                "devices": {
                    "3": "digital audio playback",
                    "7": "digital audio playback",
                    "8": "digital audio playback"
                }
            },
            "1": {
                "name": "HDA-Intel - HDA Intel PCH",
                "type": "PCH",
                "devices": {
                    "0": "digital audio capture"
                }
            }
        }
    }
}
```

**Comment by tboyce021** [comment]
@pvizeli is it possible to get access to the host on the NUC? I tried adding an {{authorized_keys}} to the flash-boot partition of the USB drive and flashing again, but it doesn't seem to work. It still denies my SSH key.

**Comment by scfigg** [comment]
ugh same issue here. Just switched over from my RPi3 to Intel NUC, was amazed by how fast it was, only to find out I can't use anything in my house because it can't find the USB. Need this fixed!

**Comment by marthoc** [comment]
After further testing I think this could be a ResinOS issue on the NUC/x64 platform. Unfortunately this probably isn’t going to get fixed since I think Hass.io is moving away from ResinOS and onto a customized Linux build (HassioOS?) in the coming months. 

What you could do is install Debian on your NUC, install Docker, then run the Hassio installer. It will set up the Hassio environment for you just as if you were using the image, except you’d be on top of Debian and not ResinOS. When I do this, my HUSBZB-1 shows up inside the Hassio container ecosystem (it shows up under `hassio host hardware` with tty entries).

**Comment by scfigg** [comment]
Thanks for the update. I'll have to play with it I guess - I've never had luck with docker, and I hate Linux. Time to start breaking things I guess!

**Comment by scfigg** [comment]
Stupid question - but on my NUC, I installed Ubuntu server, then followed this guide:

https://www.youtube.com/watch?v=EMOLDrL6_7Q&index=1&list=PLOkeE2vyZtuKOKkK1RvCwnkHEbA1_r3jy&t=303s

Isn't that technically installing it into docker on top of Ubuntu?

**Comment by marthoc** [comment]
Sorry I’m not sure if I’m following why it’s a stupid question. That video shows you exactly how to do what I’m suggesting - which is to install Hass.io on top of a regular Linux distro rather than using the premade image for Intel NUC distributes by the Hass.io project. Yes, Docker is required because at its core Hass.io is a set of Docker containers (one for Home Assistant, and one for the Hass.io supervisor that handles all Hass.io functions, including updating Home Assistant and running Addons).

**Comment by scfigg** [comment]
Ok thanks. I did that yesterday, and 'hassio host hardware' doesn't show any USB devices plugged in when using the HUSBZB-1 stick. Just a bunch of serial connections like tboyce said above.

**Comment by marthoc** [comment]
Interesting - so that points to Hass.io as the culprit then. Can you do a couple of things for me to help troubleshoot? SSH into Ubuntu (not into the Hass.io addon) and do:
```
ls -l /dev | grep ttyUSB*
```
With your HUSBZB-1 attached, that command should return two entries - ttyUSB0 and ttyUSB1. 

Also out of interest, what command did you run to install Hass.io? Was it:
```
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s
```
Or did you specify the Intel NUC machine type with:
```
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m intel-nuc
```
?

**Comment by scfigg** [comment]
I can test it later tonight for you - at work now, and I switched back to the RPi3 since I couldn't get NUC to work.

I did the first command:
`curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s`

**Comment by marthoc** [comment]
OK also interesting. Can you add to the list of things to try and report the output of:
```
docker ps
```
when SSH’d into Ubuntu. Just paste the whole result. Thanks!

**Comment by scfigg** [comment]
Any suggestions on how to SSH into the host since port 22 SSH server is already running on HassIO?

**Comment by scfigg** [comment]
Nevermind - got SSH server installed on Ubuntu. I may have been completely stupid - I have a couple NUCs laying around, and during various testing, I may have swapped them on accident. I verified the Ubuntu HassIO install was running today, then typed the "ls -l /dev | grep ttyUSB*" and it showed the USB ports once I did a show hardware command. Not sure what that command you gave me does (does it add it, or just list he USB ports?). Anyways, I got it working now. Thanks for your help!

Now I'm trying to figure out why my docker.io install is out of date somehow, so I can't install certain addons. Followed the instructions in the video, so maybe that repo sucks. Not sure how to upgrade it now.

**Comment by marthoc** [comment]
That command just lists (`ls`) the contents of the /dev directory and pipes ( | ) the output into `grep` to filter just for the ttyUSB entries.  It wouldn’t have made anything work that wasn’t working already. 

So the culprit may actually be ResinOS then!

To fix your Docker problem you’re going to need to install a newer version of Docker. That video had to install Docker.io from the Ubuntu repository but that version is probably significantly out of date by now. This page: https://docs.docker.com/install/linux/docker-ce/ubuntu/  has detailed instructions starting with removing your old version (this will/should preserve your Hass.io install). Follow the “Uninstall old versions” section and then skip down to “Install using the repository”. From there it’s pretty much copy and paste!

**Comment by scfigg** [comment]
Thanks - I forgot to update this again last night. Managed to figure out how to uninstall docker.io and install Docker-CE, and it kept my docker image/container just fine. Works great now! Thanks for your help. Looks like it was Resin-OS.

**Comment by 3lvl0** [comment]
Man this sucks. I got a NUC thinking I could flash Hass.io and it would work like it did on my RP3. As a noob I don't think I am up to the task of installing a linux distro with docker and hass.io inside of it. I doubt there is a guide good enough for that. Looks like I'm stuck waiting for Hassio OS whenever that will be released. Does anyone even know that the GoControl with work on NUCs with Hassio OS? Back to the Pi for now..

**Comment by THland83** [comment]
Just to give this a bit more life. 


HUSBZB-1:
This path works for me using the 

zwave:
  usb_path: /dev/ttyACM0

node name
Sigma Designs UZB Z-Wave USB Adapter
manufacturer name
Sigma Designs
product name
UZB Z-Wave USB Adapter
query stage
Complete
is awake
true
is ready
true
is failed
false
is info received
false
max baud rate
40000
is zwave plus
false
