### ISSUE TITLE
FIDO 2 Factor Login

### ISSUE THREAD

**Issue by pflegezentrum** [home-assistant/hassio#228]
Hi there,

 Will it be possible to use FIDO as two factor authentication? Or universal authentication technology?
Would be great since Google , Microsoft, Facebook, .... Many more go for it.

I found this in the net: https://github.com/Yubico/python-u2flib-server

BR 
Barms

**Comment by ferdydek** [comment]
Just to make it clear - you are thinking about authentication to access what exatly? HA? hassio? SSH? API?
As for now HA is not meant as user based system, it centers around whatsoever you implement a Home as, so im just not sure which direction were you thinking this should take.

**Comment by pflegezentrum** [comment]
Hi ferdydek,

Since login to the dashboard and configuration can be done by a webfrontend from extern and inside of my network, I asked if 2 Factor authentication will be part of HA login/authentication backend (wherever this is ...)... And since more thant one person mostly lives in a Home and wnat to have access. to HA e.g. by an mobile app... 2 factor?

When I'm wrong here with this feature proposal please tell...  and/or give me a hint?

BR
Barns

**Comment by frenck** [comment]
@pflegezentrum This is not part of Hass.io (which is this repository). The authentication is part of Home Assistant. You can find the repository here:

https://github.com/home-assistant/home-assistant

Thank you.
