### ISSUE TITLE
Loop energy doesn't work in hassio

### ISSUE THREAD

**Issue by pavoni** [home-assistant/hassio#229]
Versions:-
HA 0.55.2 
Current latest live hassio (but previous versions have has the same issue)

Components:-
loop_energy / hassio

**Description of problem:**
Looks like the loop_energy websocket can't call back to the app when running under hassio - assume there is a port that needs to be opened.

I'm the maintainer of loop_energy - so very happy to make some changes / do some digging - but not familiar with hassio / docker - so will need some help / advice.

**Expected:**
loopenergy should work the way it does on a native build.

**Comment by pvizeli** [comment]
The Home-Assistant docker run under host network -> Allow to use all ports without FW behind. It run also in full privileged modus -> Have any access to host hardware.

Home-Assistant is the only container they work like it is local installed without docker. Add-ons and all other have not the same rights while it's not under our control.

The only problem they you can have inside hass docker is, that the python module is not installed or while we have all official module installed, that he have problem with a other module/version.

**Comment by pavoni** [comment]
Thanks for the help.

Here is my component https://github.com/pavoni/pyloopenergy
And this uses an socket.io protocol 0.9 (it was changed to an incompatible version).
(Sadly the loop energy server seems to use 0.9)
https://pypi.python.org/pypi/socketIO-client/0.5.6

Will turn up the logging and see if I can see any issues...

**Comment by pavoni** [comment]
Here is the log in hassio with
```
logger:
  default: error
  logs:
    homeassistant.components.device_tracker: critical
    pyloopenergy.loop_energy: debug
    homeassistant.components.pyloopenergy: debug
```
Not sure if the aiohttp errors are related

The logs indicate the pyloopenergy never connected

```
2017-10-22 19:48:53 INFO (LoopEnergy Event Thread) [pyloopenergy.loop_energy] Started LoopEnergy thread
2017-10-22 19:48:53 INFO (LoopEnergy Event Thread) [pyloopenergy.loop_energy] Opening socket connection
2017-10-22 19:49:59 ERROR (MainThread) [aiohttp.access] Error in logging
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 500, in log
    for key, value in fmt_info:
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 483, in <genexpr>
    return ((key, method(args)) for key, method in self._methods)
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 436, in _format_a
    peername = args[3].get_extra_info('peername')
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 547, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
2017-10-22 19:50:19 ERROR (MainThread) [aiohttp.access] Error in logging
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 500, in log
    for key, value in fmt_info:
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 483, in <genexpr>
    return ((key, method(args)) for key, method in self._methods)
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 436, in _format_a
    peername = args[3].get_extra_info('peername')
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 547, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
```

I can pull a log from my mac install...

**Comment by pvizeli** [comment]
The errro `return self._transport.get_extra_info(name, default)` is not realated to your problem that is a problem with aiohttp and uvloop and should be solve with 2.3.1 but anyway this error is happens for every home-assistant user with uvloop settings.

Your problem is, that is not a official component (not supported to us) and that will not work. You need make a official component if you want use it with hass.io or you need use the same module version they we have installed.

**Comment by pvizeli** [comment]
Sorry, I had click on wrong button :)

**Comment by pavoni** [comment]
Is there a way to run a Python REPL in the hassio environment?
Or run a locally patched version of a library?

**Comment by pavoni** [comment]
I also changed my HA (on hassio) to use SSL - would this make any difference? 

Guess this is pretty easy to test.

**Comment by pvizeli** [comment]
I'm not sure, maybe you can install a library into dept folder and Hass will use this. But the more importend point is, that `loop_energy` is broken inside home-assistant and we should fix that. A component should work if we use requirements_all.txt to install this.

Maybe you can port this to a other websocket library (best would be async with aiohttp or https://github.com/aaugustin/websockets)?

**Comment by pavoni** [comment]
@pvizeli Thanks for the help.
What makes you think _that loop_energy is broken inside home-assistant?_

It was working fine - and I think it still works (and dependencies are installed normally via`requirements_all.txt`), at least when I install on a mac via the older set_up method.

Will of course double check.
