### ISSUE TITLE
Git pull - Ways to add new feature: "deployment keys"?

### ISSUE THREAD

**Issue by alexbarcelo** [home-assistant/hassio#234]
I was looking at the [GIT pull documentation](https://home-assistant.io/addons/git_pull/), and I see that there is no mechanism to add a private ssh key to use. I think that having a mechanism to provide a ssh key, which will typically be a read-only "deployment key", will be great for this plugin.

To implement that I am not sure how to provide the key. If json files could have multiline, I would add the private key directly in the configuration file. But JSON does not support that. I am not sure which would be a clean way to do that.

I am ready to receive suggestions on how to do that and prepare a PR for that feature, if this mechanism is considered nice-to-have.

**Comment by pvizeli** [comment]
You can look into our ssh add-on, and in this way you can also provide the private key and copy this on start to home.

**Comment by alexbarcelo** [comment]
Oh thanks, missed that. Yes it seems quite close to what I wanted to accomplish :)

I will (hopefully) provide a PR soon!

**Comment by alexbarcelo** [comment]
I proposed a certain workaround for multiline, which is readable but a bit messy. The PR is over there:
home-assistant/hassio-addons#196

I assume that the PR is the best place to further discuss about this. Reopen if I'm mistaken.
