### ISSUE TITLE
Aros AC Problems

### ISSUE THREAD

**Issue by Weldon26** [home-assistant/hassio#236]
A few releases ago, I started having trouble controlling my AC's. I can't change the mode on them anymore and I'm getting these errors. They appear again and again in the error log. In the log snippet below, they're shown to have occurred less than two minutes apart. And they don't stop.

`AttributeError: 'WinkAirConditioner' object has no attribute 'current_hvac_mode'`
`2017-10-28 00:09:34 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step`
`    result = coro.send(None)`
`  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 215, in async_update_ha_state
    state = self.state`
`  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 444, in state
    if self.current_operation:`
`  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/wink.py", line 384, in current_operation`
`    current_op = WINK_STATE_TO_HA.get(self.wink.current_hvac_mode())`
`AttributeError: 'WinkAirConditioner' object has no attribute 'current_hvac_mode'`
`2017-10-28 00:11:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step`
`    result = coro.send(None)`
`  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 215, in async_update_ha_state
    state = self.state`
`  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 444, in state
    if self.current_operation:`
`  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/wink.py", line 384, in current_operation`
`    current_op = WINK_STATE_TO_HA.get(self.wink.current_hvac_mode())`

Or sometimes I get these, instead:
`2017-10-28 01:37:05 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`
`2017-10-28 01:37:05 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`
`2017-10-28 01:37:05 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`
`2017-10-28 01:37:05 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`
`2017-10-28 01:38:35 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`
`2017-10-28 01:38:35 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`
`2017-10-28 01:39:04 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`
`2017-10-28 01:39:04 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`
`2017-10-28 01:40:34 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`
`2017-10-28 01:40:34 ERROR (MainThread) [homeassistant.components.climate.wink] Invaid operation mode mapping. auto_eco doesn't map. Please report this.`

**Comment by pvizeli** [comment]
Please open the PR on home-assistant repository. Thanks for reporting
