### ISSUE TITLE
dlib components not functioning in hassio, missing libraries

### ISSUE THREAD

**Issue by stickystyle** [home-assistant/hassio#239]
Adding any of the dlib components will generate these messages in the logs...

```
2017-11-06 11:05:02 ERROR (SyncWorker_10) [homeassistant.util.package] Unable to install package face_recognition==1.0.0: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zp1cukr2/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ldhmq9da-record/install-record.txt --single-version-externally-managed --prefix  --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-zp1cukr2/scipy/
2017-11-06 11:05:02 ERROR (MainThread) [homeassistant.setup] Not initializing image_processing.dlib_face_detect because could not install dependency face_recognition==1.0.0
2017-11-06 11:05:02 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform image_processing.dlib_face_detect: Could not install all requirements.
```

I tracked it down to dlib needing to compile native components to install, after adding packages needed to install (`apk add build-base gcc cmake python3-dev boost-dev `) I was able to get face_recognition==1.0.0 to install correctly. I understand that these packages would blow up the image size quite a bit, so is it possiable to load pre-compiled versions of the libs into the image without the dev packages?

**Comment by pvizeli** [comment]
Strange, dlib exists inside hassio container: https://github.com/home-assistant/hassio-build/blob/master/homeassistant/base/Dockerfile#L58-L63

**Comment by pvizeli** [comment]
Fix with: https://github.com/home-assistant/hassio-build/commit/70b13b0843a22379087d3bd7f214c496aeee0fda

**Comment by LordVaderXIII** [comment]
Hi Im still having this issue on Hassio 0.61.1

2018-01-23 12:00:08 ERROR (SyncWorker_19) [homeassistant.util.package] Unable to install package face_recognition==1.0.0: Exception:

Is there a planned fix?

**Comment by jadowse** [comment]
worth trying microsoft?  just cant be bothered with azure.....

**Comment by pvizeli** [comment]
It work on my test system.

**Comment by jaburges** [comment]
same issue here 
`Unable to install package face_recognition==1.0.0: Command "/home/jamie/homeassistant/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o6_ooykz/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gfz8mks_-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jamie/homeassistant/include/site/python3.6/dlib" failed with error code 1 in /tmp/pip-build-o6_ooykz/dlib/`

**Comment by jaburges** [comment]
same issue here:
Unable to install package face_recognition==1.0.0: Command "/home/jamie/homeassistant/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o6_ooykz/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gfz8mks_-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jamie/homeassistant/include/site/python3.6/dlib" failed with error code 1 in /tmp/pip-build-o6_ooykz/dlib/

**Comment by Meganoodle71** [comment]
I am still having the same issue, on HASS.IO I assume the steps detailed above were performed on hassbian and not hassio.
Any tips or help would be appreciated.

**Comment by robsonschmidt** [comment]
I'm having the same issue.

**Comment by Ouassimf** [comment]
Same issue

**Comment by Radio-van** [comment]
Same issue

**Comment by Ouassimf** [comment]
I would suggest changing the requirement on face_recognition from 1.0.0 to 1.2.2
1.0.0 use deprecated library from scipy imread which wont be found on a clean install of scipy.
I changed the requirement and it now works.

**Comment by Radio-van** [comment]
@Ouassimf Could you please tell a little bit more how to do it? It's difficult to make persistent changes in Hassio containers.

**Comment by Radio-van** [comment]
I tried to copy dlib component into custom_components folder and replaced requirement from 1.0.0 to 1.2.2, but as soon as face_recognition package still missed from Homeassistant container, initialisation of dlib component fails.

**Comment by aswieton** [comment]
same problem is there any solution?

**Comment by Ouassimf** [comment]
@Radio-van 
I did not move the component to custom. I edited the code directly. 
Also, I m not on hassio but on a standalone rpi. 
Nonetheless I have to say that dlib is slow to run on an RPi3 .

**Comment by Radio-van** [comment]
Oh, I see, thanks. Well, this is not a problem on standalone Pi)

**Comment by Radio-van** [comment]
Well, I found a solution.
Home assistant previously (afaik <0.50 version) stored dependences in a **/deps** folder under config folder. So, we are able to place missing packages here.
What I did:
1. ssh to Hassio (not Home Assistant container, but Resin instance)
2. `docker ps` to get homeassistant **container id**
3. `docker exec -it <ID_here> ash` to get to the container shell
4. `pip3 install face_recognition` to install dependences
5. `cp -r /usr/lib/python3.6/site-packages/face-recognition /config/deps/lib/python3.6/site-packages/` config folder is persistant, so it would survive container restart
6. `ctrl+p ctrl+q` to detach from container
7. ssh to Home Assistant container as usual and restart it

Thats it, **dlib** component now initializes properly.
But I have another error
```
 RuntimeError: Error deserializing object of type int64
   while deserializing a floating point number.
   while deserializing a dlib::matrix
   while deserializing object of type std::vector
   while deserializing object of type std::vector
   while deserializing object of type std::vector
```
but I think it caused by something else.

**Comment by jmtatsch** [comment]
Since 0.88 this is a problem again on hassio. 

```
019-02-24 11:01:30 ERROR (SyncWorker_17) [homeassistant.util.package] Unable to install package face_recognition==1.0.0: Failed building wheel for scipy
  Failed cleaning build dir for scipy
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-fl75n201/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5tc96_n1/install-record.txt --single-version-externally-managed --prefix  --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-fl75n201/scipy/
You are using pip version 19.0.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2019-02-24 11:01:30 ERROR (MainThread) [homeassistant.requirements] Not initializing dlib_face_identify.image_processing because could not install requirement face_recognition==1.0.0
2019-02-24 11:01:30 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform dlib_face_identify.image_processing: Could not install all requirements.
2019-02-24 11:01:36 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package face_recognition==1.0.0: Failed building wheel for scipy
  Failed cleaning build dir for scipy
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kq9_oinj/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-k0v0x1am/install-record.txt --single-version-externally-managed --prefix  --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-kq9_oinj/scipy/
You are using pip version 19.0.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2019-02-24 11:01:36 ERROR (MainThread) [homeassistant.requirements] Not initializing dlib_face_detect.image_processing because could not install requirement face_recognition==1.0.0
```

**Comment by vandalon** [comment]
This issues seems to be still there in 0.91:

Unable to prepare setup for platform dlib_face_detect.image_processing: Could not install all requirements
