### ISSUE TITLE
Docker Hub repositories have no description

### ISSUE THREAD

**Issue by escalate** [home-assistant/hassio#240]
I would like to run the Home-Assistant Docker images (e.g. https://hub.docker.com/r/homeassistant/armhf-addon-bluetooth_bcm43xx/) on my own without Hass.io.
But all Docker Hub repositories have no description.
At the moment it looks like that the images are only usefull if I run Hass.io on my Raspberry Pi 3.
Is it possible to add a description to all Home-Assistant Docker Hub repositories which explains me how to use the images?

At the moment I have to look in differrent configurations and documentations to figure out how python starts the docker container.

e.g.
https://github.com/home-assistant/hassio/blob/dev/hassio/dock/addon.py#L190-L205
https://home-assistant.io/developers/hassio/addon_config/#add-on-config
https://github.com/home-assistant/hassio-addons/blob/master/bluetooth_bcm43xx/config.json

**Comment by pvizeli** [comment]
You can only use this add-ons with hass.io. You can easy use hass.io on a raspbian without need the hardware image. Look into generic installation description.

**Comment by escalate** [comment]
Thank you for your response. The generic installation description (https://home-assistant.io/hassio/installation/) says that "When you use this installation method, some add-ons will not be available and the documentation might not work for your installation.". So it looks like the Hass.io hardware image does something more. Do you know more about the differences and pitfalls?

**Comment by bliemli** [comment]
@escalate I'm using the raspberrypi2 image without issues. There's also an image for raspberrypi3: https://hub.docker.com/r/homeassistant/raspberrypi3-homeassistant/.
Use it as if you'd use the image from https://hub.docker.com/r/homeassistant/home-assistant/, you don't need hassio for that.

However, builds are not automated which is kind of ironic and as you already noted documentation is sparse.

**Comment by frenck** [comment]
The answer provided by @pvizeli is sufficient in this case.
Dockerhub is used as a distribution method. Images provided are for use with Hass.io and not meant to be used manually.

Closing this issue for now.
