### ISSUE TITLE
rpi_gpio_pwm not working as Daemon needs to be started

### ISSUE THREAD

**Issue by thesplitter** [home-assistant/hassio#242]
I have tried configuring rpi_gpio_pwm but as it needs the Daemon to be running it can't work without some user tweaks.
Wouldn't it be better and more user friendly if on hassio the Daemon is started when rpi_gpio_pwm is found in the config?

**Comment by pvizeli** [comment]
You can provide a add-on they run the daemon. So if a user will run pwm he can install the add-on and start it. You can make a PR to core add-ons.

**Comment by Poeschl** [comment]
Any progress on this? 
I'm also not able to even start the daemon manually.
