### ISSUE TITLE
Possibility to install on and boot from external USB media on Raspberry Pi 3

### ISSUE THREAD

**Issue by cstuder** [home-assistant/hassio#246]
I would love to be able to install Hass.io on an external USB drive and boot without an SD card.

Raspberry Pi 3 [can boot from (some) USB mass storage devices](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md). (Only model 3 can boot without SD cards.)

Support for USB booting in Resin OS is [being discussed on their tracker](https://github.com/resin-os/resinos/issues/396).

Some folks are reporting [success on the HA forums.](https://community.home-assistant.io/t/usb-boot-on-raspberry-pi-3/20358/37?u=johan71)

The process is unfortunately somewhat involved (You need to boot at least once from an SD card to set the appropriate configuration on the Rasperry Pi 3) and could maybe made easier by offering a special Hass.Io-build which has the USB boot parameters already set and with a different partition scheme.

**Comment by aronsjoberg** [comment]
Please implement this! I love being able to run Hassbian from USB (after enabling USB boot on the RPi3). It's one of the few things I now miss with Hass.io but it's a important feature.

**Comment by arsaboo** [comment]
Please post feature requests in the forums and close this thread. Issues is only for tracking bugs.

**Comment by cstuder** [comment]
Issue closed as requested.

Feature request in the forum here: https://community.home-assistant.io/t/feature-request-possibility-to-install-hass-io-on-and-boot-from-external-usb-media-on-raspberry-pi-3/35514
