### ISSUE TITLE
Samba doesn't start

### ISSUE THREAD

**Issue by ziotibia81** [home-assistant/hassio#248]
After recents updates, Samba server doesn't start anymore and dont' log nothing.
Platform qemux86-64

**Comment by endor-force** [comment]
Try to load the ssh plugin.

After trying the installation of the samba add-on, use the command `hassio homeassistant logs` and `hassio supervisor logs` to see if it gives you more info.

**Comment by ziotibia81** [comment]
After one of last updates samba restart to work.

**Comment by frenck** [comment]
Since the OP reported it working again, I'm closing this issue.
