### ISSUE TITLE
Improve Addon Communication docs

### ISSUE THREAD

**Issue by mgolisch** [home-assistant/hassio#252]
From reading https://home-assistant.io/developers/hassio/addon_communication/ its not realy obvious how to construct the names used to communicate with an addon.
After fidling around quite some time i realized the repository slug/id for the builtin addons is core and by inspecting the sourcecode i found that uses some hash for custom repositories.
Later on i saw that the hassio supervisor info command shows that information
But it would have been so much easier if the docs told me that.

Also maybe this information could be shown on the Addon Info screen in the hassio ui in homeassistant?
That would make communicating with foreign/external addons much easier especialy from user standpoint.

**Comment by frenck** [comment]
@mgolisch Thank you for this suggestion. I like the idea of having this available in the dialogs.
PS: You do not need to inspect the source code since it is in the URL as well ;)
