### ISSUE TITLE
hassio homeassistant check should return exit code 1 if invalid

### ISSUE THREAD

**Issue by SteveEdson** [home-assistant/hassio#253]
I thought that #156 might have covered this but it doesn't look like it does.

I think that `hassio homeassistant check` should return a error exit code if the config is invalid. This will allow simple things such as 

```git pull && hassio homeassistant check && hassio homeassistant restart```

Thanks.

**Comment by pvizeli** [comment]
@ryanm101 that is fix with new CLI?

**Comment by SteveEdson** [comment]
Yeah thanks!
