### ISSUE TITLE
automation config page broken

### ISSUE THREAD

**Issue by dragouf** [home-assistant/hassio#259]
since version 0.58.1 when I try to create a new automation the UI is unresponsive and I have in the brower console : 

```
TypeError: this._updateComponent is not a function
```

**Comment by lptutor** [comment]
Same issue here... It seems the page is broken too. When creating new Automation you cannot add action or condition and the save button is hiding at the bottom of the page and cannot be clicked. Although editing existing Automation seems working.

**Comment by pvizeli** [comment]
Please reopen this issue on Home-Assistant repository. Here is only hass.io they make home-assistant available but do not run it or modify it. Thanks for reporting

**Comment by jpenyc** [comment]
Just ran into this issue on a new install. has me dead in the water . . .
