### ISSUE TITLE
RPi3 not connecting to WiFi

### ISSUE THREAD

**Issue by Cnordbo** [home-assistant/hassio#273]
Moved from https://github.com/home-assistant/home-assistant/issues/11066

**Home Assistant release (`hass --version`):**
resinos-hassio-1-1-raspberrypi3 (latest from website per 10.12.2017)

**Component/platform:**
Raspberry Pi 3

**Description of problem:**
Not connecting to wifi

**Expected:**
Connection to wifi

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml

```

1. Follow the guide on [Hassio installation](https://home-assistant.io/hassio/installation/)
2. Edit resin-sample in `system connections` with your own SSID and password

**Additional info:**

resin-sample file: 
```
[connection]
id=resin-sample
type=wifi

[wifi]
hidden=false
mode=infrastructure
ssid=My2GNetwork

[wifi-security]
auth-alg=open
key-mgmt=wpa-psk
psk=1234@4321

[ipv4]
method=auto

[ipv6]
addr-gen-mode=stable-privacy
method=auto
```

I downloaded the Hassbian image right after, and everything works from there. So there is no issues with the device or its connectivity in general.

**Comment by frenck** [comment]
This issue is reported against ResinOS. Since we moved away from ResinOS and replaced it with HassOS, this issue doesn't apply anymore (and is certainly not going to be fixed).

Closing this issue because of that.
