### ISSUE TITLE
hass.io resin build with -v or --dev

### ISSUE THREAD

**Issue by mbrownnycnyc** [home-assistant/hassio#281]
Hello all,

I had mentioned in #general on discord that I wish to share `/dev/snd` between multiple docker containers.  If I run the [bestlibre mopidy add-in](https://github.com/bestlibre/hassio-addons/tree/master/mopidy), I can't produce sound from the hass.io container since the mopidy container locks /dev/snd.

One option is to use `--ipc=host` and start all containers with that.  Then again, you could instead isolate the shared IPCs to just /dev/snd with `-v /dev/snd`.  I've seen both recommended as options.

Thanks,

Matt

**Comment by pvizeli** [comment]
Supported by 0.76

**Comment by mbrownnycnyc** [comment]
awesome thanks!
