### ISSUE TITLE
Multicast making it through?

### ISSUE THREAD

**Issue by jevy** [home-assistant/hassio#291]
I'm having the issue where xiaomi-aqara is discovered but can't be initialized properly. I'm pretty sure I've isolated it to a network issue.

I ran wireshark on the host machine and I can see it the packets making it there:

```
$ sudo  ngrep port 9898 -d enp0s31f6
interface: enp0s31f6 (192.168.1.0/255.255.255.0)
filter: (ip or ip6) and ( port 9898 )
#
U 192.168.1.108:4321 -> 224.0.0.50:9898
  {"cmd":"heartbeat","model":"gateway","sid":"XXXXXXX","short_id":"0","token":"XXXXXXX","data":"{\"ip\":\"192.168.1.108\"}"}
#
```

But I'm not sure if they are making it through to the homeassistant container. Is there a way to verify that? I tried to "docker exec" in to try to install ngrep but of course I can't.

**Comment by pvizeli** [comment]
The homeassistant container have a special level. It is the only container they run on host network and have full privileged on host. That is like he run native on host.

You can install things with docker exec until next restart/update. Maybe you forgetting that we use alpine linux on this image?

Please tell me what you find out and if we can change some things. Thanks

**Comment by jevy** [comment]
Hey @pvizeli! Thanks for getting back. I did a bit of digging.

When I install hass on my Raspberry Pi with the default install, the xiaomi gateway is discovered without any issue. The same install/config on my x86 mini-pc (Ubuntu 16.04) does not properly set up the gateway.

Are either of these set up differently somehow?

**Comment by frenck** [comment]
This is used and tested by many (including myself) and not an issue at this moment.
We also did not receive any more reports of this and since this issue is pretty old, I'm closing it of being stale / not an issue anymore.
