### ISSUE TITLE
Unresponding after last update

### ISSUE THREAD

**Issue by vtxfr** [home-assistant/hassio#302]
Hi,
my hassio is KO since last update ...
Is this the new #watchdog always restarting it on my #raspberrypi ?
PiHole addon is accessible on port 80 but under heavy load : 6.84  3.93  2.88 !
How can I fix that ?
Thanks

**Comment by pvizeli** [comment]
The watchdog can only restart home-assistant. Can you post the supervisor logs?

**Comment by vtxfr** [comment]
As only pi-hole add-on is accessible and the raspberry pi stays under heavy load I think hassio permanently restarts.

How can I access the logs without SMB and SSH ?

**Comment by pvizeli** [comment]
You can access to log over UI. The watchdog only restart every 5 minute. So you should have 4-3 min times to access the log on hass.io panel

**Comment by vtxfr** [comment]
No way to access the UI

**Comment by pvizeli** [comment]
do you try to reboot? How do you edit the config?

**Comment by vtxfr** [comment]
I tried to reboot but no way to access hassio.
I edit config files via SMB but I have no acces anymore since the update.

**Comment by frenck** [comment]
@vtxfr This issue is pretty stale, is this still an issue?

**Comment by frenck** [comment]
Since there was no response, I'm declaring this issue stale and closing it.
Feel free to re-open this issue when you feel like that is the appropriate thing to do.
