### ISSUE TITLE
Potential attributes for supervisor/info - addons part

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/hassio#304]
Operational (probably higher computational cost):

- CPU usage: Probably average over last X minutes in % to allow spotting of resource hungry addons
- Memory used (RAM): Probably average on last X minutes to allow spotting of resource hungry addons

Decoration:
- Time since last upgrade: Useful to spot addons that might have lower activity (if they miss features) or for rock solid addons (that do everything you need)
- Time since installed: Useful to see old addons that you might recommend to other users or friends
- Uptime of container: Spot containers that die frequently or those that are long living with no memory issues to help build confidence

**Comment by c727** [comment]
We should not flood the users with too much info.
All in all I think for dashboard config-error/requries-config and weg-ui-link can be useful

**Comment by ciotlosm** [comment]
@c727 I agree, but having the info there, unlock potential for other UIs (like HADashboard) and maybe sensors and other reporting that users might need. If the info is not resource intensive, it doesn't hurt to be available.
