### ISSUE TITLE
Make watchdog timer configurable

### ISSUE THREAD

**Issue by derjoerg** [home-assistant/hassio#313]
Hi,

since the upgrade to 0.60.1 I have a serious problems in getting HASS up and running.

I'm running hass.io on a raspberry pi zero w and so the startup took some time. Since the upgrade it seems to need more than the planned 10 minutes and so watchdog always restarts HASS creating an endless start loop.

As soon as I disable some of the components and get below the 10 minutes line everything is working.

Is there a possibility to either increase the value of **RUN_WATCHDOG_HOMEASSISTANT_API** in **tasks.py** to more than 300 seconds or - even better - make this value configurable?

**Comment by clach04** [comment]
What look like other reports of the same problem:

 * https://community.home-assistant.io/t/after-update-to-0-60-1-home-assistant-gets-stuck/38377
 * https://community.home-assistant.io/t/solved-restart-looping/41572

I'm pretty sure I hit this too.
