### ISSUE TITLE
after hassio update to .61 there is a warning for running on 'dev'

### ISSUE THREAD

**Issue by cogneato** [home-assistant/hassio#315]
2018-01-15 15:36:06 WARNING (MainThread) [homeassistant.components.updater] Running on 'dev', only analytics will be submitted

also referenced here: https://github.com/home-assistant/home-assistant/issues/11679

**Comment by ciotlosm** [comment]
Version shows: 0.61.0.dev0

**Comment by pvizeli** [comment]
Fix with last push or 0.61.1

It was wrong taged.
