### ISSUE TITLE
0.61 Update Not Found

### ISSUE THREAD

**Issue by bakedraccoon** [home-assistant/hassio#317]
Hey there,

I'm trying to update, but when I click the update button this error appears in the logs.

```ERROR (SyncWorker_28) [hassio.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.61 -> 404 Client Error: Not Found ("manifest for homeassistant/qemux86-64-homeassistant:0.61 not found").```

**Comment by pvizeli** [comment]
fix :+1:
