### ISSUE TITLE
Z-Wave stick changes device identifier

### ISSUE THREAD

**Issue by frog32** [home-assistant/hassio#329]
Every time I add a new device to my z-wave network I have to at least once restart home assistant. After that z-wave does not come up correctly and I have the following message in the logs and dmesg. What would be the correct procedure to add a device without having to restart my entire raspberry?

`openzwave.object.ZWaveException: "Zwave Generic Exception : Can't find device /dev/ttyACM0 : ['NoneType: None\\n']"`

`
[ 2018.085087] usb 1-1.2: USB disconnect, device number 4
[ 2018.332179] usb 1-1.2: new full-speed USB device number 5 using dwc_otg
[ 2018.435412] usb 1-1.2: New USB device found, idVendor=0658, idProduct=0200
[ 2018.435425] usb 1-1.2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 2018.437672] cdc_acm 1-1.2:1.0: ttyACM1: USB ACM device
[ 2136.007773] udevd[10]: starting version 3.2.4
[ 2136.016461] udevd[10]: starting eudev-3.2.4
[ 2968.817733] udevd[9]: starting version 3.2.4
[ 2968.825446] udevd[9]: starting eudev-3.2.4
`

**Comment by frenck** [comment]
How do you restart Home Assistant on Hass.io currently? Via the Hass.io panel or via the Configuration panel?

**Comment by frog32** [comment]
Using the hassio panel.

**Comment by frog32** [comment]
This time I tried restarting from the configuration panel and it causes the same issue. Possible that this happens earlier and is not caused by the restart of home assistant.

**Comment by pvizeli** [comment]
I see the same, if I unplug the zwave stick and reattach it to device. But after host reboot it have the old device ID.

I don't think we can fix this with old resinos images, but with new buildroot we should able to fix it.

**Comment by pmsinger** [comment]
I have had the same issue previously with removing the Z-wave stick and having to recycle the entire box. To resolve this, I will shutdown homeassistant before removing the stick.

With hassio I installed ssh.
1) From ssh: hassio homeassistant stop
2) Unplug USB stick
3) Pair devices
4) Plug in USB stick
5) From ssh: hassio homeassistant start

Obviously during setup you will need to restart homeassistant a few more times to get the device configured properly.

**Comment by austwhite** [comment]
I know this thread is older, but this issue seems to be still present.
If I reboot from HASSIO panel, or restart from Configuration, the z-wave USB device, which usually is dev/ttyACM0, will sometimes change to dev/ACM1.    
It will also do this change from ACM0 to ACM1 if a Soft Reset is initiated.
This obviously upsets the z-wave configuration.
The only cure once it does this is to use SHUTDOWN from the HASSIO menu, then manually power cycle the device, which is a Raspberry Pi 3 Model B+ in my case.
