### ISSUE TITLE
python script not working at boot, despite...

### ISSUE THREAD

**Issue by asantos15** [home-assistant/hassio#336]
Hello everyone,

I have been hitting my head against the wall, as I try to have this script start at boot on a Raspbian:

This one aims to read motion detection from a sensor. It works fine when I run it manually, but not as a service!

_________________________________________________
#!/usr/bin/python

import time
import RPi.GPIO as GPIO
import paho.mqtt.client as mqtt
import paho.mqtt.publish as publish

# Def
broker = "..."
state_topic = "home-assistant/fundos/motion"
auth = {
  'username':"...",
  'password':"..."
}

# Use BCM GPIO references
# instead of physical pin numbers
GPIO.setmode(GPIO.BCM)

# Define GPIO to use on Pi
GPIO_PIR = 17

print ("PIR Module Holding Time Test (CTRL-C to exit)")

# Set pin as input
GPIO.setup(GPIO_PIR,GPIO.IN)      # Echo

Current_State  = 0
Previous_State = 0

#MQTT
client = mqtt.Client()
client.connect(broker)
client.loop_start()

try:

  print ("Waiting for PIR to settle ...")

  # Loop until PIR output is 0
  while GPIO.input(GPIO_PIR)==1:
    Current_State  = 0

  print ("Ready")
  publish.single('home-assistant/fundos/motion', 'no motion', hostname=broker, auth=auth)
  
  # Loop until users quits with CTRL-C
  while True:

    # Read PIR state
    Current_State = GPIO.input(GPIO_PIR)

    if Current_State==1 and Previous_State==0:
      # PIR is triggered
      start_time=time.time()
      print ("Motion detected!")
      publish.single('home-assistant/fundos/motion', 'motion detected', hostname=broker, auth=auth)
      # Record previous state
      Previous_State=0
    elif Current_State==0 and Previous_State==1:
      # PIR has returned to ready state
      stop_time=time.time()
      print ("Ready "),
      elapsed_time=int(stop_time-start_time)
      print ("(Elapsed time : " + str(elapsed_time) + " secs)")
      Previous_State=0
      publish.single('home-assistant/fundos/motion', 'no motion', hostname=broker, auth=auth)

except KeyboardInterrupt:
 print ("Quit")
  # Reset GPIO settings
  GPIO.cleanup()
------------------------------------------------------------
This is my .service file config:

[Unit]
Description=PIR Mqtt Service
After=multi-user.target

[Service]
Type=idle
ExecStart=/usr/bin/python /home/pi/pir.py > /home/pi/pir.log 2>&1
Restart=always
StandardOutput=syslog
StandardError=syslog
User=root

[Install]
WantedBy=multi-user.target

I have tried contrab, rc.local, systemd, init.d, etc. All shows the following status:
● pirmqtt.service - PIR Mqtt Service
   Loaded: loaded (/lib/systemd/system/pirmqtt.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-01-30 04:36:51 +03; 16min ago
  Process: 570 ExecStart=/usr/bin/python /home/pi/pir.py > /home/pi/pir.log 2>&1 (code=exited, status=1/FAILURE)
 Main PID: 570 (code=exited, status=1/FAILURE)

THANK YOU FOR ANY  #TIME/ATTENTION!

**Comment by ciotlosm** [comment]
@asantos15 Issue tracker on this repo is for bugs with hassio. Your problem is a generic sensor setup problem over MQTT. I recommend you post this on the forums to get more help: https://community.home-assistant.io/c/third-party

**Comment by pvizeli** [comment]
Write it as add-on like the bluetooth add-on: https://home-assistant.io/developers/hassio/addon_development/

**Comment by asantos15** [comment]
Moved to another more appropriate forum
