### ISSUE TITLE
No State History Found

### ISSUE THREAD

**Issue by rhettcp** [home-assistant/hassio#338]
After updating to version 0.62.0, the items in Home Assistant show "No State History Found" when clicked. Sometimes they will show the history correctly for 1-2 seconds but then default to the Not found.

This is running on a Raspberry Pi 2 with the hassio image burnt to the SD. Haven't changed anything other than the update, mostly using z-wave devices. Any suggestions?

<img width="348" alt="screen shot 2018-01-30 at 12 53 56 pm" src="https://user-images.githubusercontent.com/6452922/35582388-ac78742e-05bc-11e8-9436-081ccc8f3bfe.png">
Here is an example.

Seems to be fine on the "History" page. All items do this on the "Overview" page tho.

**Comment by ciotlosm** [comment]
Probably related to https://github.com/home-assistant/home-assistant/issues/12023 more than to hassio.

**Comment by rhettcp** [comment]
Good call, I'm still getting the hang of which is which. Thanks!
