### ISSUE TITLE
Reboot required for whitelist_external_dirs to take effect

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/hassio#341]
At 0.64.3,  a reboot of the hardware (not just restart of HA) is required for:
```
homeassistant:
  whitelist_external_dirs:
    - /share
```
to take effect. If I don't reboot I get the following error:
```
starting version 3.2.4
Testing configuration at /config
ERROR:homeassistant.config:Invalid config for [homeassistant]: not a directory @ data['whitelist_external_dirs'][0]. Got '/share'. (See /config/configuration.yaml, line 2). 
Failed config
.
.
.
    whitelist_external_dirs: [source /config/configuration.yaml:15]
      - /share
Successful config (partial)
  homeassistant:
```

**Comment by mr-sneezy** [comment]
This is still the case for me too six months later. Can use white_list only if I do a full power restart on the RPi, but cannot restart via the GUI list for other configuration changes. Gives the 'package' errors like some other get.

Using HA on RPi with HassOS.

**Comment by pvizeli** [comment]
If you restart home assistant only, we cleanup everything. So I don't see a different to a system reboot. You confirm, that a `hassio ha restart` command not work?

**Comment by pvizeli** [comment]
Oh, I see. We can fix that 👍

**Comment by mr-sneezy** [comment]
Fantastic news.
