### ISSUE TITLE
After panel update (.84?), themes no longer applied to hassio panel pages

### ISSUE THREAD

**Issue by cogneato** [home-assistant/hassio#342]
Themes are working everywhere except for the hassio menu.

**Comment by ekt-** [comment]
Same here. 
I got this in logs when accessing Hassio panel

`2018-02-01 11:45:06 INFO (MainThread) [homeassistant.components.http] Serving /api/hassio/app-es5/hassio-app.html to 192.168.1.117 (auth: False)`

`2018-02-01 11:45:14 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=system_log, service=write, service_data=logger=frontend.js.latest.201801300, message=https://192.168.1.119:8123/frontend_latest/panels/ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1:829 Uncaught TypeError: Cannot read property ‘setProperties’ of null, service_call_id=1964707344-56>`

`2018-02-01 11:45:14 ERROR (MainThread) [frontend.js.latest.201801300] https://192.168.1.119:8123/frontend_latest/panels/ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1:829 Uncaught TypeError: Cannot read property ‘setProperties’ of null`

`2018-02-01 11:45:14 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]: service_call_id=1964707344-56>`

**Comment by c727** [comment]
@ekt- that's different problem and might be already fixed in 0.62.1...

both issues should be reported to the polymer repo btw

**Comment by ekt-** [comment]
i'm on 0.62.1
is the PR #860 included or after the 0.62.1 release?

**Comment by jjtoard** [comment]
I'm missing something.  I don't understand how I can fix it.
