### ISSUE TITLE
Samba share config and Configurator config differ

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/hassio#344]
I'm experiencing that the config file I can edit with the Configurator is different from that I can edit via the Samba share. The file shown by Configurator is up to date whilst that shown by Samba is the default. Hassio 0.61

![image](https://user-images.githubusercontent.com/11855322/35721067-4adb2710-07e8-11e8-9461-81585d4726b9.png)

**Comment by robmarkcole** [comment]
Updated to 0.62.1 and issue persists

**Comment by pvizeli** [comment]
Browser cache?

**Comment by cogneato** [comment]
The file open in atom has a dash at the end, indicating that there are more than one file open with the same name, in different locations. At least, that's how it works for me.
