### ISSUE TITLE
Reboot fails with error - no route to host

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/hassio#345]
Hassio 0.62.1

Via ssh addon, on attempting reboot, get the following error:

```
core-ssh:~# hassio host reboot
The HTTP request failed with the error: Post http://hassio/host/reboot: dial tcp 172.30.32.2:80: getsockopt: no route to host
```

**Comment by RambozoClown** [comment]
Same here. Hass is only partially functional and looking for a way to restart outside the web interface.

**Comment by pvizeli** [comment]
-> CLI

**Comment by RambozoClown** [comment]
SSH CLI is where that error is returned. I have no way to restart except pull the plug, which always seems to corrupt the SD card and leads to a full reinstallation.

**Comment by spyderjosh** [comment]
I've just experienced this same issue this morning.  Only way to reboot the raspberry pi was to pull the power and now the card is corrupted and i'll be facing a complete rebuild.  Any ideas how to avoid this in the future?
