### ISSUE TITLE
Restore partial snapshot: homeassistant is not a valid paramter

### ISSUE THREAD

**Issue by c727** [home-assistant/hassio#346]
@pvizeli 
```
"error":"Response error: 400","status_code":400,"body":{"result":"error","message":"extra keys not allowed @ data['homeassistant']. Got True"}}
```

API says:

POST /snapshots/{slug}/restore/partial
```
{
    "homeassistant": "bool",
    "addons": ["ADDON_SLUG"],
    "folders": ["FOLDER_NAME"]
}
```

**Comment by ciotlosm** [comment]
@pvizeli I think the problem is here: https://github.com/home-assistant/hassio/blob/6f2cf2ef8514396b56346c09cccaebfe3c3127d5/hassio/api/snapshots.py#L121 where it should be using `SCHEMA_RESTORE_PARTIAL` instead of  `SCHEMA_SNAPSHOT_PARTIAL`
