### ISSUE TITLE
Increase Docker Read Timeout

### ISSUE THREAD

**Issue by korylprince** [home-assistant/hassio#347]
Please consider increasing the docker-py read timeout from 60 to something much larger (300?) I'm [seeing](https://community.home-assistant.io/t/new-caddy-add-on/37084/18) timeouts on Raspberry Pis when they first start up, causing add-ons to not start correctly.

I think this is also the root cause of issue #323.

**Comment by pvizeli** [comment]
Thanks, will be fix with next version
