### ISSUE TITLE
Enable support for IPv6

### ISSUE THREAD

**Issue by alexbarcelo** [home-assistant/hassio#355]
The `hassio` bridge network doesn't has the IPv6 network stack enabled.

"Culprit" seems to be the line at `hassio/docker/network.py`, in particular the parameter `enable_ipv6=False` in the method `_get_network`.

Enabling is not as straightforward as puting there `True` because to set up correctly IPv6 a subnet should be specified. And that subnet is typically provided by the user (if the user is doing globally routable addresses, which is a likely scenario in IPv6 environments).

I haven't come up with a proposal on how to address that. I was open to suggestions (if a PR is feasible and appreciated, I can work on that) or some workaround tips otherwise (if there are any).

**Comment by Fubi95** [comment]
Go to the HomeAssistant Config file under component http and add server_host: "::0"

**Comment by alexbarcelo** [comment]
@Fubi95 yeah, I added that to the documentation. Note that the homeassistant container is *not* part of the `hassio` bridge, as that container uses host network mode and thus works correctly with IPv6 if the host has IPv6.

However, the problem I found is for the addons, which typically use the `hassio` bridge which --when created-- has an explicit disable of ipv6.

I have abandoned this route, as it started to seem (at least to me) painful and cumbersome. And Docker itself has no clean semantics and features for IPv6 stack of containers IMHO. So not sure if it is worth having this issue opened, as I don't know if it will benefit anybody in the short term.

**Comment by donnib** [comment]
@alexbarcelo I would love to expose my hassio on IPv6 but as far as i understand it's not possible now, correct ?

**Comment by alexbarcelo** [comment]
@donnib You can expose hassio to IPv6 because, as I said, that container is *not* part of the `hassio` bridge. According to my comment (which I honestly don't remember at all) I updated something in the documentation, probably related to the @Fubi95 comment.

That will expose hassio to IPv6, but will not work for any other container in the hassio environment. That was my use case, and was not supported. ATM I am using vanila dockerized hass, so you should try it yourself /shrug

**Comment by alexbarcelo** [comment]
(see https://www.home-assistant.io/components/http/ > `server_host`)

**Comment by donnib** [comment]
@alexbarcelo the doc says explicitly : Don’t use option server_host on a Hass.io installation!

**Comment by alexbarcelo** [comment]
So... either I did not see it, or it was not there when I was toying around.

If somebody wants to try it, go ahead. I have stopped using Hass.io a while ago so I will keep an eye on the project but I am not doing anything with it at the moment.

**Comment by alexbarcelo** [comment]
Sorry if it came out as passive aggressive, wasn't my intention, I was in a hurry.

IMHO given my previous experience, Hass.io is phenomenal for easy deployment on typical use cases, specially for non-techie users. Using IPv6 doesn't seem to fit that scenario. IPv6 networks are cumbersome and is very difficult to provide a default behavior one-fits-all that is actually useful. And lots of IoT gadgets are not IPv6 ready, so everything should be dual stack, and to be honest, dual stack feels not so useful right now.

With more perspective (from when I started the issue), I think that it is too soon to give support for IPv6 --I feel it would be a waste of efforts given the current IPv6 ecosystem.

**Comment by pvizeli** [comment]
I agree

**Comment by donnib** [comment]
@pvizeli @alexbarcelo 
My use case was to allow Hass.IO to be accessed from the outside world when i have Carrier Grade NAT otherwise that won't be possible. I think this case is still valid for many users that they don't have a public IPv4 address. Maybe this case is simpler than what you are worried about. Please correct.

**Comment by alexbarcelo** [comment]
In Spain, there is no ISP offering IPv6 AFAICT. There are some of them using CGNAT, and in those cases you are basically screwed.

You are right that this specific use case is simpler than the original issue --what I had in mind was something along "support the whole IPv6 hybrid network stack inside the IoT local network". However the scenario you describe was (maybe still is) simply solved by changing the `server_host`. It beats me why it is discouraged in the documentation, given that it used to work.

**Comment by donnib** [comment]
@pvizeli do you know why it's not recommended to use ```server_host``` ?

**Comment by troykelly** [comment]
> IMHO given my previous experience, Hass.io is phenomenal for easy deployment on typical use cases, specially for non-techie users. Using IPv6 doesn't seem to fit that scenario. IPv6 networks are cumbersome and is very difficult to provide a default behavior one-fits-all that is actually useful. And lots of IoT gadgets are not IPv6 ready, so everything should be dual stack, and to be honest, dual stack feels not so useful right now.
> 
> With more perspective (from when I started the issue), I think that it is too soon to give support for IPv6 --I feel it would be a waste of efforts given the current IPv6 ecosystem.

It is _too late_ for any platform or product to not be fully embracing IPv6.
IPv6 is no different to IPv4. IPv6 is no more confusing, cumbersome, difficult or any other descriptor that is being thrown around than IPv4 was.
It is becoming common place - especially for major ISP's in the USA.

What is difficult (in my experience) is docker networking and IPv6. But that shouldn't hinder the implementation of IPv6 for Home Assistant/Hass.io.

**Comment by TheZoker** [comment]
I Germany many ISPs only offer [dslite](https://en.wikipedia.org/wiki/IPv6_transition_mechanism#Dual-Stack_Lite_.28DS-Lite.29), where you have a public IPv6 but no IPv4. So if I want to use HA outside my network, I need to use IPv6. 
Adding the `::0` value to the `server_host` does work for me. So why is it not recommend to use it with hassio? 

And I agree, that IPv6 is the future and it should be supported as soon as possible (not only Hassio, but all applications in general).

**Comment by troykelly** [comment]
This really should stay open.
IPv6 support is exceptionally important

**Comment by codyc1515** [comment]
Can we please re-open this? To the people saying it’s too soon for IPv6, it’s been 26 years.

**Comment by agners** [comment]
@codyc1515 just to be clear, on a host level Home Assistant Supervisor supports IPv6: The Core runs in host network mode, as well as Add-on which have host network enabled. Those can directly communicate using IPv6. Also the Supervisor supports setting IPv6 addresses through its network configuration setting.

What currently is missing is IPv6 support for the internal isolated `hassio` network, and add-ons which use this network option (as opposed to host network). This is planned and tracked with #2133.

**Comment by codyc1515** [comment]
Thanks for clarifying. I appreciate it.
