### ISSUE TITLE
snapshots not successfully created using .63 or .63.1, supervisor .88

### ISSUE THREAD

**Issue by cogneato** [home-assistant/hassio#357]
docker logs ---follow for supervisor: https://hastebin.com/iwarugimus.sql
Snapshot is not created in backups directory, attempts to create another show that the process is already running. CPU use (pi3) pegs around 30% and remains there (also cpu temp increases) until reboot.

**Comment by pvizeli** [comment]
https://github.com/docker/docker-py/pull/1906

**Comment by pvizeli** [comment]
Will be fixed with next docker-py updated

**Comment by mattlward** [comment]
I thought mine were not creating either, but it took hours for each one to finish.  Try starting one and just walk away and check later in the day.
