### ISSUE TITLE
Would be nice to add support for Sonoff switches

### ISSUE THREAD

**Issue by Bauke777** [home-assistant/hassio#366]
I would love to see support for Sonoff wi-fi switches

**Comment by disrupted** [comment]
what do you mean? I already use a bunch of these configured as [MQTT switch / light](https://home-assistant.io/components/switch.mqtt/). Check out https://github.com/KmanOz/KmanSonoff or https://github.com/arendst/Sonoff-Tasmota as a custom firmware for your Sonoffs.

**Comment by Bauke777** [comment]
Hmmm good point. Wich of those do you use/prefer yourself?

**Comment by disrupted** [comment]
I've used both and they're quite excellent. It really depends on what you are trying to achieve. Tasmota is very powerful and can do just about anything but it's also a bit more complex to set up. the Kman firmware has a more minimal approach and runs very stable. If you just want to connect some Sonoff Basic's to HA via MQTT I'd choose the latter.

**Comment by disrupted** [comment]
I believe this can be closed.

**Comment by Bauke777** [comment]
Fixes #366
