### ISSUE TITLE
Hassio 0.63.2 and 0.63.3 system panel blank

### ISSUE THREAD

**Issue by mattlward** [home-assistant/hassio#378]
The system panel contains nothing at this point and does not look like it did in 0.62 and earlier.  The system has been power cycled, everything else seems fine at this point.

![image](https://user-images.githubusercontent.com/8540074/36626223-a2fb9250-18f4-11e8-8084-54c3dc7425f4.png)

This is my addon page now, totally different as well.
![image](https://user-images.githubusercontent.com/8540074/36626287-cc2187b0-18f5-11e8-8ef8-cafd2d9b5b08.png)

**Comment by cogneato** [comment]
Yes, UI update in Hassio .92

<https://github.com/home-assistant/hassio/releases/>

The system panel will have Host and Supervisor entries soon, hopefully.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/home-assistant-polymer/issues/914
