### ISSUE TITLE
errors starting Hassio

### ISSUE THREAD

**Issue by vpomax** [home-assistant/hassio#381]
I use HA 0.64 and HASSIO 0.94
from yesterday night after restarting HassIO it show me this errors…

18-02-25 22:20:26 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:27 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:27 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:27 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:27 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons
18-02-25 22:20:28 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:28 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons
18-02-25 22:20:29 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:29 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:29 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:29 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:30 WARNING (MainThread) [hassio.api.security] Invalid token for access /supervisor/info

Please help me...

**Comment by frenck** [comment]
This issue is rather old and is not reported more often by other users.
Therefore I assume this is no longer an issue, if it still is, feel free to re-open and letting us know the current status.
