### ISSUE TITLE
Feature Request: hassio (ho | su | ha ) update status

### ISSUE THREAD

**Issue by jeubanks** [home-assistant/hassio#382]
Can a progress/status be added to the CLI when performing updates?

**Comment by ryanm101** [comment]
Not directly. I would need @pvizeli to add "progress" endpoint to be returned by "update" in the header. 
I could then poll that and it could hold the "%" complete or something. but in its current form I can do nothing as the api only returns when it is finished

**Comment by ryanm101** [comment]
@pvizeli 
Could you change the update endpoint to return a 201 and a "location" header with an endpoint that can be polled? This would actually be a REST best practice.

**Comment by pvizeli** [comment]
I don't see a real benefit with this. We block on request, so the application can show a progressing until the request is done. We can not have more other details. Maybe we can add a log streaming endpoint.

**Comment by ryanm101** [comment]
I think the main complaint here it there is no difference to an end user between a "block" and a "hang" they just have to trust that the cli / app is working away.

**Comment by balloob** [comment]
The problem is that for progress to be reported, each layer will have to start reporting progress. And for progress to be reported, each layer will have to get a lot more complicated because it would have to switch from a synchronous call (you call, you get a response), to an asynchronous call: you call, get an identifier and then poll that identifier via a different API.

**Comment by ryanm101** [comment]
In the case of hassio though when we update hass the supervisor stays "up" so in theory we could poll docker on the host to get the state by redirecting docker pull to a file and then tailing that. 
It may not be possible for the supervisor update but for hass and the host (not sure how the host updates in resinos) could out put apt to a log file for tailing. ?

**Comment by pvizeli** [comment]
we can make the supervisor log streamable i.e. with `/supervisor/tail`

**Comment by balloob** [comment]
I think that would be a great start Pascal.

Here is some CoffeeScript code by Resin-OS that converts docker pull logs to progress: https://github.com/resin-io/docker-progress/blob/master/index.coffee#L99-L153

**Comment by frenck** [comment]
This should be in the hassio-cli repo.

/move home-assistant/hassio-cli
