### ISSUE TITLE
Support for updated USPS component

### ISSUE THREAD

**Issue by PhilRW** [home-assistant/hassio#384]
0.64 now supports a new method of utilizing the USPS Informed Delivery service. Recommended method is to install the latest version of Google Chrome and chromedriver (see [PR](https://github.com/home-assistant/home-assistant/pull/12465) and [docs](https://home-assistant.io/components/usps/)).

**Comment by mattlward** [comment]
Can one use this on a Dockered RPi2 with Hassio?  I am not sure how to install the required software.

**Comment by PhilRW** [comment]
It requires Google Chrome to be installed, perhaps there is a headless version that would work.

**Comment by mattlward** [comment]
So far, the trick has been installing anything that is not in the store as a prepackaged app.

**Comment by pvizeli** [comment]
can we run the daemon inside add-on like homematic, tellstick?

**Comment by PhilRW** [comment]
The author of the fix said that it has to be in the `PATH`, so I don't know.

**Comment by toddw65** [comment]
I've been able to build & run it successfully with the attached add-on.


[chrome.zip](https://github.com/home-assistant/hassio/files/1822280/chrome.zip)

**Comment by toddw65** [comment]
Yeah,  it's an add-on like homematic, tellstick, etc.  Like you mentioned [above](https://github.com/home-assistant/hassio/issues/384#issuecomment-369677543).

It consists of:
```
#!/bin/bash
# Sets up chrome & chromedriver.

# Stop on errors
set -e

PACKAGES=(
    xvfb libxi6 libgconf-2-4 unzip curl
)

# Required debian packages for running hass or components from jessie-backports
PACKAGES_BACKPORTS=(
  openjdk-8-jre-headless java-common ca-certificates-java
)

apt-get install -y --no-install-recommends -t jessie-backports ${PACKAGES_BACKPORTS[@]}
apt-get install -y --no-install-recommends ${PACKAGES[@]}

# Versions
CHROME_DRIVER_VERSION=$(curl chromedriver.storage.googleapis.com/LATEST_RELEASE)


# Install Chrome.
curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
apt-get -y update
apt-get -y install google-chrome-stable

# Install ChromeDriver.
wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
unzip ~/chromedriver_linux64.zip -d ~/
rm ~/chromedriver_linux64.zip
mv -f ~/chromedriver /usr/local/bin/chromedriver
chown root:root /usr/local/bin/chromedriver
chmod 0755 /usr/local/bin/chromedriver
```
And then in the "setup_docker_prereqs" file I added:

`INSTALL_CHROME="${INSTALL_CHROME:-yes}"`

and 

```
if [ "$INSTALL_CHROME" == "yes" ]; then
  virtualization/Docker/scripts/chrome
fi
```
