### ISSUE TITLE
partial backup not working for folders/addons = []

### ISSUE THREAD

**Issue by c727** [home-assistant/hassio#386]
if `folders = []` or `addons= []` all folders/addons are included in the snapshot

```
{"name":"Montag, 26. Feb. 2018","folders":["ssl"],"addons":[]}
{"name":"Montag, 26. Feb. 2018","folders":[],"addons":["a0d7b954_terminal"]}
{"name":"Montag, 26. Feb. 2018","folders":[],"addons":[]}
```
workaround: select at least 1 folder/addon

cc: @cogneato

**Comment by pvizeli** [comment]
Maybe I can fix that on backend. The backend use all = empty list and None as null or if not exists
