### ISSUE TITLE
064.1 time off in system logs by the amount of my time zone offset...

### ISSUE THREAD

**Issue by mattlward** [home-assistant/hassio#393]
My system logs are showing +6 hours compared to my shell date command.  

Time zone from configuration.yaml:
America/Chicago

shell date command:
Wed Feb 28 22:36:23 CST 2018

Last logged entry in Hassio System logs:
18-03-01 04:27:48 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from core_configurator

The time appears to be off my the amount of my time zone offset.

Should they not match?

**Comment by pvizeli** [comment]
The supervisor run in UTC

**Comment by morhimi** [comment]
Hi @pvizeli , is there a way to update the supervisor timezone?
