### ISSUE TITLE
Cannot start configurator add-on

### ISSUE THREAD

**Issue by wind-rider** [home-assistant/hassio#396]
I have problems with hass.io in Edge and Chrome:

When trying to start the configurator add-on in the Edge browser (latest version of hass.io and browser), nothing happens and the following errors pop up in the browser console. There are no errors in the hass.io system log.

```
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - http://192.168.0.7:8123/api/hassio/build-temp/util.js

 HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
(XHR)POST - http://192.168.0.7:8123/api/hassio/addons/core_configurator/start
```

In Chrome I get:
```
Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).     core_configurator:1
Failed to load resource: the server responded with a status of 404 (Not Found)    util.js
POST http://192.168.0.9:8123/api/hassio/addons/core_configurator/start 400 (Bad Request)
```

**Comment by wind-rider** [comment]
It turns out that the default config for the configurator has a `null` password but the addon requires a password to be set.

**Comment by drjayvee** [comment]
I ran into this shortly after installing Hass.io. Without the configurator, I can't install either the Samba or SSH add-on, so I don't even know how to work around this.

@wind-rider, can you point me to the configuration file's path and describe what change to make to get this to work?

**Comment by wind-rider** [comment]
In the addon section of hass.io open the Configurator settings.

Below the panel where you can e.g. restart the Configurator, you can configure its basic settings like the port to run on or the password.

**Comment by drjayvee** [comment]
The addon section (clicking on Hass.io in the menu) remains blank, perhaps because util.js can't be loaded?

I thought that was the bug you were reporting here. :D
