### ISSUE TITLE
Hass.io System Logs Wrong date/time + use local time

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/hassio#400]
If I go to hassio->System the system log is displayed with an incorrect date from September last year:

starting version 3.2.4
17-09-17 13:49:44 INFO (MainThread) [__main__] Initialize Hassio setup
17-09-17 13:49:45 INFO (MainThread) [__main__] Setup HassIO

Also it eventually 'jumps' to correct date and time:

17-09-17 13:49:55 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_terminal
18-03-05 22:30:26 INFO (MainThread) [hassio.api.security] /addons/a0d7b954_terminal/info access from a0d7b954_terminal

With the correct date and time, is it possible for this to be displayed in LOCAL time please? (We are UTC +11hrs here)

Thanks.

**Comment by sirs2k** [comment]
I'm having the same issue.

The Hassio UI is showing the correct Sydney time
But the Log file is showing UTC time

How can I change the OS time?
