### ISSUE TITLE
No Home Assistant or SSH after update to 65.4

### ISSUE THREAD

**Issue by messismore** [home-assistant/hassio#416]
Hi I attempted to update Home Assistant from 65.0 to 65.4 via the UI yesterday. The update button showed the spinner for a while and went back to normal without any indication whether or not something had happened. When I rebooted the system, Home Assistant did not start up, SSH is gone also (Connection refused). I can ping the machine though.

Is there any way to get back into the system and avoid starting over from scratch?

**Comment by pvizeli** [comment]
SSH ist startup before home-assistant. So it look like follow problems:
- Need a reboot more while docker service have a problem
- SD card is damage
- Power Supply is not enaught
- Harddisk is full

**Comment by messismore** [comment]
> Harddisk is full

Bingo! Thanks a lot for your pointers!
