### ISSUE TITLE
Addon fails to start with error: Conflict. Container name already in use.

### ISSUE THREAD

**Issue by jsmath** [home-assistant/hassio#418]
Having an issue upgrading to v2.3.0 of the Terminal add-on. Have tried uninstalling, rebooting host/restarting hassio and reinstalling add-on multiple times. When starting the add-on I get the same error every time in the System log (see below). No log for add-on since it never starts.
18-03-20 01:03:36 INFO (MainThread) [hassio.addons.addon] Create Home-Assistant addon data folder /data/addons/data/a0d7b954_terminal
18-03-20 01:03:36 INFO (SyncWorker_15) [hassio.docker.interface] Pull image hassioaddons/terminal-armhf tag 2.3.0.
18-03-20 01:03:37 INFO (SyncWorker_15) [hassio.docker.interface] Tag image hassioaddons/terminal-armhf with version 2.3.0 as latest
18-03-20 01:03:38 WARNING (SyncWorker_1) [hassio.docker.interface] Can’t grap logs from hassioaddons/terminal-armhf: 500 Server Error: Internal Server Error (“can not get logs from container which is dead or marked for removal”)
18-03-20 01:03:46 WARNING (SyncWorker_11) [hassio.docker.interface] Can’t grap logs from hassioaddons/terminal-armhf: 500 Server Error: Internal Server Error (“can not get logs from container which is dead or marked for removal”)
18-03-20 01:03:49 INFO (SyncWorker_0) [hassio.docker.interface] Clean hassioaddons/terminal-armhf docker application
18-03-20 01:03:49 ERROR (SyncWorker_0) [hassio.docker] Can’t create container from addon_a0d7b954_terminal: 409 Client Error: Conflict (“Conflict. The container name “/addon_a0d7b954_terminal” is already in use by container “afde0eba…”. You have to remove (or rename) that container to be able to reuse that name.”)
18-03-20 01:04:31 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/hassio-addons/repository repository
18-03-20 01:04:31 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/home-assistant/hassio-addons repository
18-03-20 01:04:32 INFO (MainThread) [hassio.addons] Load addons: 32 all - 0 new - 0 remove

**Comment by pvizeli** [comment]
Can you more explain your environment where hass.io is running?

**Comment by jsmath** [comment]
It is running on a Raspberry Pi 3.

**Comment by jsmath** [comment]
I'm using the latest resinos host version (1.3) and Hass.io supervisor (0.98).

**Comment by pvizeli** [comment]
Can you reboot the host?

**Comment by pvizeli** [comment]
Can you explain what do you have done to run into issue. A full log from supervisor and what kind of system envoiremnt do you have (version of HassOS, ResinOS, docker)

**Comment by jsmath** [comment]
I still see this issue when trying to install and then start the Terminal addon. I posted my log earlier. From what I recall, the issue happened when I was not patient when uninstalling and then reinstalling (or maybe starting) the addon from the hass.io web UI. It would be nice if there was a way to clear out this error without completely reinstalling Hass.io.

**Comment by pvizeli** [comment]
Look like a docker bug. Can you try HassOS? They use a actual docker-ce version.

**Comment by jsmath** [comment]
Have been interested in trying HassOS, but wasn't sure if it was ready for prime time yet. I also have not seen any install instructions for raspberry pi on the home assistant website.

**Comment by ndarilek** [comment]
Is there no fix for this? I wish Hass.io at least exposed access to Docker. So many of the issues I've encountered would be made easier by just giving me access to Docker itself. I don't even care if Hass.io is explicit about trashing any non-blessed containers. Just being able to remove dead containers like this would be great, or being able to see build logs, etc.

No I don't know what I did to get into this state, and no rebooting doesn't fix things. I know and generally support wanting to lock things down, but on one hand Home Assistant encourages tinkering with home automation, and on the other Hass.io is almost actively hostile to even accidentally stepping off the happy path as I did here.

**Comment by rschuiling** [comment]
Same issue here, I think I also perhaps was too impatient when updating DuckDNS add-on from 1.0 to 1.5. Now the DuckDNS add-on doesn't start anymore. Same error: 409 Client Error: Conflict (“Conflict. The container name “/addon_xxxxx_terminal” is already in use by container xxxxx.

Is there perhaps a solution for this?

**Comment by jsmath** [comment]
I did as suggested by pvizeli and am now using HassOS on a different microSD card. Have not seen this issue on HassOS. See details here:
https://www.home-assistant.io/blog/2018/07/11/hassio-images/

**Comment by bighi** [comment]
I'm also having this problem. It seems like it's trying to create a new container, and the previous one wasn't properly disposed of?

The bad part of this is that there's nothing I can do. Hassio doesn't let me run a proper terminal, and I can't control the docker containers.
