### ISSUE TITLE
Hassio does not work with Raspberry Pi 3 (as well as RP3+)

### ISSUE THREAD

**Issue by gelazanskas** [home-assistant/hassio#422]
Hassio does not start using the latest image and Etcher from here:
https://home-assistant.io/getting-started/

**Comment by arsaboo** [comment]
I just it a few days back, so it definitely works. Please provide detailed information on what is not working or where is it stuck. As a first step, make sure you have a good SD card and a decent power supply for your Pi.

**Comment by gelazanskas** [comment]
Hi thanks for fast reply. I am currently trying to setup. The Hassio just gets stuck at the HA logo (when connected to the monitor). It also repeatedly tries to connect to the router (I see that from the router UI). The http://hassio.local:8123 does not respond.

On the other hand, the hassbian works on the exact same setup (power supply, SD card, RPi3)...
I assumed it is the same issue as with RPi3+, as stated in here https://home-assistant.io/getting-started/

**Comment by arsaboo** [comment]
The docs clearly state that the initial Hassio setup takes time....please be patient.

**Comment by pvizeli** [comment]
Maybe your system have no support for local domains. Can you connect with IP address?

**Comment by osstynd** [comment]
I have the same issue: I cannot even ping the IP address for the PI3 (I have given it a fixed IP@ through the router, based on the MAC address). Seems like there is no IP connectivity, though using wired connection.
