### ISSUE TITLE
Custom Component Dependencies and REQUIREMENTS hash

### ISSUE THREAD

**Issue by tyler-vincent** [home-assistant/hassio#425]
I'd like to run the in development version of `zha_new` (https://github.com/Yoda-x/ha-zha-new) on hass.io but I've run into an issue. This component relies on forked branches of `bellows` and `zigpy`. While I can install those manually via `pip3` the changes are wiped out upon reboot. 

In the custom component file I see `REQUIREMENTS = ['bellows', 'zigpy']` which is what I think is causing the issue. Can I specify a GIT url here so that hassio will install the forked version? If not, is there an easy way around this to test this component outside of installing Hassbian?

**Comment by pvizeli** [comment]
Use the new add-on for control this stuff
