### ISSUE TITLE
ASUSWRT how to deal with changing hostkeys?

### ISSUE THREAD

**Issue by mgolisch** [home-assistant/hassio#426]
The component uses openssh and will create the known_hosts file in /root/.ssh/known_hosts inside the container.
When upgrading the Router firmware it changes the ssh hostkeys and the component fails to connect to the router afterwards.
The only way i found solving that with hassio is enabling the debug ssh and docker execing into the ha container to change the known_hosts file.
Users should not be forced to enable the debug/host ssh at anytime.
Is there other ways of accessing the ha containers filesystem without enabling the host/debug ssh?
Maybe an option to recycle/recreate the ha container would be an easy way out of this problem.

**Comment by pvizeli** [comment]
You can stop home-assistant and start it again, that will clean the current filesystem layer.

**Comment by pvizeli** [comment]
We can make, that a reboot all time recreate the filesystem layer?

**Comment by pvizeli** [comment]
Fix next version with a simple restart
