### ISSUE TITLE
Support for Raspberry pi model B+

### ISSUE THREAD

**Issue by danielsjf** [home-assistant/hassio#438]
Is this development on the roadmap?

**Comment by CookieMonster87** [comment]
I see B+ support is added in the source files, but no idea when it will be released.

**Comment by danielsjf** [comment]
I guess it will be in the release of an hour ago. It probably won't take long to create the image from here.

**Comment by pvizeli** [comment]
Hass.io-OS

**Comment by danielsjf** [comment]
But that's still a work in progress for the moment. I suppose it's easier to add support for hass.io. Or could we expect a final release for hassio-os soon?

**Comment by pahlby** [comment]
@danielsjf a tweet says hassio-os is about 85% finished, a preview will be out shortly, you can follow pvizeli here: https://twitter.com/pvizeli

@CookieMonster87 yes, hassio-os is created with buildroot.

**Comment by frenck** [comment]
The new HassOS based images with 3B_ support are available. Therefore closing this issue 🎉
