### ISSUE TITLE
zwave.set_config_parameter broken

### ISSUE THREAD

**Issue by inputd** [home-assistant/hassio#439]
Hello,

Running HA 0.66.1, Hass.io 0.99.  Zwave parameters cannot be set using the services menu, or by automation script.

Currently I just have a single zwave device installed - a dome siren. In the services section of the developer tools, I am using the following code, for service zwave.set_config_parameter
`{
 "node_id" : 2,
 "parameter" : 7,
 "value" : 2
}`

 It accepts the code, and then nothing happens - the OZW_Log does not update, and the HA log doesn't update either. 

I can use Configuration>Zwave to verify the node id/parameter/values above are all correct. Additionally, I can change parameter values just fine in this menu.

Going through the various zwave services, some work just fine (heal_network works, resfresh_node works). I experienced the same issue with print_config_parameter though.

**Comment by stiansoevik** [comment]
I am having the same issue. I could set parameters for one device (which lacks parameter description in OpenZWave) via the service, but for another device, nothing happens when trying to configure a parameter through the service (although I can set its parameters through Configuration -> Z-Wave GUI).

**Comment by inputd** [comment]
I finally figured this out, I should have updated this post:

You have to pass the item label, NOT the value. Your zwcfg_xxxx.xml file will show you both. So in my original post:

{ "node_id" : 2, "parameter" : 7, "value" : 2 }

should have been

{ "node_id" : 2, "parameter" : 7, "value" : "Sound 5 - Low Volume" }

**Comment by labaland** [comment]
> I finally figured this out, I should have updated this post:
> 
> You have to pass the item label, NOT the value. Your zwcfg_xxxx.xml file will show you both. So in my original post:
> 
> { "node_id" : 2, "parameter" : 7, "value" : 2 }
> 
> should have been
> 
> { "node_id" : 2, "parameter" : 7, "value" : "Sound 5 - Low Volume" }

THANK YOUU!!!! so many days trying to make this works. TY 2 years later :D
