### ISSUE TITLE
Missing build 0.67.0 (and 0.67.1) for docker image qemuarm-64-homeassistant

### ISSUE THREAD

**Issue by hako74** [home-assistant/hassio#447]
Hi,

I'm one of the few people using the `qemuarm-64-homeassistant` docker image with Hassio. Since the release of 0.67.0 I'm unable to update from 0.66.1. It took a while to figure out the docker image installed on my Hassio system (Khadas VIM Lite) is a qemuarm-64. 
Somehow for this image there is no new build for de latest Homeassistant version, the latest available version is 0.67.0b0.
https://hub.docker.com/r/homeassistant/qemuarm-64-homeassistant/tags/

**Comment by pvizeli** [comment]
is fix soon
