### ISSUE TITLE
DNS resolution fails from within the containers

### ISSUE THREAD

**Issue by Diaoul** [home-assistant/hassio#448]
*After posting on [hassio forum](https://community.home-assistant.io/t/dns-resolution-issue/50833) and discussion on Discord, I've been advised to open an issue here.*

I'm having issues with the DNS resolution in Home Assistant. All my local hostnames are not resolved properly. Reboots don't solve the issue. It's not always the case though, it worked fine for quite some time and reappeared only a few days ago.

On the host (ssh root@hassio -p 22222):

    $ ifconfig eth0
    eth0      Link encap:Ethernet  HWaddr B8:27:EB:7F:E7:62  
              inet addr:10.0.1.4  Bcast:10.0.1.255  Mask:255.255.255.0
              inet6 addr: xxxxxxxxxxxxxxxxxxxxx Scope:Link
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:7110 errors:0 dropped:0 overruns:0 frame:0
              TX packets:6594 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000 
              RX bytes:1139758 (1.0 MiB)  TX bytes:811329 (792.3 KiB)

    $ cat /etc/resolv.conf 
    # Generated by NetworkManager
    search zzzz
    nameserver 10.0.1.3  <- PiHole
    nameserver 10.0.1.1  <- Router
    nameserver 8.8.8.8   <- Google

    $ nslookup syno
    Server:    10.0.1.3
    Address 1: 10.0.1.3 pihole

    Name:      syno
    Address 1: 10.0.1.2 syno.zzzz

Now the same thing from within the SSH addin (ssh root@hassio):

    $ ifconfig eth0
    eth0      Link encap:Ethernet  HWaddr 02:42:AC:1E:21:01  
              inet addr:172.30.33.1  Bcast:0.0.0.0  Mask:255.255.254.0
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:202 errors:0 dropped:0 overruns:0 frame:0
              TX packets:88 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:29652 (28.9 KiB)  TX bytes:16002 (15.6 KiB)

    $ cat /etc/resolv.conf 
    nameserver 127.0.0.11
    options ndots:0

    $ nslookup syno
    nslookup: can't resolve '(null)': Name does not resolve

    Name:      syno
    Address 1: 10.0.1.2 syno.zzzz

And now from the homeassistant container (with docker exec from within the host):

    $ cat /etc/resolv.conf 
    nameserver 172.30.32.2
    options ndots:0

    $ nslookup syno
    nslookup: can't resolve '(null)': Name does not resolve

    nslookup: can't resolve 'syno': Name does not resolve

So the funny thing is that it works when I configure my DHCP (on the router) not to advertise the DNS 10.0.1.3.
And when I add it back it stops working again.

The logs on the DNS server on 10.0.1.3 don't show any activity when I `nslookup` from within the homeassistant container but it works fine on the host and I  can see the logs.

**Comment by leinich** [comment]
I'm currenlty facing the same issue.
Is there any progress regarding this issue?

**Comment by Diaoul** [comment]
It seems DNS queries made on the `homeassistant` container are forwarded to `resin_supervisor` with `172.30.32.2` as IP address which in turn forwards them with `socat`  to `127.0.0.11`.

Somehow, the link between `resin_supervisor` container and `127.0.0.11` was broken as I couldn't resolve from within `resin_supervisor`.

I managed to resolve within `resin_supervisor` after I restarted it which is really weird. Somehow the link between `resin_supervisor` and `127.0.0.11` was broken (or maybe `socat` but then I would've been able to resolve from within `resin_supervisor` *before* the restart).
I could still resolve from other addon that don't use this tunneling but have `127.0.0.11` in their `/etc/resolv.conf` directly (ssh addon, and a few others I tried).

@pvizeli any thoughts?

**Comment by pvizeli** [comment]
That is a docker problem. He use only the first DNS server. And they have a problem with pihole. Can you try HassOS, maybe the last docker ce resolve the problem?

**Comment by Diaoul** [comment]
HassOS? I'm not sure how I am supposed to use that. I'm currently running Hassio on RPi 3.

Other addons are not affected by this, only the homeassistant container is (and resin_supervisor).

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassos

**Comment by Diaoul** [comment]
This is different from the Hassio install based on resinos ?

Le mer. 20 juin 2018 à 16:44, Pascal Vizeli <notifications@github.com> a
écrit :

**Comment by mgafner** [comment]
i had the same problem with the home-assistant docker image `homeassistant/home-assistant` on a debian host.

this helped me to fix the problem:
https://github.com/home-assistant/hassio/issues/497#issuecomment-401496769

**Comment by Diaoul** [comment]
Still having the issue on RPi3 with HassIO.

**Comment by Diaoul** [comment]
Flashing HassOS, I'll keep you posted if I can reproduce with it.

**Comment by Diaoul** [comment]
So far so good. I close this and will reopen if I face the issue again.

**Comment by DeviousPenguin** [comment]
Diaoul how did you fix this in the end? I'm having the same issue and I've tried a fresh install of Hass.io on a RPI 3 and would like to know how you resolved this issue.

Thanks

**Comment by Diaoul** [comment]
I'm using HassOS which is a different OS from what has been done before and thus has a different way of handling DNS relay from Docker containers to the host's DNS. It seems a lot more reliable than the previous implementation.

**Comment by olskar** [comment]
I am also having this problem, with latest hassos.

**Comment by Nixellion** [comment]
The only thing that worked for me was creating a cron job that runs this command every minute or so:

`docker exec -d homeassistant bash -c "echo 'nameserver 192.168.1.1' > /etc/resolv.conf"`

Maybe it will be useful for someone. Replace IP with your DNS, 192.168.1.1 is my router. You can use 1.1.1.1 or 8.8.8.8 for CloudFlare's or Google's DNS. Also `homeassistant` is the name of the docker container, adjust if needed.
