### ISSUE TITLE
Full snapshot backup not including several files and folders in the config directory

### ISSUE THREAD

**Issue by Teri928** [home-assistant/hassio#452]
I found myself needing to use a Hassio snapshot to recover a yaml file that was accidentally deleted from the config directory only to find that Hassio's "full" snapshot didn't actually include a copy of this file. Then on further inspection, the snapshots are not backing up several folders and files. Is there a way to control what folders on the SD card and config directory Hassio actually backs up or actually ensure that ALL folders and files are actually backed up?
I'm on 0.67.1

**Comment by pvizeli** [comment]
Any snapshot of home-assistant config folder include all data. That work only, if you don't mess up the permissions. Do you have restore the data and it was the old one? Inside logs he should print all errors after a snapshot are done.

I see that 7-zip have some problem with read the tarfile they we generate with tarfile in python.

**Comment by sdrasmussen** [comment]
I noticed that when I restored a "full" snapshot this evening, the restore did not restore all of my third party addons, NOR did it restore the 3rd party repositories I had added to my install.  Just reporting.  Thanks.

**Comment by matisaul** [comment]
Same problem here. Sometimes, some yaml files are not included in full backup, or the "homeassistant" option in folder backup is not saved in json file.
