### ISSUE TITLE
Issue with Worx Landroid

### ISSUE THREAD

**Issue by Klangen82** [home-assistant/hassio#455]
Hassio 0.68.0 running on a Rasp pi3 and Worx WG796E.1 Firmware 2.66

Issue with sensor "worxlandroid-state" https://www.home-assistant.io/components/sensor.worxlandroid/

Link to the forum with the issue: [Worx alwasy mowing](https://community.home-assistant.io/t/worx-alwasy-mowing)

The issue is that the "worxlandroid-state" sensor never change from anything else than "mowing"

What I have in my configuration.yaml
``` 
- platform: worxlandroid
    host: 192.168.5.13
    pin: XXXX
```
Cannot find any error messages in the log. Have been running older Hassio versions and older Worx FW, but it has never worked. Battery sensor is working fine so the communication is ok.

The mower is changing when I took the image snapshot but the sensor indicates that its mowing. When I look into the Worx ios application I can see that the unit is changing.
![image](https://user-images.githubusercontent.com/25564168/39437576-900dc330-4ca1-11e8-859f-b6bc9bca8c57.png)

Below image you see that the battery indicator works like it should.
![image](https://user-images.githubusercontent.com/25564168/39437596-9b57a972-4ca1-11e8-9f04-bad042ec40ec.png)

**Comment by markusdahlgren** [comment]
Hi, I have the same issue. I have make a try to fix this.

I have made it to 3 sensors, battery, state and error. 

This is my first time I have made a sensor or change something.. Maybe this will work, maybe not... 

add my file in "custom_component/sensor/" and add in configuration.yaml like you have byt change platform-name to same as the file, but without ".py".. 

[worxlandroid2.zip](https://github.com/home-assistant/hassio/files/2065921/worxlandroid2.zip)

I have not test all fails and states of Landroid.. 

**Sensor-names will be:**
sensor.worxlandroid2state
sensor.worxlandroid2error
sensor.worxlandroid2battery

**Comment by Klangen82** [comment]
Thanks man!

I have added it and let you know if I will find any bugs etc.

**Comment by markusdahlgren** [comment]
I have made some changes. I read little more about how hassio works and if a file in custom_component folder exist it override "original" file when loading.. So no need to change anything in configuration.yaml, just paste file in custom_component/sensor/ with 'worxlandroid.py' as name.. 

[worxlandroid.zip](https://github.com/home-assistant/hassio/files/2075559/worxlandroid.zip)

Things I change..
* changed sensor.name and friendly name at once (same name but friendly name have "WorxLandroid - battery" thats why it is "__" in sensor name, bad/good ? please return to me..)
   * sensor.worxlandroid__battery
   * sensor.worxlandroid__state
   * sensor.worxlandroid__error
   * sensor.worxlandroid__batterychargerstate
* One mor sensor, battery charging status. 
* Add icons as default, guess it is possible to change to own with customize.yaml.. 
* Different icon for battery level. full / 80% / 60% / 40% / 20%.. 

Things I try to solve:
- [ ] Error handling, now it only shows error message before Landroid auto turn off.. Then it shows "no"
- [ ] Error icon, to highlight it when error, maybe impossible without custom_ui.. 

I am a newbie in Github. If I want to push my changes to official file, is it possible ? if it, how ?

**Comment by markusdahlgren** [comment]
https://github.com/home-assistant/home-assistant/pull/14840

**Comment by JakobTewes** [comment]
This is not closed. Code was not merged.
