### ISSUE TITLE
No color logs after 0.68.1 update

### ISSUE THREAD

**Issue by ghost** [home-assistant/hassio#458]
Hi!
I've updated from 0.67.1 to 0.68.1. Now `hassio ha logs` command outputs logs without coloring (red errors, yellow warnings, etc). What could be wrong? Help command for `hassio ha` shows no options for colorful output.

**Comment by frenck** [comment]
The hassio commandline support log coloring, as long as the application delivers it.

`hassio su logs`:

![image](https://user-images.githubusercontent.com/195327/56079319-2161bb80-5df3-11e9-8079-6a8970a7febc.png)

Closing issue.
