### ISSUE TITLE
Google Assistant Add-On stops automatically without logs

### ISSUE THREAD

**Issue by sabaatworld** [home-assistant/hassio#462]
I have installed Hassio on a RPi Zero W. I have installed the Google Assistant Add-On but I'm unable to start it. It stop automatically soon after I start it. Also there are no logs show (even after refresh several times).

My hardware:
```
Hardware
serial:
/dev/ttyAMA0
input:
Microsoft Microsoft® Nano Transceiver v2.0
disk:
gpio:
gpiochip0
audio:
0:
name: bcm2835 - bcm2835 ALSA
type: ALSA
devices:
0: digital audio playback
1: digital audio playback
```

Add-on configuration:
```
{
  "mic": "0,0",
  "speaker": "1,0",
  "client_secrets": "google_assistant.json"
}
```

**Note:** I have already added the JSON file under the shared SMB share

**Comment by pvizeli** [comment]
I will update it 👍

**Comment by sabaatworld** [comment]
Have you fixed the issue in the add on?
