### ISSUE TITLE
Weak use of SSL ciphers

### ISSUE THREAD

**Issue by brentil** [home-assistant/hassio#470]
If you scan a Hassio installation with a vulnerability scanner like Tenable's Nessus or Alienvault OSSIM they find that the built in web server when in HTTPS on 8123 and SSH on 22222 are using weak ciphers.  I've noticed these since I've started running Hassio (.54) on my network so they've existed for a while.

RasPi 3
Hassio .68.1
Hass.io supervisor 103.3
Host System Resin OS 2.3.0+rev1

Nessus Plugin 42873

> # **SSL Medium Strength Cipher Suites Supported**
> **Description**
> The remote host supports the use of SSL ciphers that offer medium strength encryption. Nessus regards medium strength as any encryption that uses key lengths at least 64 bits and less than 112 bits, or else that uses the 3DES encryption suite.
> 
> Note that it is considerably easier to circumvent medium strength encryption if the attacker is on the same physical network.
> **Solution**
> Reconfigure the affected application if possible to avoid use of medium strength ciphers.
> **See Also**
> https://www.openssl.org/blog/blog/2016/08/24/sweet32/
> **Output**
> Here is the list of medium strength SSL ciphers supported by the remote server :
> 
>   Medium Strength Ciphers (> 64-bit and < 112-bit key, or 3DES)
> 
>     ECDHE-RSA-DES-CBC3-SHA       Kx=ECDH        Au=RSA      Enc=3DES-CBC(168)        Mac=SHA1   
>     DES-CBC3-SHA                 Kx=RSA         Au=RSA      Enc=3DES-CBC(168)        Mac=SHA1   
> 
> The fields above are :
> 
>     {OpenSSL ciphername}
>     Kx={key exchange}
>     Au={authentication}
>     Enc={symmetric encryption method}
>     Mac={message authentication code}
>     {export flag}
> **Port**
> 8123 / tcp / possible_wls

Nessus Plugin 70658

> # **SSH Server CBC Mode Ciphers Enabled**
> **Description**
> The SSH server is configured to support Cipher Block Chaining (CBC) encryption. This may allow an attacker to recover the plaintext message from the ciphertext. 
> 
> Note that this plugin only checks for the options of the SSH server and does not check for vulnerable software versions.
> **Solution**
> Contact the vendor or consult product documentation to disable CBC mode cipher encryption, and enable CTR or GCM cipher mode encryption.
> **Output**
> The following client-to-server Cipher Block Chaining (CBC) algorithms
> are supported : 
> 
>     3des-cbc
>     aes128-cbc
>     aes256-cbc
>     twofish-cbc
>     twofish128-cbc
>     twofish256-cbc
> 
> The following server-to-client Cipher Block Chaining (CBC) algorithms
> are supported : 
> 
>     3des-cbc
>     aes128-cbc
>     aes256-cbc
>     twofish-cbc
>     twofish128-cbc
>     twofish256-cbc
> **Port**
> 22222 / tcp / ssh

Nessus Plugin 71049

> # **SSH Weak MAC Algorithms Enabled**
> **Description**
> The remote SSH server is configured to allow either MD5 or 96-bit MAC algorithms, both of which are considered weak.
> 
> Note that this plugin only checks for the options of the SSH server, and it does not check for vulnerable software versions.
> **Solution**
> Contact the vendor or consult product documentation to disable MD5 and 96-bit MAC algorithms.
> **Output**
> The following client-to-server Message Authentication Code (MAC) algorithms
> are supported : 
> 
>     hmac-md5
>     hmac-sha1-96
> 
> The following server-to-client Message Authentication Code (MAC) algorithms
> are supported : 
> 
>     hmac-md5
>     hmac-sha1-96
> **Port**
> 22222 / tcp / ssh

**Comment by fabaff** [comment]
The SSL cipher issue looks like a false-positive. SSL/TLS is not activated by default. Can be verified with something like:

```bash
$ openssl s_client -connect hassio.local:8123
```

The SSH daemon behind port 22222 is for debugging only and needs additional work to allow logins. Only developers will use that as the SSH feature for the users is provided with an Add-on. The Add-on enables the SSH daemon with similar setting and this should be hardened.

**Comment by brentil** [comment]
Being a developer only interface still doesn't mean it shouldn't be using strong ciphers.  Especially if something is ever accidentally configured wrong or is being used by a developer.

It's not on by default but you can enable it which I've done.  Once that's enabled it exposes the weak ciphers.  The Remote Access documentation for example recommends you enable it when accessing your HA over the internet.  Using sslscan against my running instance exposes the full cipher list once enabled which does include the weaker ones listed above.

> TLS Fallback SCSV:
> Server supports TLS Fallback SCSV
> 
> TLS renegotiation:
> Secure session renegotiation supported
> 
> TLS Compression:
> Compression disabled
> 
> Heartbleed:
> TLS 1.2 not vulnerable to heartbleed
> TLS 1.1 not vulnerable to heartbleed
> TLS 1.0 not vulnerable to heartbleed
> 
> Supported Server Cipher(s):
> Preferred TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256
> Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
> Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve P-256 DHE 256
> Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256
> Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
> Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
> **Accepted  TLSv1.2  112 bits  ECDHE-RSA-DES-CBC3-SHA        Curve P-256 DHE 256**
> Accepted  TLSv1.2  128 bits  AES128-GCM-SHA256
> Accepted  TLSv1.2  256 bits  AES256-GCM-SHA384
> Accepted  TLSv1.2  128 bits  AES128-SHA256
> Accepted  TLSv1.2  256 bits  AES256-SHA256
> Accepted  TLSv1.2  128 bits  AES128-SHA
> Accepted  TLSv1.2  256 bits  AES256-SHA
> **Accepted  TLSv1.2  112 bits  DES-CBC3-SHA**
> Preferred TLSv1.1  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
> Accepted  TLSv1.1  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
> **Accepted  TLSv1.1  112 bits  ECDHE-RSA-DES-CBC3-SHA        Curve P-256 DHE 256**
> Accepted  TLSv1.1  128 bits  AES128-SHA
> Accepted  TLSv1.1  256 bits  AES256-SHA
> **Accepted  TLSv1.1  112 bits  DES-CBC3-SHA**
> Preferred TLSv1.0  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
> Accepted  TLSv1.0  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
> **Accepted  TLSv1.0  112 bits  ECDHE-RSA-DES-CBC3-SHA        Curve P-256 DHE 256**
> Accepted  TLSv1.0  128 bits  AES128-SHA
> Accepted  TLSv1.0  256 bits  AES256-SHA
> **Accepted  TLSv1.0  112 bits  DES-CBC3-SHA**

**Comment by fabaff** [comment]
We are following the recommendations made by Mozilla's Operations Security team for the Server side SSL/TLS settings. Users will access their Home Assistant with whatever client they have at hand. This forces us to support recent clients, legacy clients and especially devices like micro controller which have no support for AES.

**Comment by frenck** [comment]
Since there was no response at all, I'm declaring this stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.
