### ISSUE TITLE
Can't build dependencies with native code

### ISSUE THREAD

**Issue by jkeljo** [home-assistant/hassio#471]
I'm working on a new built-in component for Home Assistant, and one of its dependencies is the `netifaces` module, which has some C code in it. Loading the component as a custom component into Hass.io fails to build that module, I think because Hass.io is missing things like `gcc`, `python3-dev`, and `libc-dev`. I was able to work around for testing by `apk add`ing those items in the ssh add-on and manually `pip3 install`ing `netifaces` to `/config/deps`. However, f I want my component to be built-in, Hass.io needs to be able to build its dependencies.

Would you accept a change (presumably in hassio-build) that adds the necessary things to the Docker image, or is there some other way that I should solve this problem?

Thanks in advance for your advice.

**Comment by pvizeli** [comment]
Use https://github.com/home-assistant/hassio-addons/tree/master/custom_deps for you custom component. After it is in upstream it will be build automatic correct with all the other components.
