### ISSUE TITLE
In/Out devices in audio cards not detected

### ISSUE THREAD

**Issue by vicfergar** [home-assistant/hassio#472]
I'm using a USB card in my Raspberry Pi3 running hassio. This cards has 2 devices within the same id:

![image](https://user-images.githubusercontent.com/6979979/39935035-fe1c8024-5547-11e8-8778-64431d513ac4.png)

The current hardware.py overrides the audio playback device (1,0) with the audio capture one (also 1,0), so audio playback cannot be used from Hass.io:

![image](https://user-images.githubusercontent.com/6979979/39934997-df34a2ae-5547-11e8-8c63-d7eaf88f8acc.png)

**Comment by pvizeli** [comment]
How would be handle that with alsa? You can use the same channel for input/output on same time?

**Comment by vicfergar** [comment]
Yes. I suppose it is possible because I was using this same channel in first version of the Google Assistant add-on without problems :)

**Comment by pvizeli** [comment]
Ok, we need convert it from a dict into a `attr` object as list and we can handle this case, that we not can use channel numbers.

**Comment by vicfergar** [comment]
Nice! If I can check it please let me know how to do it.

**Comment by vicfergar** [comment]
Hi again!

Where can I locate this file in my local hassio installation? I would like to propose a PR fixing this issue, but I need to test it before. Thanks!

**Comment by vicfergar** [comment]
It is very important for me, I cannot use Google Assistant add-on anymore. Can someone help me please? 😊

**Comment by vicfergar** [comment]
Please help me!! 😶

**Comment by vicfergar** [comment]
Nothing new? It would be great to have support to it :)

**Comment by frenck** [comment]
I've been able to reproduce this on Vagrant as well.

```txt
$ cat /proc/asound/devices
  1:        : sequencer
  2: [ 0]   : control
  3: [ 0- 0]: digital audio playback
  4: [ 0- 0]: digital audio capture
  5: [ 0- 1]: digital audio playback
  6: [ 0- 1]: digital audio capture
  7: [ 0- 2]: digital audio capture
  8: [ 0- 0]: hardware dependent
 33:        : timer
```

As a result (with the above), I only have capture devices available.

**Comment by luca-simonetti** [comment]
Hi! we're having exactly the same issue! Is there any update on this? It's wuite vital for us this to be working ASAP

**Comment by pvizeli** [comment]
We need convert the format into object with attr. Not very difficult, but need some one with time

**Comment by luca-simonetti** [comment]
can you give me an hint on what file needs to be changed? So that we can give it a try at least

**Comment by luca-simonetti** [comment]
> I think that the file to be changed is [this](https://github.com/home-assistant/hassio/blob/dev/hassio/misc/hardware.py) and probably [this one](https://github.com/home-assistant/hassio/blob/267791833e95f84ec1b52cd10f6f50dbfa39c027/hassio/host/alsa.py) too.

yes, I actually made a PR already before you commented, hopefully this will be accepted ASAP and an update may be pushed as an hotfix? I really hope so

**Comment by luca-simonetti** [comment]
@pvizeli sorry to insist, did you have any chance to take a look at the PR I pushed few days ago? Looks like it's a really small thing and it shouldn't break anything else (that specific part ain't being used anywhere else). It'd be great to have it working soon

**Comment by luca-simonetti** [comment]
any news? I mean at least to know if it has even been considered or something. This is very crucial for us and I want to understand wether we need to fork and build our custom version or we can rely on you.

**Comment by luca-simonetti** [comment]
looks like my contribute is working fine, I successfully tested with two usb cards.
Keep in mind that you'll need a full reboot hassio to see the cards correctly in the google assistant config.
After saving the correct input and output you'll also need to reload the addon.
But it's definitely working!!!

**Comment by pvizeli** [comment]
Good work 👍 
I need a bit refactor the code to detect the correct names now on supported device, but that is only a minor fix.
