### ISSUE TITLE
Py_Initialize: can't import _frozen_importlib

### ISSUE THREAD

**Issue by 9guiajkbk2** [home-assistant/hassio#474]
After updating Home assistant to version 0.69.0, I get the following error when trying to run and checking Home Assistant:

`Fatal Python error: Py_Initialize: can't import _frozen_importlib
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 48, in <module>
TypeError: descriptor '' requires a 'type' object but received a 'str'`

I am running Hassio. hassio ha info:
```
{
    "result": "ok",
    "data": {
        "version": "0.69.0",
        "last_version": "0.69.0",
        "machine": "raspberrypi3",
        "image": "homeassistant/raspberrypi3-homeassistant",
        "custom": false,
        "boot": true,
        "port": 8123,
        "ssl": true,
        "watchdog": true,
        "wait_boot": 600
    }
}
```

**Comment by 9guiajkbk2** [comment]
Thanks. I reinstalled Hassio, and it's no longer an issue.

**Comment by frenck** [comment]
🎉
