### ISSUE TITLE
Configuration error with MySensors

### ISSUE THREAD

**Issue by peerv** [home-assistant/hassio#478]
I am now at 0.69.1 HASS on Rpi and still having configuration check problem.

This is my configuration:

mysensors:
  gateways:
    - device: '/dev/ttyUSB0'
      persistence_file: '/config/mysensors.json'
      baud_rate: 115200
  optimistic: false
  persistence: true
  retain: true
  version: '2.0'

And this is the configuration check ERROR:

core-ssh:~# hassio ha check
ERROR
starting version 3.2.4
Testing configuration at /config
Failed config
  mysensors:
    - Invalid config for [mysensors]: /config directory does not exist or is not writeable for dictionary value @ data['mysensors']['gateways'][0]['persistence_ file']. Got /config/mysensors.json'
not a valid value for dictionary value @ data['mysensors']['gateways'][0]['device'].
Got '/dev/ttyUSB0'. (See /config/configuration.yaml, line 85). Please check the docs at https://home-assistant.io/components/mysensors/

A secondary result of this error is the restarting the Rpi does NOT load a new configuration!
The only way to load a new configuration file is to power off/on the Rpi.

However all the rest seems to funtion well !?

**Comment by davidhrbaty** [comment]
Hello,

I'm now at 0.71.0  Hassio on RPI and I have the same problem. If I changed the persistence file to pickle file, everything is all right, but I want to use json as a persistence file for mysensors plugin.
Via WEB Configuration validation is everything all right, but it is impossible to restart HA.There is a configuration error check via ssh addon shown below:

`core-ssh:/# hassio ha check
ERROR
Testing configuration at /config
Failed config
  mysensors: 
    - Invalid config for [mysensors]: /config directory does not exist or is not writeable for dictionary value @ data['mysensors']['gateways'][0]['persistence_file']. Got 'mysensors1.json'. (See /config/configuration.yaml, line 98). Please check the docs at https://home-assistant.io/components/mysensors/`

If you have any questions,or you need debug logs, feel free to ask. Thank you.

**Comment by gervaso** [comment]
Hello,
same issue here, I've tried with both absolute and relative paths and naming the files both ".json" and ".pickle". The annoyances are the same already reported, basically it's not possible to restart HA without restarting the whole hass.io thing (the whole resinos on rpi in my case).

Here's the relevant config section:
```yaml
# MySensors hub support
mysensors:
  gateways:
    - device: '10.80.80.3'
      persistence_file: '/config/mysensors.json'
      tcp_port: 5003
  version: '2.0'
```

**Comment by innesleroux** [comment]
Hi,

I am also in the same boat, hass.io 0.71.0 running on a Pi3 and mysensors.

I am using an Arduino Nano and RF24L01 as the serial gateway connected to the PI via usb (/dev/ttyUSB0).

The normal hassio ha check fails stating that /dev/ttyUSB0 is incorrect but that is indeed the correct port.

A hassio hw info confirms and it disappears when the Nano is unplugged, so port setting is correct.

It looks to me that the USB is not passed through to and from the Docker instance but editing the group file and adding dialout is not persistant as it lives inside the docker container.

It seems from various posts that hassbian is the answer but I have been running hassio for many months and everything else works (all mqtt, sensors, WOL, Sonoffs etc )

I have a specific requirement for Mysensors and it was also updated to version 2.3 on 18 June, so the project is alive and well.

The sensors and gateway do communicate when doing a serial dump from the Arduino IDE. (obviously disconnected from the Pi/ hassio). There is just no communication to and from the gateway to the PI

Please help!!

**Comment by pvizeli** [comment]
That is only a problem with `hassio ha check`. If you call `hassio ha restart` it do what you want.
I will fix the problem if the check command support also devices.
