### ISSUE TITLE
Cannot reboot hassio 1.3.0

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/hassio#484]
I'm getting the following error:
```
core-ssh:~# hassio host reboot
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2c7050, 0x107c8200)
	/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x33c
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x107fe000, 0x24, 0x200, 0x0)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x3c8
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x2f45fc, 0x4, 0x7e95ee5b, 0x6, 0x0, 0x0, 0x76500, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x308
github.com/home-assistant/hassio-cli/command.CmdHost(0x10786420)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/host.go:42 +0x4f0
github.com/urfave/cli.HandleAction(0x2af768, 0x324b18, 0x10786420, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0xf0
github.com/urfave/cli.Command.Run(0x2f45fc, 0x4, 0x0, 0x0, 0x40bd20, 0x1, 0x1, 0x2fabdf, 0x18, 0x0, ...)
	/home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x6b8
github.com/urfave/cli.(*App).Run(0x107b2380, 0x1070a160, 0x3, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x8b0
main.main()
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +
```
In earlier hassio I had no problem with this command

**Comment by pvizeli** [comment]
Do you can reboot over the UI?

**Comment by sumitrajancse** [comment]
I also have the same problem... UI does not even open.. 
When restart it manually the rpi, it worked for 5-10 mins, then again hangs... This problem is presented after the new update.

**Comment by sumitrajancse** [comment]
Can you advise a way how can I rollback to older version ?

**Comment by robmarkcole** [comment]
@pvizeli I can restart HA, but not reboot the PI from the UI (unless there's another menu?)

![image](https://user-images.githubusercontent.com/11855322/40683163-97afcc8c-6385-11e8-8178-01430b0901ec.png)

**Comment by rogersmj** [comment]
Same symptoms here. Same kernel panic when attempting to restart from CLI, no host reboot buttons in the UI.

**Comment by pvizeli** [comment]
The Problem is, that you host don't support dbus and we use now dbus to control the host.
The CLI don't respect this and that is a bug. I fix that in next verson.

If your host support dbus, you can rerun the installer and all things work like before.

**Comment by Pre10der** [comment]
Same issue here. This is on a RaspberryPi 3 running HASSIO 0.72.1.

**Comment by frenck** [comment]
On a generic Linux / Manual installation, this is fixable by running these commands:

https://gist.github.com/frenck/32b4f74919ca6b95b30c66f85976ec58

In the case of @Pre10der (assuming you are running the download image / ResinOS), I'm not sure.

**Comment by techionltd** [comment]
Ditto here. Following a power fail, the Pi3 starts up faster than the router re-establishes internet connectivity. Samba and SSH are available on hassio, but UI is unavailable locally and via duckdns. Also, duckdns does not get refreshed IP address and UI is unavailable until Pi is rebooted again with internet already connected

**Comment by pvizeli** [comment]
You can install HassOS :)

**Comment by frenck** [comment]
This issue can be resolved.

- Generic Linux installations: Run the generic installer again, this will update profiles. Also be sure to check if you have all requirements and dependencies installed on the host system.

- ResinOS installations: Upgrade to HassOS
