### ISSUE TITLE
Duckdns is not working any more for me

### ISSUE THREAD

**Issue by sdrasmussen** [home-assistant/hassio#505]
I have been running DuckDNS for a while, and it has been working fine.  However, recently, I upgraded from RPi3 to Ubuntu 18.04.  I restored from a snapshot, and everything is working fine except this.  I have uninstalled and reinstalled both DuckDNS and LetsEncrypt.  No joy.  Basically, it looks like I am having some sort of resolution problem  One more piece of the puzzle; I am running Pihole.  However, from the CLI of my server, I can resolve the domain in question just fine.  Any, here is the error I am getting from LetsEncrypt:

starting version 3.2.4
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
An unexpected error occurred:
ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0da0d78550>: Failed to establish a new connection: [Errno -3] Try again',))
Please see the logfiles in /var/log/letsencrypt for more details.

Here is the error I am getting from DuckDNS:

starting version 3.2.4
# INFO: Using main config file /data/workdir/config
ERROR: Problem connecting to server (get for https://acme-v02.api.letsencrypt.org/directory; curl returned with 6)

As I said, from the CLI, I can resolve acme-V0#.api.letsencrypt.org just fine.  Suggestions?

**Comment by pvizeli** [comment]
Fix with last version?
