### ISSUE TITLE
Unable to load the panel source: /api/hassio/app/entrypoint.js.

### ISSUE THREAD

**Issue by andlo** [home-assistant/hassio#510]
After last update I get this when going to hass.io panel: "Unable to load the panel source: /api/hassio/app/entrypoint.js."
I am on the beta channel, and now I dont know how to get back to normal channel….

**Comment by andlo** [comment]
Downgrading- I figured out 
`hassio ha update -o version=0.70.0`

**Comment by c727** [comment]
hassio ha update -o version=0.72.0b4

**Comment by be-engineer** [comment]
when I use command"hassio ha update -o version=0.99.2"
it returned
hassio: command not found
what can I do then?
