### ISSUE TITLE
Update kernel to at least 4.14

### ISSUE THREAD

**Issue by metbril** [home-assistant/hassio#540]
This will enable the use of file

    /sys/devices/platform/soc/soc:firmware/get_throttled

that makes it possible to work around the lack of `vcgencmd get_throttled` being available.

In turn, that will enable us to create a (command line) sensor to test for bad Pi chargers

https://community.home-assistant.io/t/raspberry-pi-charger-sensor/58155

The PR that created this kernel feature:

https://github.com/raspberrypi/linux/pull/2397

**Comment by pvizeli** [comment]
HassOS is on 4.14
The support for resinos will be shutdown now. If you need kernel 4.14 use HassOS.

On Add-on, you can use `gpio: true` they give also access to that feature.

**Comment by metbril** [comment]
> On Add-on, you can use gpio: true they give also access to that feature.

What add-on do you refer to?

**Comment by frenck** [comment]
@metbril He does not refer to any specific add-on, he is referring to an add-on capability a developer could use.
