### ISSUE TITLE
Hass.io add-on auto start on boot, after install.

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio#541]
This is kinda a security concern in my point of view, and total unexpected behaviour...

I did install a fresh installation of my production system, which went fine. I installed all add-on which I'd wanted to use, but did NOT start them, since I would still need to configure them.

During this whole setup process, I've rebooted my machine. After the boot, all installed add-ons where started! Running their default config...

That was unexpected...

# Proposal

The add-on must be started at least once, before the auto-start feature kicks in.

**Comment by pvizeli** [comment]
Yeah, I'm fine with that and accept PRs for that 👍
