### ISSUE TITLE
Boot homeassistant dependency issue

### ISSUE THREAD

**Issue by andyinno** [home-assistant/hassio#562]
It just appened twice, never happened before in one year with the same setup.

I have an hassio installation with:
 
- pi-hole
- mosquitto

Addons installed.
I had to reboot the pi and when it went up again I saw in the web panel that a lot of my sensors, connections failed.
I restarted home assistant and everything was up and running.

It was the first time it happened. I tryed to reboot the pi again for seeing if the same happened again and yes. It happened again.
I removed the pi-hole add on for testing, reboot and it happened again with all the mqtt things.

It looks like hass container starts before, or get ready before, the others container with the server side third parties I use.
It means that I was lucky in the past having the same software starting correctly?

There is some way for verifying that the containers starts in a predefined order and change it pushing mqtt before hass?

I mean... if it is a random startup there is a high possibility to hit a wrong order.
What if there is a power failure, an unexpected reboot, and then the system goes up again? 
There is a possibility that hass / homeassistant must be restarted by hand because of a wrong startup order?

I don't know if this is the right place for writing this. 
I see two point of failure, one is this. Hassio could be able to prioritize by hand, or by code that one container is up before starting another one?
Or is the home assistant "startup" that needs to see all the single parts connected? If the network provider needs more time than expected for any reason and home assistant finish powering up it display the error message and there is no way for trying another connection / try again to initialize the module. The only possible thing to do is restart the container.

If it power up in the right order, everything works as expected. 
But if something is out of order a restart of the single container is needed for being fully operational again.

**Comment by andyinno** [comment]
Hi @pvizeli 

thank you for your reply.
It is, anyhow, someway obscure to me. Can you please describe where I have to act?
From the hassio panel on home assistant web interface?

**Comment by frenck** [comment]
@andyinno Manually, via the Hassio API is currently the only way.
Since this issue is stale for a while now, is this still a problem for you?

**Comment by andyinno** [comment]
Hi @frenck 
Telling the truth? I was not able to fix the issue, I "resolved" by installing pi-hole on another pi I had half used. After an host update mosquitto started without errors and now after a reboot it starts correctly.

For me the issue is closed
