### ISSUE TITLE
Snapshot restore missing lots of data

### ISSUE THREAD

**Issue by ndarilek** [home-assistant/hassio#566]
I just took a partial snapshot of my Hass.io installation. Unfortunately, while the snapshot appears to contain everything I wanted, restoring it:
 * did not restore my custom repositories. I see them in the snapshot.json.
 * Did not restore my local addons, nor did it restore any addons from the non-stock repositories. Yes, I checked everything I wanted to restore in the UI, and those things were definitely not restored.

Logs of the restore:

```
18-07-11 17:03:34 INFO (MainThread) [hassio.snapshots] Partial-Restore 31e7f803 start
18-07-11 17:03:55 INFO (MainThread) [hassio.snapshots] Restore 31e7f803 run folders
18-07-11 17:03:55 INFO (SyncWorker_3) [hassio.snapshots.snapshot] Restore folder ssl
18-07-11 17:03:55 INFO (SyncWorker_3) [hassio.snapshots.snapshot] Restore folder ssl done
18-07-11 17:03:55 INFO (SyncWorker_18) [hassio.snapshots.snapshot] Restore folder addons/local
18-07-11 17:03:56 INFO (SyncWorker_18) [hassio.snapshots.snapshot] Restore folder addons/local done
18-07-11 17:03:56 WARNING (MainThread) [hassio.snapshots] Can't restore addon 31e7f803
18-07-11 17:03:56 WARNING (MainThread) [hassio.snapshots] Can't restore addon 31e7f803
18-07-11 17:03:56 WARNING (MainThread) [hassio.snapshots] Can't restore addon 31e7f803
18-07-11 17:03:56 WARNING (MainThread) [hassio.snapshots] Can't restore addon 31e7f803
18-07-11 17:03:56 WARNING (MainThread) [hassio.snapshots] Can't restore addon 31e7f803
18-07-11 17:04:09 INFO (MainThread) [hassio.snapshots] Partial-Restore 31e7f803 done
```

I really don't like that, when something fails on Hass.io, the logs are either a) absent or b) entirely unhelpful, and there's no way to reach under the hood as an expert and just remove the stuck Docker container or whatever. How do I debug this? I reinstalled because #418 was preventing me from starting an addon, and now I can't restore the snapshot I spent days setting up. Which addons are failing to install here and why? The hex digits appear to be the backup slug, which I don't know why I'd care about when what I need in this log message is the addon that won't restore, but even more helpful would be why it isn't restoring.

Thanks.

**Comment by ndarilek** [comment]
OK, had a bit more luck with this. I restored another backup that knocked my Pi completely offline. So I started fresh, then copied the same snapshot that failed to restore earlier. Since my initial restore failed to add third-party repositories, even when I performed the restore again, and even though the repo URLs are in the snapshot.json, I wondered what would happen if I manually added the repo URLs and tried the restore again.

Now it seems to be working.

I don't want to definitively say this was the issue, but the broken restore left me with only core addons running, and those core addons came from a repo baked into the image. Maybe the restore process needs to ensure that the repos are populated, and do so before trying to restore the actual images?

**Comment by pvizeli** [comment]
Can I have a snapshot file that not work?

**Comment by ndarilek** [comment]
Sure. How do I scrub it for sensitive details? I've seen a couple 
instances of my passwords in the backup.

Also, as an update, I spoke too soon. Not all items restored even in the 
second round.

Thanks.

**Comment by pvizeli** [comment]
You can send me a PM

**Comment by ndarilek** [comment]
Just emailed a link to the broken backup to the email on your profile.

Thanks!

**Comment by almostserious** [comment]
I observe the same behaviour... all of the custom repositories are not restored. Neither the addons, nor the repositories itself.

**Comment by ndarilek** [comment]
Does HassOS use the same restore mechanism? I'd like to upgrade, but I'm worried that my backup won't be restored, and I hope this issue doesn't slip through the cracks if it is only relevant to the previous images. I'm OK with it not being fixed if Hass.io is being deprecated, but I hope it isn't present in HassOS too.

**Comment by ndarilek** [comment]
GOt it. Well, the snapshot definitely has everything in it. It just 
doesn't restore.

Thanks.
