### ISSUE TITLE
RPi 3B+ installation issue

### ISSUE THREAD

**Issue by swefse** [home-assistant/hassio#567]
Am having issues installing the new HASS.io on 3B+.

Boots up fine and can see it on network from Fing, but attempts to connect to pi_IP:8123 fail with "connection refused" error.

How can I troubleshoot this?

**Comment by GrandNewbien** [comment]
I've been having the same problem on Hassbian. I was able to use it for a while.

It appears they recently added support for the B+, or at least took the warning away.

**Comment by pvizeli** [comment]
If that is a HassOS problem, please open there a new Issue. Thanks
