### ISSUE TITLE
Support for bluetooth dongle

### ISSUE THREAD

**Issue by kurteknikk** [home-assistant/hassio#572]
I run hassio on a raspberry pi 2B and it has no builtin bluetooth. I read that on hassio only the builtin bluetooth works.

Is there any specific reason for this ? Are there plans to also support bluetooth dongles ? Or can i maybe install something manually to get this to work ?

**Comment by pvizeli** [comment]
We support all that stuff they is supported by raspbian kernel. Feel free to join into HassOS and provide a PR with optional module.

**Comment by kurteknikk** [comment]
At least i know the reason now. I will have a look at HassOS because i haven't looked into that yet and maybe submit a PR, thanks.
