### ISSUE TITLE
Google Maps Location Sharing Device tracker (locationsharinglib) not updating HA

### ISSUE THREAD

**Issue by v966732** [home-assistant/hassio#574]
https://www.home-assistant.io/components/device_tracker.google_maps/

I’m seeing an issue with the Google maps device tracker element, it worked for a few days and has now stopped updating.

When I run a debug on device_tracker and locationsharinglib I can see in the logs that it is pulling back the updated GPS location for each user but is not populating it into homeassistant. The device state just shows as Null. In the logs I’m seeing locationsharinglib.service retrieve the data for each user I’m tracking (checked the timestamps and it is not historical data it is live) and then the next entry is locationsharinglib.Service Could not load people, response

This is not the issue with the cookies file or a captcha issue, the data is being successfully pulled from google to my HA.

I am currently running HASSIO 0.73.2 but I have also seen this issue on Docker Home-Assistant run as a VM on my QNAP NAS.

My configuration.yaml entries are as follows:-

**device_tracker:
  - platform: google_maps
    username: !secret device_tracker_gmail
    password: !secret device_tracker_gmail_password
    scan_interval: 300
    new_device_defaults:
      track_new_devices: true**

**Comment by AJStubbsy** [comment]
Any update on this? I'm having the same problem.

**Comment by v966732** [comment]
I think I may have resolved the issue by following the information detailed here:-
https://community.home-assistant.io/t/google-maps-location-sharing-new-thread/54555/72 

It's caused by the Google data being returned incomplete for one of the users you are tracking, this could be because the device has been switched off for a while or that the device has stopped sharing location with you.

If you follow the link and then you'll need to recreate the locationsharinglib file to include the fixes mentioned in jedi7's pul request of locationsharinglib

Mine has been working again for the last few days so hopefully this is the permanent fix

**Comment by AJStubbsy** [comment]
Thank you for pointing me towards this! Can you tell me the path for the locationsharinglib file please?

**Comment by SteveDinn** [comment]
I'm curious if this is still resolved for you. The behaviour I've seen is that the google login cookies in .google_maps_location_sharing.cookies expire after ~14 days, and then all my tracked devices always show "Home' regardless of where they actually are. 

I feel like this component should automatically refresh its login when it expires. Currently, I am forced to manually delete the .google_maps_location_sharing.cookies file and restart home assistant every two weeks to keep things up and running.

**Comment by AJStubbsy** [comment]
@SteveDinn  I've been checking this for a fortnight because I recently had to rebuild my Home Assistant image. It's been ~15 days today and my tracked devices is working correctly. I think my original problem was caused because my wife's phone decided not to share its location, which resulted in the cookie file not being updated in hass. I cancelled all the location sharing, deleted the cookie file and then shared location again, making sure to log in to google and accept the security settings. Since then its been fine. Hopefully redoing everything will sort it for you too

**Comment by frenck** [comment]
I'm closing this issue.
While (maybe) still relevant (not totally clear from the conversion).
The fact is that this issue should have been raised against the https://github.com/home-assistant/home-assistant repository.

If you are still experiencing issues with this, please feel free to open an issue there.
