### ISSUE TITLE
Missing container after installing Hass.io on an Orange Pi Zero

### ISSUE THREAD

**Issue by albertogonzalez** [home-assistant/hassio#590]
Please, let me say first that I have no issues installing Hassbian on my Orange Pi Zero but I haven't been able to install Hass.io and make it run and up yet. 
I have tried with Ubuntu_bionic_next_4.17.7 and with Debian_stretch_next_4.14.14 with the same result.
After installing all required dependencies I install docker-ce (I've tried to install it using the convenience script and manually through apt-get install docker-ce after adding the required repo to /etc/apt/sources.list.d/docker.list).
In any case I verify that Docker CE is installed correctly by running the hello-world image and checking the version and everything seems to be correct:

Client:

 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:18:40 2018
 OS/Arch:           linux/arm
 Experimental:      false
 
Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:14:26 2018
  OS/Arch:          linux/arm
  Experimental:     false

Then I run sudo su and I install Hass.io with the command:

curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m armhf

It finish with no errors but when I try to see the frontend on a browser (http://orangepizero:8123) nothing is shown.

If I look for the docker containers using docker ps I only see one:

CONTAINER ID        IMAGE                                   COMMAND               CREATED             STATUS              PORTS               NAMES
97bae1780c51        homeassistant/armhf-hassio-supervisor   "python3 -m hassio"   22 hours ago        Up 18 hours                             hassio_supervisor

Please, can someone tell me what I'm doing wrong?
Thanks

**Comment by carlostico** [comment]
Hi Alberto 

Could you please try with :

`curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m armhf`

**Comment by albertogonzalez** [comment]
Hi Carlos,

If you read again my description you'll see that I tried installing Hass.io using that command.

**Comment by carlostico** [comment]
Hi Alberto my bad... 

I fixed the command for an Orange Pi machine. 

I Installed and everything is working here 

Let me know

**Comment by albertogonzalez** [comment]
Thanks! I'll try with qemuarm.
Is your board an Orange Pi Zero too or a different model?

**Comment by carlostico** [comment]
Mine is Orange Pi+ 2E but it should work , keep me posted

**Comment by carlostico** [comment]
The only problem @albertogonzalez  is that Bluetooth it's not working in this way of install

**Comment by albertogonzalez** [comment]
Thank you for letting me know.

**Comment by lourivalbarreto** [comment]
Congratulations @carlostico

Can I suggest an improvement?
Why this script dont install all dependences?

Jose

**Comment by lourivalbarreto** [comment]
I am new here.....
How can I install correctly all dependences?

Thanks,
Jose

**Comment by carlostico** [comment]
https://gist.github.com/frenck/32b4f74919ca6b95b30c66f85976ec58#file-hassio_ubuntu_install_commands-sh

**Comment by carlostico** [comment]
Not sure but I found that from @Frenck on the discord channel

**Comment by lourivalbarreto** [comment]
Thanks a lot @carlostico
Works!

**Comment by mitchando96** [comment]
@ albertogonzalez Hi would you mind giving me some directions on how to install Hassbian on the OrangePi zero? I've followed the armbian instructions but I would like to use Hassbian instead

**Comment by albertogonzalez** [comment]
Hi @mitchando96 I'm writting some posts for my blog about how to install Home Assistant on an Orange Pi Zero (Hassbian and Hass.io) but they are not ready yet. You can follow me on Twitter (gamebaker) to find out when they are published.
In the meantime, I recommend that you read this page:
https://home-assistant.io/docs/installation/armbian/

**Comment by marine1988** [comment]
I have orange pi zero with armbian installed hassbian with python virtual environment should I change to docker?

**Comment by albertogonzalez** [comment]
@mitchando96 @marine1988 You probably don't need it but I published today how to install Armbian on an Orange Pi Zero. 
https://www.albertogonzalez.net/2018/08/26/how-to-install-armbian-debian-on-an-orange-pi-zero/
In the following posts I will show how to install Home Assistant using a python virtual environment and Hass.io using a Docker container.
If you want my opinion, I prefer the Hass.io option.

**Comment by OvCa77** [comment]
Hello,
I am having the same problem installing HASS.io with missing docker. I have installed all dependencies, install goes through without any errors but I cannot use it.
root@orangepizeroplus:~# curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m qemuarm
[Info] Install supervisor docker
[Info] Install supervisor startup scripts
[Info] Install AppArmor scripts
[Info] Run Hass.io

**Comment by albertogonzalez** [comment]
@mitchando96  I have published a complete guide about how to install Home Assistant on an Orange Pi Zero 
https://www.albertogonzalez.net/2018/08/30/how-to-install-home-assistant-on-an-orange-pi-zero/

**Comment by alexandrecv01** [comment]
Hi when will you post the hassio installation on orange pi

**Comment by albertogonzalez** [comment]
@alexandrecv01 It's absolutely on my list, but you'll have to wait a bit because there are some other posts I want to publish first. Stay tuned!

**Comment by alexandrecv01** [comment]
@ albertogonzales Thank you. Let's wait.

**Comment by raystream** [comment]
I have installed hassio on an orangepi zero this way:

`copy armbian toSD Card with etcher or win32diskimager

start OrangePi and set root passwort 
abort the user creation

login as root

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

echo "deb [arch=armhf] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

apt-get update

apt-get install -y apparmor-utils apt-transport-https avahi-daemon ca-certificates curl dbus jq network-manager socat software-properties-common gnupg2

apt-get install -y docker-ce

wget https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install

chmod u+x hassio_install

./hassio_install -m qemuarm`

**Comment by thanhtantran** [comment]
> 7\. apt-get update

Hello,

I got error while update repo as follow

`root@orangepizero:~# curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
OK
root@orangepizero:~# echo "deb [arch=armhf] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
deb [arch=armhf] https://download.docker.com/linux/debian bionic stable
root@orangepizero:~# apt-get update
Ign:2 https://download.docker.com/linux/debian bionic InRelease
Hit:3 http://ports.ubuntu.com bionic InRelease
Hit:4 http://ports.ubuntu.com bionic-security InRelease
Hit:5 http://ports.ubuntu.com bionic-updates InRelease
Err:6 https://download.docker.com/linux/debian bionic Release
  404  Not Found [IP: 54.192.75.91 443]
Hit:7 http://ports.ubuntu.com bionic-backports InRelease
Hit:1 https://apt.armbian.com bionic InRelease
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/debian bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

how to fix it?

**Comment by berryelectronics** [comment]
> @mitchando96 I have published a complete guide about how to install Home Assistant on an Orange Pi Zero
> https://www.albertogonzalez.net/2018/08/30/how-to-install-home-assistant-on-an-orange-pi-zero/

Hey, cool that you made an article, but why is your webpage forcing me to allow notifications for some weird ad company? this really lowers your page hits..
