### ISSUE TITLE
Request to change URL_VERSION back to github

### ISSUE THREAD

**Issue by neroxps** [home-assistant/hassio#594]
Hello everyone.

Starting with hassio version 109, switch URL_VERSION to https://s3.amazonaws.com/hassio-version/stable.json, but access to s3.amazonaws.com in mainland China is severely disrupted, which can cause hissio to fail to update or even start up.

Can I change the URL to github?

**Comment by pvizeli** [comment]
Is fixed with 118. I will create new images to include this supervisor 👍

**Comment by neroxps** [comment]
Thank you for your reply.

After version 118, even if you can't access https://s3.amazonaws.com/hassio-version/stable.json, it won't cause a startup failure.

However, due to the inability to access https://s3.amazonaws.com/hassio-version/stable.json, hassio and homeassistant cannot be upgraded properly. This forced me to give up using hassio.

If you can switch back to the https://raw.githubusercontent.com/home-assistant/hassio/dev/version.json address you used before, there will be no problem.

**Comment by awarecan** [comment]
LOL, we should buddle a ladder.

**Comment by neroxps** [comment]
```
18-08-03 04:31:30 WARNING (MainThread) [hassio.updater] Can't fetch versions from https://s3.amazonaws.com/hassio-version/stable.json: 
```

feel despair! !

In mainland China, I can't recommend hassio to my friends.

FUCK GFW! ! !
