### ISSUE TITLE
can't use  hassio in Raspberry Pi 3b(not 3b+),with hassos_rpi3-1.7.img.gz or hassos_rpi3-64-1.7.img.gz

### ISSUE THREAD

**Issue by endless1651** [home-assistant/hassio#596]
Hi, I just install hassio with Raspberry Pi 3b,whether 32bit nor 64bit IMG can use when the installation done. I can ping my Pi,but ,I can't access http://hassio.local:8123,and I can use hassio with a low version ,just like 1.1,that img can work . is this a bug for Pi 3b?

**Comment by pvizeli** [comment]
please send the output of "su logs"

**Comment by endless1651** [comment]
ok, i will paste the log  when i reinstall hassio asap

**Comment by pvizeli** [comment]
we use a more modern version with journalctl as login background.

**Comment by endless1651** [comment]
I'm sorry for reply so lately,i can't ssh my pi3b ,i put authorized_keys in boot and i can't connect port 22222,so i don't know how to copy jounal log to you

**Comment by endless1651** [comment]
and i found when pi3b reboot, the date will be 2018-1-28

**Comment by frenck** [comment]
@endless1651 Any progress on this? Is this still an issue?
