### ISSUE TITLE
Release 120 broke Node-Red Addon and introduced interface error

### ISSUE THREAD

**Issue by jjpeet** [home-assistant/hassio#601]
Hi,
I just restarted my HassOS and HASS.io updated itself to 120.
On restart Node-Red now does not come up (neither node red 1880 or /UI dashboards).
Also, the “System” tab hass changed the CSS so its all full screen now.

Running HassOS 1.7, HASS.io 120 and HASS 73.2

JP

**Comment by jjpeet** [comment]
Oh and I have cleared my browser cache...  Problem is still there.
JP

**Comment by jjpeet** [comment]
After 30min, Node-Red is now working again. Not sure why.
The CSS is still wonky on the “System” tab.

**Comment by danielsjf** [comment]
I get an error while loading the hassio panel:
Unable to load the panel source: /api/hassio/app/entrypoint.js.

Not clear if this is related.

**Comment by pvizeli** [comment]
Any kind of logs?

**Comment by pvizeli** [comment]
If you have problem. Remove `ip_bans.yaml` from configuration and reboot
