### ISSUE TITLE
Continuos reboot hassio

### ISSUE THREAD

**Issue by ezar** [home-assistant/hassio#606]
After update to supervisor 119, 120, 121..., system reboots every 10 minutes :(

**Comment by pvizeli** [comment]
https://github.com/home-assistant/home-assistant/issues/15673

Look like a custom component hit the connection pool.

**Comment by stevearbon15** [comment]
I'm also seeing this issue. On HASS 74.1 with Supervisor version 121.

**Comment by pvizeli** [comment]
Remove `ip_bans.yaml` from configuration

**Comment by ezar** [comment]
Works!!!

**Comment by frenck** [comment]
Thank you for letting us know @ezar!
Happy to hear it worked 👍
