### ISSUE TITLE
Unable to configure wifi in HassOS for RBP3

### ISSUE THREAD

**Issue by Ilitem2** [home-assistant/hassio#609]
Hi, I just installed HassOS for Raspberry Pi 3,whether 32bit (recommended) or 64bit after it has finished install, I open SD card files but I can't located the System Connections Folder, where the Resin Sample is supposed to be so I can change the setting in wifi. Any help on where to locate the folder or how to continue is greatly appreciated.

These are the file/folder on the SD Card

overlays
bcm2710-rpi-3-b.dtb
bcm2710-rpi-3-b-plus.dtb
bcm2710-rpi-cm3.dtb
boot.scr
bootcode.bin
cmdline.txt
config.txt
fixup.dat
ssart.elf
u-boot.bin

**Comment by frenck** [comment]
The file does not go onto the SD card.
The file needs to go on a separate USB stick.

Please watch this introduction video: <https://www.youtube.com/watch?v=qnCRcGTznXs>
