### ISSUE TITLE
hassio.local:8123/hassio blank page

### ISSUE THREAD

**Issue by madberry** [home-assistant/hassio#628]
Hey guys,

Ran into a problem trying a new install of hass.io on a Raspberry Pi 3 B+ it has installed and I can open the homepage opens up just fine.

The /hassio page however refuses to open up and out of the log on the about page I copied this error:

"hassio.local:8123/frontend_latest/app-7338956c.js:2:32005 Uncaught TypeError: Cannot read property 'length' of undefined"

I've been unable to find any issues with the current version could someone point me in the right direction on how to solve this please.

Thanks,
Really looking forward to getting this setup and working.
Berry

**Comment by pvizeli** [comment]
This bug is fix with Home-Assistant 0.75.1

**Comment by madberry** [comment]
That is the version I am using
