### ISSUE TITLE
Home-Assistant API config missmatch: 401  when enabling api_password

### ISSUE THREAD

**Issue by Censored3** [home-assistant/hassio#632]
Hi,

As soon as I enable api_password in HA, the hassio_supervisor seems to miss that on a certain check. This yields a 401, causing the watchdog to restart HA (seems to be every 15mins).
Running latest supervisor (v123).

Log:
```
18-08-07 11:14:11 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch: 401
18-08-07 11:14:11 ERROR (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant API!
18-08-07 11:14:11 INFO (SyncWorker_13) [hassio.docker.interface] Stop homeassistant/qemux86-64-homeassistant docker application
18-08-07 11:14:15 INFO (SyncWorker_13) [hassio.docker.interface] Clean homeassistant/qemux86-64-homeassistant docker application
18-08-07 11:14:15 INFO (SyncWorker_10) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.75.2

```

**Comment by pvizeli** [comment]
Do you have a `ip_ban.yaml` inside config folder? Can you remove it?

**Comment by Censored3** [comment]
Hi, no, I checked that, I can't find any ip_bans.yaml. Even though the hassio internal IP gets banned, it's not put in that yaml. Also, disabling api_password 'solves' the issue...

**Comment by austwhite** [comment]
I am having similar issue with HASSIO.  I am not able to offer much as far as coding and what not, but the fault seems to be some kind of authentication issue.
Adding the docker IP range to the trusted IP list seems to fix the issue, if this helps with troubleshooting.

**Comment by Censored3** [comment]
Seems to be fixed in current release of hassio/ha. Possibly because of the new auth system.
