### ISSUE TITLE
Not able to use the Hass.IO Panel with Home-Assistant 0.45

### ISSUE THREAD

**Issue by pascalmattes** [home-assistant/hassio#65]
After doing a fresh reinstall with the new 0.8 image and adding my config I can't use the Hass.IO Panel any more.
When I try to open it there is a popup saying: "Failed to load the Hass.io panel from supervisor."

![image](https://cloud.githubusercontent.com/assets/12157131/26285060/2d56b96c-3e48-11e7-8195-4f0e415a9ef9.png)

**Comment by apo-mak** [comment]
i have the same problem . the error goes away if i disable the API password.
```
http:
  api_password: PASS
```
if you look the home assistant logs there is a report of wrong login when you restart the hassio hypervisor 
` WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.17.0.4`

> docker restart hassio_supervisor

**Comment by pvizeli** [comment]
That will be fix with HomeAssistant 0.45.1

**Comment by pvizeli** [comment]
https://community.home-assistant.io/t/release-notes/17316/18
