### ISSUE TITLE
Can't update from home assistant 0.75.3 to 0.76

### ISSUE THREAD

**Issue by hugodelaroza** [home-assistant/hassio#661]
It takes a long time trying to update, buy when finally restarts it's on 0.75.3. I read something about changing wait_boot variable from 600 to 900, but culdn't find the file with tis option connecting on SSH

Can anybody help me? if not, I'll have to make a clean installation of my hassos

Thanks

**Comment by pvizeli** [comment]
That is not anymore needed. Update to 0.76.2 should fix all problems and supervisor 127 can detect running DB migration and don't abort anymore.

**Comment by hugodelaroza** [comment]
ok, Thanks, I'll Try

**Comment by hugodelaroza** [comment]
It doesn't update.. I don't know what to do except a celean installation

**Comment by pvizeli** [comment]
Remove the database or post logs

**Comment by hugodelaroza** [comment]
removed database and the problem persists. I made a clean installation and now it wors.

Thanks anyway Pascal!!
