### ISSUE TITLE
local addon using "full_access"

### ISSUE THREAD

**Issue by tomcatGu** [home-assistant/hassio#664]
I set full_access to true at my config.json file.But I can not see full dev list at /dev folder in addon container.

**Comment by tomcatGu** [comment]
{
  "name": "nRFNet",
  "version": "1",
  "slug": "nrfnet",
  "description": "nrf24l01+ network add-on!",
  "startup": "application",
  "boot": "auto",
  "options": {},
  "schema": {},
  "full_access": true,
  "protected": false

}
Like this?

**Comment by tomcatGu** [comment]
I add the api component to my configuration.yaml file. 
Call GET /api/ then returns a "API running "message.But when call GET /api/addons there retuns "404: Not Found" message.Is somewhere error?

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio/blob/dev/API.md
