### ISSUE TITLE
How to set local addon state to "unprotected"?

### ISSUE THREAD

**Issue by tomcatGu** [home-assistant/hassio#666]
In config.json file I use the following config:
  "full_access": true,
  "protected": false
But no effect.

**Comment by frenck** [comment]
This is currently not yet possible.
Unprotected is an action that a user could do, not an add-on. This gives the user the awareness and specific choice of "unprotecting" an add-on. This part is not yet added to the user's Hassio/add-on panel.

**Comment by frenck** [comment]
Duplicate of #664

**Comment by pergolafabio** [comment]
Hi @frenck , is this now possible? I also want full access to retrieve all devices...how can I disable protection mode on a local add-on?

@tomcatGu , did you manage?
