### ISSUE TITLE
Suggestion about "full_access"

### ISSUE THREAD

**Issue by tomcatGu** [home-assistant/hassio#683]
Make a suggestion to cancle protected check from full_access check. The "full_access" means complete control.When set full_access to true but nothing had happened.It's very confusing.

**Comment by pvizeli** [comment]
That work only if you disable the protection mode for this add-on...

**Comment by frenck** [comment]
We are currently waiting for a UI developer to add an option into the interface, allowing the user to "unlock" protected features like this.

Therefore it is currently not available for use yet.
