### ISSUE TITLE
Hass.io panel provides no feedback in interface when action causes an error 

### ISSUE THREAD

**Issue by genestealer** [home-assistant/hassio#689]
**Feature Request**
Please consider reporting back error messages to the UI / log when starting HASSIO add-ons.

**Background**
Hass.io provides no error messages shown when starting add-ons, which fail when attempting to start.

My Home Assistant is in the form of Hass.IO in Docker on a virtualized Ubuntu Server 18.04, as per these instructions: https://bonani.tech/how-to-install-hass.io-on-ubuntu-server-18.04/ .

As an example, I already have an server running on the same port as the add-in wants to bind to, I'm my case APC UPS Daemon is running on the Ubuntu server, so when trying to start the Hass.io apcupsd add-on it fails and the only line in the logs is: “Error grabbing logs: EOF”.

The issue turned out to be I already had a APCUPSD server running on the same machine, so the new docker container could not start because port was in use (error message: 3551: bind: address already in use).

Only found by using Docker Portainer by manually starting the apcupsd Hass.io add-on which then presented me with the error.

**Comment by genestealer** [comment]
In the meantime we can view the logs via: your_hass_instance/hassio/system

**Comment by pvizeli** [comment]
What do you see inside supervisor logs?

**Comment by genestealer** [comment]
The logs are there inside the supervisor logs, but my request is to have the error show up when attempting to manually start an add in. Currently when trying to start nothing appears, there is no obvious indication that any action has taken place. The only way to know why the little indicator hasn't switch to green is to check the logs.

**Comment by frenck** [comment]
Changed the title a little to be more descriptive of the issue.
This is something that should be solved in the frontend and therefore I'll move this to the frontend repo.
