### ISSUE TITLE
401: Unauthorized when calling hassio API

### ISSUE THREAD

**Issue by tomcatGu** [home-assistant/hassio#693]
In HA0.77.3:
 curl -H "Content-Type" -X POST --data '{"protected":"false"}' http://hassio/addons/local_nrfnet/options
return 401.
In HA0.77.2: this command works well. 
I add  "x-ha-access:${HASSIO_TOKEN}" into the parameters but the command returns 401 also.

**Comment by pvizeli** [comment]
You need include the hassio token + the api call have moved to /addons/.../security. Look at changelog of 129

**Comment by pvizeli** [comment]
https://github.com/home-assistant/developers.home-assistant/blob/master/docs/hassio_addon_communication.md#hassio-api

**Comment by frenck** [comment]
I think that would resolve your issues @tomcatGu, therefore closing this issue.
If you have additional questions, feel free to re-open or (probably better), join us at Discord, so we can help you directly.
