### ISSUE TITLE
Timezone not passed to addons correctly

### ISSUE THREAD

**Issue by omgnvq** [home-assistant/hassio#732]
Hello, 

Despite having timezone set in configuration.yaml correctly (Europe/Berlin) this is not respected by the Node-Red addon. 

After speaking to the guy who created the addon, it is a problem with the data which is passed through, not the addon itself

Thanks

**Comment by pvizeli** [comment]
`hassio su info`

We pass the timezone to container but they need installed the tzdata otherwise it have no effect.

**Comment by frenck** [comment]
@pvizeli The community add-ons have tzdata and restart do not help.
I've now received multiple reports on this in the last couple of days.

**Comment by pvizeli** [comment]
`hassio su info`

If the timezone are correctly, it work with available tzdata on alpine.

**Comment by frenck** [comment]
Another similar report: https://github.com/home-assistant/hassio-addons/issues/417

**Comment by pvizeli** [comment]
I need know that the supervisor say:
`hassio su info`

**Comment by pvizeli** [comment]
Look like that is a issue with multiarch base images

**Comment by frenck** [comment]
Hmm interesting:

https://github.com/gliderlabs/docker-alpine/blob/c14b86580b9f86f42296050ec7564faf6b6db9be/versions/library-3.8/armhf/Dockerfile

**Comment by pvizeli** [comment]
I fix the bug for homematic add-on with simple install tzdata

**Comment by andrea-mattioli** [comment]
Hi there i've a same issue on my addons, 
i use homeassistant  image trought build.json:
```
{
  "build_from": {
    "aarch64": "homeassistant/aarch64-base:3.12",
    "amd64": "homeassistant/amd64-base:3.12",
    "armhf": "homeassistant/armhf-base:3.12",
    "armv7": "homeassistant/armv7-base:3.12",
    "i386": "homeassistant/i386-base:3.12"
  }
}
```
On Hassios variable TZ is not used and my addons are in UTC.
How can i fix this issue?
Thanks
