### ISSUE TITLE
Container name before being renamed homeassistant

### ISSUE THREAD

**Issue by signaleleven** [home-assistant/hassio#768]
When I start or restart home assistant from the hassio supervisor, the homeassistant container is first created with a default name (default docker naming convention, adjective_scientist) and then renamed.
Why is that? I log container metrics on influx db, and the metrics are tagged with the container name. Therefore I have several containers metrics that exist for a few seconds only, before being renamed.

Is there any specific reason why the container is not started directly with the correct name?

**Comment by pvizeli** [comment]
You can look into the code. We don't rename the container. Look like the API work in that direction.
