### ISSUE TITLE
New Xiaomi Button Not Detected

### ISSUE THREAD

**Issue by fcollingwood** [home-assistant/hassio#773]
New Xiaomi button is not detected: {'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001e79089', 'short_id': 2100, 'data': '{"voltage":3165}'}

This has been fixed in PyXiaomiGateway (See line 235 at https://github.com/Danielhiversen/PyXiaomiGateway/blob/master/xiaomi_gateway/__init__.py) but is not yet in Hass.io.

**Comment by frenck** [comment]
Thank you for opening a PR @fcollingwood, nevertheless, this is not an issue with Hass.io, but with Home Assistant itself.

The correct repository for reporting this issue would be: https://github.com/home-assistant/home-assistant
