### ISSUE TITLE
Corrupt hassio rpi2 img files

### ISSUE THREAD

**Issue by gfoltz** [home-assistant/hassio#775]
## SUMMARY
I cannot install HassOS on my rpi2. I think the img files for rpi2 are corrupted.

## STEPS:
1.) Download https://github.com/home-assistant/hassos/releases/download/1.11/hassos_rpi2-1.11.img.gz
2.) Write to 32gb SD card with Etcher using a Macbook Pro

## RESULTS:
Disk image is not readable by my macbook.
RPI2 will not boot. I get a single green LED flash and then nothing. No display output.

## EXPECTED:
I'm new to all this, but my understanding is that RPI2 images are FAT32 and therefore readable by OSX. That's how it works with other RPI2 images I've tried.

## NOTES:
I also tried https://github.com/home-assistant/hassos/releases/download/1.11/hassos_rpi2-1.10.img.gz. Same result

Also tried Kodi OpenElec (http://releases.libreelec.tv/LibreELEC-RPi2.arm-8.90.005.img.gz) using the same equipment. This worked as expected.

**Comment by hanneskl** [comment]
Same issue here with Etcher 1.4.5 on an iMac and Macbook Pro with 1.11.
I also tried unzipping the file first before flashing.

I get one quick green flash on the ACT LED and then nothing.

**Comment by pvizeli** [comment]
That is a Mac problem. The Disk layout is GPT hybrid and a MacOSX version doesn't support this and modify the partition table without any user input. The effect is, mac destroys the partition table. There is a thread on HassOS repository, if I understand that correct, it is only affected on older MacOSX.

**Comment by gfoltz** [comment]
@hanneskl in my case I was just being dumb. Turns out I have an RPI 3, not RPI 2. I was able to get it running using the RPI 3 image.

The fact that I cannot mount the disk image on OSX is easy to repro. I don't have an issue with it corrupting when I attempt to mount it from the SD card, though.
