### ISSUE TITLE
`403: forbidden` when running any hassio commands

### ISSUE THREAD

**Issue by ndarilek** [home-assistant/hassio#781]
When SSH'd into the core_ssh addon, hassio commands no longer work and throw a 403.

When I SSH into the debug port and view the supervisor logs, I see:

```
18-10-25 19:25:42 WARNING (MainThread) [hassio.api.security] /host/reboot no role for core_ssh
18-10-25 19:25:42 ERROR (MainThread) [hassio.api.security] Invalid token for access /host/reboot
```

Using Supervisor 138, HassOS 1.11 and Home Assistant 0.80.3 on a RPi 3B+.

**Comment by frenck** [comment]
I guess you need to update the SSH add-on...
What version are you on?
