### ISSUE TITLE
please upgrade hassio-cli to latest version

### ISSUE THREAD

**Issue by c0ff3e** [home-assistant/hassio#784]
Hi.

Did upgrade today and i have

> core-ssh:~# hassio -v
hassio version 1.3.1

and there is 1.4 out sins 22/9

BR

**Comment by c0ff3e** [comment]
seems there is a issue with ha reboot command

> core-ssh:~# hassio ha info
{
    "result": "ok",
    "data": {
        "version": "0.81.0",
        "last_version": "0.81.0",
        "machine": "raspberrypi3",
        "image": "homeassistant/raspberrypi3-homeassistant",
        "custom": false,
        "boot": true,
        "port": 8123,
        "ssl": true,
        "watchdog": true,
        "wait_boot": 600
    }
}
core-ssh:~# hassio ha restart
Error decoding json invalid character ':' after top-level value: 403: Forbiddencore-ssh:~#

**Comment by pvizeli** [comment]
1.4 is out a long time: https://github.com/home-assistant/hassio-addons/commit/c47b3673ded481dc04dc7ba653cb0b56f593ff66
