### ISSUE TITLE
HA Bugfix releases should be available ASAP

### ISSUE THREAD

**Issue by mbo18** [home-assistant/hassio#785]
Home Assistant 0.81.1 is out for more than 24 hours now but Hassio users are still waiting to get this bugfix release. Only 0.81.0 is currently available.

I think that minor releases (which are only for bug fix) should be available as soon as it is released for Hassio users as it fixes major bugs introduced in major release.

Thanks

**Comment by pvizeli** [comment]
is out

**Comment by mbo18** [comment]
Well it was more a feature request than specific to this release. Also, not out for me currently
