### ISSUE TITLE
First run

### ISSUE THREAD

**Issue by imbackniantic** [home-assistant/hassio#789]
Hi everyone,
I've just run hass.io on my pi3 b+ but it does not start. It is connected through HDMI and ethernet. 
The last 2 lines that are repeated every 5 minutes are:
IPv6: ADDRCONF (NETDEV_UP): wlan0: link is not ready
BRCMFMAC: power management disabled

If i go to hassio.local nothing appears, if i reach the HA with its IP address i see Preparing Hass.io
(this can take up to 20 minutes) but after hours nothing changes. What can i do?

**Comment by pvizeli** [comment]
You can add a USB Tastatur and login into CLI. After that you can enter `su logs`.

Do you block NTP? Without NTP the time will not set correctly and they can't setup home assistant.

**Comment by frenck** [comment]
@imbackniantic Any progress on this issue?

**Comment by hungyip** [comment]
Hassio cannot be run in China now because it use Google NTP server (which unfortunately, is blocked by the government). If hassio can use another NTP server it would be good

**Comment by eplt** [comment]
even with vpn, i can't get it to work. i ended up going back to Hassbian and it works well. i liked hass.io, easy to use, and easy to install add-ons, but it just doesn't work in china.
