### ISSUE TITLE
Home Assistant doesn't resolve .local domain

### ISSUE THREAD

**Issue by woutercoppens** [home-assistant/hassio#79]
The .local domain is used by multicast dns services: https://en.wikipedia.org/wiki/.local

If I put .local hostnames in the configuration.yaml file, I get resolve errors.

Please include the avahi package in the home-assistant docker container:
https://pkgs.alpinelinux.org/package/v3.6/main/armhf/avahi-compat-libdns_sd

Add this line to /etc/dnsswitch.conf:
hosts:          files mdns4_minimal dns [NOTFOUND=return] mdns4

More info can be found at:
https://wiki.archlinux.org/index.php/avahi

**Comment by pvizeli** [comment]
Work that inside a docker since it redirect all dns query to dns server that is set on dockerd? On resinos it goes to a local dns server.

**Comment by stickystyle** [comment]
The .local domain wouldn't get resolved by a DNS server, it would be resolved by Avahi via multicast DNS (mDNS).

**Comment by pvizeli** [comment]
also inside a docker? You can make a PR on build repository for homeassistant docker Image. This issue is for hassio supervisor bugs.

**Comment by mcolyer** [comment]
The [documentation](https://home-assistant.io/hassio/installation/) refers to using `hassio.local` as a way to access a hass.io installation but that doesn't seem to work for me. @pvizeli can we repurpose this issue to address that or is there a better repo to discuss that on?
