### ISSUE TITLE
Hass-os supervisor crash after reboot

### ISSUE THREAD

**Issue by Masterzior** [home-assistant/hassio#794]
Out of the blue the OS side of Hass-os has started not working. after investigation i found that the supervisor cant have an uptime more of 10 seconds and i draw from that discovery that the supervisor OS container is stuck in either a boot-loop or something is very broken. Ive not made any changes at all to the OS or At all infact since 3 weeks , and its been working perfectly untill today. 
![img_20181105_130340](https://user-images.githubusercontent.com/23239792/47997668-f0bb7e80-e0fc-11e8-8a62-cc4672a47af2.jpg) Heres an image of the Log i got from the supervisor container before it restarts itself every 10 seconds

Verision: 81.X.
Installing method: Hass-os, SD Card with Etcher as flasher.

**Comment by aav7fl** [comment]
Looks like a breaking change with the `core-mosquitto` broker possibly? I removed my `discovery.json` file and managed to get it booting again (suggested by cogneato on Discord).

**Comment by deviant-studio** [comment]
Same issue. I'm on Hassio 81.2
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/hassio/__main__.py", line 40, in <module>
    loop.run_until_complete(coresys.core.setup())
  File "uvloop/loop.pyx", line 1448, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/site-packages/hassio/core.py", line 56, in setup
    await self.sys_discovery.load()
  File "/usr/local/lib/python3.7/site-packages/hassio/discovery.py", line 36, in load
    discovery = Message(**message)
TypeError: __init__() got an unexpected keyword argument 'uuid'
```

I have mqtt addon installed too.
Tried to remove `discovery.json` with no success :(

**Comment by pvizeli** [comment]
Is fix with 139.

Yes, remove the `discovery.json` and it will startup again. After that you can update to supervisor 139.

**Comment by lativl** [comment]
Please suggest how can I remove  discovery.json file? My installation type - Hass.io image and now I can not access it either from SSH, Samba or WebUI. Can I eject SD card and delete it directly?

**Comment by pvizeli** [comment]
You can attach a USB keyboard and monitor to your device and login into console.

**Comment by Masterzior** [comment]
It was indeed the discovery.json file . I deleted it by plugging away monitor and keyboard into my host and finding the file in /mnt/data/supervisor.  Rebooting and then updating the supervisor to 139 .

**Comment by slonkar** [comment]
@pvizeli I am having similar issue (https://github.com/home-assistant/hassio/issues/799) When connected Pi is connected to monitor, I get continuous stream of logs. Is there way to terminate it and log in into pie? Also what would be default username and password?

**Comment by slonkar** [comment]
@Masterzior I am kinda newbie, not sure how to get login prompt with that steam. I do get login prompt sometime but by the time I start typing steams start loading again. Also whats the credentials for root? Are they pi default (pi/raspberry)?

**Comment by Masterzior** [comment]
Just write root into the cli and it should tell you welcome to hass.io or whatever. Then write login and You should hit # aka the os . From there follow the instructions People have said .

**Comment by lativl** [comment]
When I connect monitor I see just HA logo screen... How to switch to the command line?

**Comment by Masterzior** [comment]
@lativl what do you mean ? You are already inside the command line then just start writing ?

**Comment by lativl** [comment]
I have hass.io type of setup and see just splash screen
![image](https://user-images.githubusercontent.com/34886340/48083861-eda8b700-e1fe-11e8-9791-a3b76d4b69d7.png)

**Comment by lativl** [comment]
Upd: Managed to access SD content via another raspberry and delete discovery.json file.

**Comment by cogneato** [comment]
@lativl you found the other way which is good, as you are running the older resinOS version of Hassio and there is no console to log into. The HassOS based version has the offline access.

**Comment by slonkar** [comment]
I was able to get into /mnt/data/supervisor/ but I don't see any discovery.json file there. Earlier you mentioned rebooting supervisor and updating it to 139, but when I try to that by following command
`# su reboot / update`
I am getting Error in log.

**Comment by Masterzior** [comment]
> I was able to get into /mnt/data/supervisor/ but I don't see any discovery.json file there. Earlier you mentioned rebooting supervisor and updating it to 139, but when I try to that by following command
> `# su reboot / update`
> I am getting Error in log.

You can update the supervisor in the frontend. All i did was remove the discovery.json file, which made my frontend work, then i updated the supervisor from 138 to 139 via the frontend.
