### ISSUE TITLE
Mosquitto broken after update to v139

### ISSUE THREAD

**Issue by DoctorOctagonapus** [home-assistant/hassio#798]
HassOS 1.12 32-bit on RPi 3B+
Home Assistant v0.80.3
Mosquitto addon v2

System apparently updated itself to v139 this morning, and that was the last time I received any communication from any of my MQTT devices. Since the update, all I get is a message in the log that says "Unable to connect to the MQTT broker: Connection Refused: not authorised."

Relevant section of configuration.yaml:
mqtt:
    broker: core-mosquitto
    username: "homeassistant"
    password: !secret http_password

Mosquitto config:
{
  "plain": true,
  "plain_websockets": false,
  "ssl": false,
  "ssl_websockets": false,
  "anonymous": true,
  "logins": [
    {
      "username": "homeassistant",
      "password": "[PASSWORD]"
    }
  ],
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}

Tried restoring from a known working snapshot from a few days ago but the problem still persists, leading me to think the issue is with the Supervisor as that's the only thing that's different.

**Comment by pvizeli** [comment]
Please read the documentation about user management:
https://www.home-assistant.io/addons/mosquitto/

Or in short terms:
- Remove the login stuff on add-on options
- Remove the configuration from yaml and the integration on settings (panel)
- Restart Home Assistant
- Go into settings on integration and click to the new mqtt integration from add-on
- Need no manual configuration anymore

Old way:
- Create a user they not call `homeassistant` on add-on options
- Change your yaml settings.
