### ISSUE TITLE
RFC: Set add-on options as Docker environment variables

### ISSUE THREAD

**Issue by cschroeter** [home-assistant/hassio#805]
### Current behavior
At the moment an add-on is started with the following environment and volume:
```shell
# Environment
{'TZ': 'UTC', 'HASSIO_TOKEN': 'ab6720fc028...'}
# Volume
/mnt/data/supervisor/addons/data/core_hello_world': {'bind': '/data', 'mode': 'rw'}
```

Within the attached volume you can find the `options.json` including your add-on options like:
```json
{
  "SECRET": "abc"
}
```

### Desired behavior
Along with the current behavior, which should be kept for backward compatibility, an add-on should also be started with its options available as environment args.

```shell
# Environment
{'TZ': 'UTC', 'HASSIO_TOKEN': 'ab6720fc028...',  'SECRET': 'abc'}
```

### Motivation
A lot of Docker images requires you to make certain configurations. With the `options.json` approach there is no way to plug&play a Docker image. You'll either have to write an wrapper to parse that options.json and start the Docker container accordingly or even worse your Docker images has to be aware that there is an option.json with some kind of configuration.

**Comment by pvizeli** [comment]
First, we could use the option `legacy`, and if they is available, we parse the first layer of options as Environment to container.

Why legacy, that is for docker images they are not builded for Hass.io and not have any labels for our supervisor. I think the Environment approach is a nice try to allow simply modification without need a Orchestra but it now allow more complex structure they we have. But I see the need, if you have a simple container they don't need anything from Home Assistant / Hass.io world.

**Comment by cschroeter** [comment]
For me it is not clear why non-legacy Docker containers should not get those options passed in as environment args. It just introduces another layer of complexity. Eventually it comes down to one line of code

```python
# docker/addon.py
@property
def environment(self):
     """Return environment for Docker add-on."""
    #  {...}

    return {
        **addon_env,
        # pass add-on optoions as Docker environment args
        **self.addon.options
        ENV_TIME: self.sys_timezone,
        ENV_TOKEN: self.addon.hassio_token,
    }

**Comment by pvizeli** [comment]
Because non-legacy docker images are specially created for Hass.io, and they should use the modern json options and not old school flat environment they can be reading from anyone. Docker use also json options for his swarm operations but this feature is not available for dummy single container management :( In that case we adapt this form for Hass.io Add-ons.

**Comment by cschroeter** [comment]
Ok that makes sense. It just a little bit confusing to know that the flag`legacy` means: _something which is not explicitly build for Hass.IO

**Comment by pvizeli** [comment]
yeah, docker legacy container

**Comment by svrooij** [comment]
@bramwalet they changed something to the hass.io setup. You can just have hass.io set environment variables so it wouldn't require any changes to the image.
