### ISSUE TITLE
Hassio addon container boot order issues

### ISSUE THREAD

**Issue by cbrherms** [home-assistant/hassio#812]
Howdy all.

So, it's come to my attention lately that after starting to use MQTT discovery more for devices (loving ESPHomeYAML for that) i'm starting to have some issues after hard reboots of my HASSIO host.

After a reboot, my MQTT broker (The community version by @frenck) is a little slower to load than the main hass front end, causing issues with devices not appearing or being discovered as the broker is not ready yet. 
This means i have to go through and restart some addons that rely on mqtt such as my zigbee addon, and then reload hass itself.

Rather than pinning the issue on a particular addon though, i believe it would be more beneficial to have a way to choose boot order or delay between addons starting. Maybe within the list of addons set a preferred order / priority number to each addon?

EDIT:
Looks like there is a way to do this via API but cannot find any documentation? This was mentioned in a previous issue that looked like it was closed due to staleness #562

**Comment by frenck** [comment]
IMHO, this should not be solved this way.
Programs/software using the services should be able to handle the loss of connection to services at any time and reconnect as soon as they are available again.

As of the states, MQTT supports retaining messages and HA support auto-discovery. Those are the things that will add to a proper solution.

**Comment by cbrherms** [comment]
Indeed, after a few weeks of getting more to grips with how the discovery process works I can see the error in my previous opinion.

It is more to do with the component set up procedure requiring the mqtt host to be ready to be able to read the config for the entities, rather than just a simple file.

Would be interesting if a new device/entity published via mqtt discovery could trigger a reload of the relevant platform but that is a different matter.

Closing the issue as it is not hassio or addon related.
