### ISSUE TITLE
Can't upgrade from 0.81.6 to 0.82.1: 404 Client Error: Not Found ("manifest for homeassistant/tinker-homeassistant:0.82.1 not found")

### ISSUE THREAD

**Issue by mbo18** [home-assistant/hassio#813]
I'm using Hassio 2.2 with a tinkerboard. I can't upgrade to 0.82.1 from 0.81.6:

> 18-11-16 09:35:28 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.82.1
> 18-11-16 09:35:28 INFO (SyncWorker_12) [hassio.docker.interface] Update Docker 0.81.6 with homeassistant/tinker-homeassistant:0.82.1
> 18-11-16 09:35:28 INFO (SyncWorker_12) [hassio.docker.interface] Pull image homeassistant/tinker-homeassistant tag 0.82.1.
> 18-11-16 09:35:29 ERROR (SyncWorker_12) [hassio.docker.interface] Can't install homeassistant/tinker-homeassistant:0.82.1 -> 404 Client Error: Not Found ("manifest for homeassistant/tinker-homeassistant:0.82.1 not found").
> 18-11-16 09:35:29 WARNING (MainThread) [hassio.homeassistant] Home Assistant is already running!
> 18-11-16 09:35:29 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.82.1

I have also issues with snapshoot, I can't download it. I have a 'File not found' error. It seems to be related to the api_password that I removed from my configuration.yaml file.

**Comment by pvizeli** [comment]
Fix. There was an issue with Dockerfile

**Comment by mbo18** [comment]
Nice! Thank you

**Comment by thepapamaan** [comment]
Having the exact same issue for the last 12 hours. Several attempts made.
