### ISSUE TITLE
Hassio 0.82.0 to 0.82.1 500 Server Error

### ISSUE THREAD

**Issue by erwinvos72** [home-assistant/hassio#830]
In the dashboard (see docx) i see there is an upgrade to 0.82.1. When i click the update button, nothing happens.
My log shows the following:

18-11-21 09:43:43 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
18-11-21 10:13:43 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
18-11-21 10:20:08 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.82.1
18-11-21 10:20:08 INFO (SyncWorker_10) [hassio.docker.interface] Update Docker 0.82.0 with homeassistant/raspberrypi3-homeassistant:0.82.1
18-11-21 10:20:08 INFO (SyncWorker_10) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.82.1.
18-11-21 10:20:10 ERROR (SyncWorker_10) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.82.1 -> 500 Server Error: Internal Server Error ("readlink /var/lib/docker/overlay2/l: invalid argument").
18-11-21 10:20:10 WARNING (MainThread) [hassio.homeassistant] Home Assistant is already running!
18-11-21 10:20:10 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.82.1

So, i receive an 500 Server Error, but last line says Succesful run Home Assistant 0.82.1

In System i see that i have the latest version 140 (see docx). 

So do ik have version 0.82.1, still 0.82.0 or partially parts of both?

[Doc2.docx](https://github.com/home-assistant/hassio/files/2603839/Doc2.docx)

**Comment by pvizeli** [comment]
I think your UI is broken. Try to cleanup your cache

**Comment by erwinvos72** [comment]
Thanks for the answer. Which cache do you mean and where can i do this?
