### ISSUE TITLE
Trigger a event when snapshot creation is finished

### ISSUE THREAD

**Issue by d0ugal** [home-assistant/hassio#839]
It would be great if a HA event were triggered when snapshot creation has finished. This would allow me to do the following.

1. Automation triggers snapshot creation at 02:00:00
2. Second automation is triggered by the snapshot completion event and backs up the snapshot

Currently I need to guess how long it will take between step 1 and 2. To be safe I end up with a really long time, but it would be better to backup sooner.

**Comment by 3v1n0** [comment]
Something can be done on this as per https://github.com/home-assistant/supervisor/pull/3305 ?
