### ISSUE TITLE
Breaking Change - Add upload and download sensors and component for asuswrt #17757

### ISSUE THREAD

**Issue by deddc23efb** [home-assistant/hassio#849]
**Home Assistant release with the issue:**

**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

The changes associated with introducing the ASUS WRT component have borked existing working features in device_trackers.  I don't understand how the priority of download/upload sensors superseded presence detection but ok... 

There should be road map item plan to add the dropped functionality (and some documentation please) to the new component.,

**Comment by cbrherms** [comment]
Assuming you meant to post this in [home-assistant/home-assistant](https://github.com/home-assistant/home-assistant) ?

**Comment by deddc23efb** [comment]
Well, no the break that affected me was in hassio. It may be that the documentation is the only problem at this point.  With the help of others I confirmed that the basic functionality is fine with a device_tracker updated and the ASUS WRT component added to configuration.yaml

**Comment by deddc23efb** [comment]
may as well close this.
