### ISSUE TITLE
Custom component package install fails on Hassio

### ISSUE THREAD

**Issue by danielsjf** [home-assistant/hassio#850]
**Home Assistant release with the issue:**
0.83.3

**Operating environment (HassOS/Generic):**
HassOs

**Description of problem:**
I'm trying to configure the [irceline custom_component](https://github.com/danielsjf/irceline). It uses the package airqdata which can be found on pypi. Unfortunately, after a restart, the installation of this package fails with the following error.

```
Unable to install package airqdata==0.2: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-m36c2ky0/matplotlib/
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I've tried restarting, rebooting and I even waited for a new HA version, but the problem persists.

After some Googling, I found that this is usually due to an [outdated setuptools](https://github.com/palantir/python-language-server/issues/370). Since I'm running it under Hassio, I was wondering if there is a way to update the package. The only thing I could find regarding upgrading Hass.io/HassOs was the [official upgrade of Home Assistant](https://www.home-assistant.io/hassio/), but not individual packages.

There has been a [similar issue](https://github.com/home-assistant/home-assistant/issues/13325) in the past, but this was closed without solution.

A [similar issue](https://github.com/home-assistant/hassio/issues/453) with a build-in component has been solved previously as well.

**Comment by frenck** [comment]
Home Assistant in Hass.io now runs on the latest Python, PIP, Wheel & setuptools.
