### ISSUE TITLE
How to Find IP address of Hassio

### ISSUE THREAD

**Issue by imcoltanmay** [home-assistant/hassio#855]
**Home Assistant release with the issue:**

**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
