### ISSUE TITLE
After restoring from snapshot noder-red addon fails to start

### ISSUE THREAD

**Issue by casperklein** [home-assistant/hassio#860]
**Home Assistant release with the issue:**
0.84.3

**Operating environment (HassOS/Generic):**
HassOS

**Description of problem:**

 I have two Hassio installations. One in a VM (for staging --> VMDK Version) and one running on a RPI3 (Raspberry Pi 3 Model B and B+ 64bit Image). When taking a Hassio snapshot in the VM and restoring to the RPI, node-red addon fails to start:

`
INFO (SyncWorker_12) [hassio.docker.interface] Clean hassioaddons/node-red-aarch64 Docker application
ERROR (SyncWorker_12) [hassio.docker] Can't start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyS1": no such file or directory")
`
## Expected behavior

node-red should properly start after restoring

## Actual behavior

node-red is not able to start after restoring

## Workaround

Uninstalling node-red addon, then installing again fixes the issue. The good thing at this point, my node-red flows are not affected by the uninstalling and are present after fresh installation of the addon😃 

## fyi

It doesn't seem to be an issue with the addon itself: https://github.com/hassio-addons/addon-node-red/issues/93#issuecomment-448967117

**Comment by PerGon** [comment]
Having the same issue! Restarting hass.io and node-red breaks - the message is the same as OP posted (in my case is ttyAMC3)

**Comment by casperklein** [comment]
Update: Since HA 0.86 (in my tests) all addons fail to start after restore to my RPI:

    [FATAL tini (6)] exec /init failed: Exec format error

Since Node-Red stores the data outside of the container, reinstalling is possible without losing data. 

However addons like InfluxDB & Grafana do NOT store their data outside of the container. Reinstalling them leads to data loss if you do not use specific backup/restore functions provided by the software in questions.

**Comment by pvizeli** [comment]
can you post:
`docker image ls`?

Could be that is the new arch selector they run amok with change the platform now. Can you also post the output of supervisor from restore?

**Comment by casperklein** [comment]
Thank you, now the addons are restored correctly again, except for the node red addon.

Current state is now, as in my first post:

```
19-02-25 12:03:38 ERROR (SyncWorker_12) [hassio.docker] Can't start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyS1": no such file or directory")
19-02-25 12:03:38 ERROR (MainThread) [hassio.snapshots.snapshot] Can't restore snapshot for a0d7b954_nodered
```

**Comment by pvizeli** [comment]
They add `/dev/ttyS1` to container because it has seen that inside udev logs. Look like that device don't exist? Can you confirm that on the host? Is the device `/dev/ttyS1` inside add-on config.json?

**Comment by frenck** [comment]
@pvizelli

None of the community add-ons have hardcoded "optional" devices. Add-on config: https://github.com/hassio-addons/addon-node-red/blob/master/node-red/config.json

**Comment by casperklein** [comment]
Yes, /dev/ttyS1 doesn't exist on my RPI.

**Comment by cbrherms** [comment]
Just ran in to the same issue after doing full snapshot on my NUC, copying remotely, then installing proxmox and setting up a hassio/hassos vm and restoring.

```
19-03-26 23:31:43 INFO (MainThread) [hassio.snapshots] Partial-Restore 19ea9976 start
19-03-26 23:31:57 INFO (MainThread) [hassio.snapshots] Restore 19ea9976 old add-ons
19-03-26 23:31:57 INFO (MainThread) [hassio.addons.addon] Restore config for addon a0d7b954_nodered
19-03-26 23:31:57 INFO (MainThread) [hassio.addons.addon] Restore/Install image for addon a0d7b954_nodered
19-03-26 23:31:57 INFO (SyncWorker_8) [hassio.docker.interface] Pull image hassioaddons/node-red-amd64 tag 2.0.2.
19-03-26 23:31:58 INFO (SyncWorker_8) [hassio.docker.interface] Tag image hassioaddons/node-red-amd64 with version 2.0.2 as latest
19-03-26 23:31:58 INFO (MainThread) [hassio.addons.addon] Restore data for addon a0d7b954_nodered
19-03-26 23:31:59 ERROR (SyncWorker_10) [hassio.docker] Can't start addon_a0d7b954_nodered: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyS28": no such file or directory")
19-03-26 23:31:59 ERROR (MainThread) [hassio.snapshots.snapshot] Can't restore snapshot for a0d7b954_nodered
19-03-26 23:32:00 INFO (MainThread) [hassio.snapshots] Partial-Restore 19ea9976 done
```

**Comment by jsiemek** [comment]
Hi!

I survived it.

Simply create symbolic link named /dev/ttyS28 to any existing /dev/ttyXXX.

Then restore snapshot. 

Later on it will work without this symlink.

It’s wired error in node-red snapshot.

Jarek





Wysłane z iPhone'a

**Comment by zox-gh** [comment]
Any system solution/fix to this issue yet?
I confirm suffering same prob, just the opposite way then the original post:
RPi > create shapshot > copy snapshot to VM (hyper-v) > restore snapshot = all works except node red (wont start at all)
Apparently it has to do with changing machine/environment.

**Comment by pvizeli** [comment]
Is fix with 163 but only for new add-ons. Currently, you need to edit `addons.json` and clean up the device settings for that add-ons. A device check comes later but is not done jet with udev.

**Comment by casperklein** [comment]
@pvizeli What do you mean by "only for new add-ons"? I just tried again and restore works fine. Node-Red started without an error 👍
