### ISSUE TITLE
shell commands

### ISSUE THREAD

**Issue by TonyHultqvist** [home-assistant/hassio#864]
Been looking around the whole community for a answer. 

Why is it so damm hard to run bash script shell commands from hassio. 
I've been through permission rights and paths and nothing is left out by now. 
Do you have some hidden user inside hassio executing the bash or what's the issue with not making every file inside of /config/ with chmod 777/750/ +x executable for the hassio user? By looking around the community and it seams like this is a bug more than a user error.

**Comment by frenck** [comment]
Not sure what you are trying to do.
Could you provide a use-case?

**Comment by TonyHultqvist** [comment]
Found another solution to this problem. But just having hassio stateing the full return off what’s going on with the shell reruns after after an error would be much appreciated. Or building in support for running .sh files and returning terminal errors in the hassio log on permission rights and such.
