### ISSUE TITLE
Every successful API request from addon spams log

### ISSUE THREAD

**Issue by akx** [home-assistant/hassio#865]
**Home Assistant release with the issue:**
0.84.6

**Operating environment (HassOS/Generic):**
HassOS

**Supervisor logs:**
n/a

**Description of problem:**

My addon https://github.com/akx/hass-ruuvitag POSTs into the Home Assistant API via the hass.io proxy. If one has 3 Ruuvitag sensors with all properties enabled, using the default update interval, it makes 24 requests every 30 seconds, which means 

https://github.com/home-assistant/hassio/blob/7a87d2334a09eacfa95280db1b9079d47c349c3f/hassio/api/proxy.py#L37-L38

will also be triggered for each POST request, quickly spamming logs full of useless information. :(

* Is the `hassio.api.proxy` log level changeable to something higher than `INFO`, to avoid the spam?
* Is there a mass update API I could use instead of having to make a POST request for each sensor value?

**Comment by sabeechen** [comment]
I've [recently authored an add-on](https://github.com/sabeechen/hassio-google-drive-backup) that uses the APIs and a number of users now have [expressed concern](https://github.com/sabeechen/hassio-google-drive-backup/issues/13) over how it pollutes their supervisor's logs.

Is there a good reason this is logged at INFO?  It really seems like a DEBUG kind of thing to me but I won't pretend I know what yall's logging philosophy is.  

If I make a PR to change it to DEBUG will somebody from the project look at it for me?

**Comment by sabeechen** [comment]
I've [created a pr](https://github.com/home-assistant/hassio/pull/992) to change the log level from info to debug, I'd appreciate if someone from the project could either look at it or tell me to eat my hat.
