### ISSUE TITLE
Use pypy/IronPython instead of cpython

### ISSUE THREAD

**Issue by arontsang** [home-assistant/hassio#866]
Given that hassio is often run on under powered boxes, we could increase performance and lower start up times by switching our runtime to Pypy or IronPython could help improve performance (assuming the compiler cache is put on a docket volume).

**Comment by miguelgilmartinez** [comment]
> Given that hassio is often run on under powered boxes, we could increase performance and lower start up times by switching our runtime to Pypy or IronPython could help improve performance (assuming the compiler cache is put on a docket volume).

That's an excellent idea. I have googled it but no results. Maybe HA cannot run on Pypy for some reason.

**Comment by arontsang** [comment]
Seems that the maintainer won't even take a look at this.

I've recently found that even in my x64 server, that the History tab is really slow due to the python bottlenecking.

I'm disappointed that the maintainers won't look at performance as an issue.
