### ISSUE TITLE
Hassio VMDK image does not recognize USB-SERIAL CC2530 adapter

### ISSUE THREAD

**Issue by fcasarsa** [home-assistant/hassio#868]
**Home Assistant release with the issue:** 

HassOS 1.13

**Operating environment (HassOS/Generic):**
VMDK running on xigmanas hypervisor

**Supervisor logs:**
`18-12-29 13:37:34 INFO (MainThread) [__main__] Initialize Hass.io setup
18-12-29 13:37:34 INFO (MainThread) [__main__] Setup HassIO
18-12-29 13:37:34 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 141
18-12-29 13:37:34 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1
18-12-29 13:37:34 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
18-12-29 13:37:34 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1
18-12-29 13:37:34 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
18-12-29 13:37:34 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /
18-12-29 13:37:34 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: de.pengutronix.rauc - /
18-12-29 13:37:34 INFO (MainThread) [hassio.host.info] Update local host information
18-12-29 13:37:34 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
18-12-29 13:37:34 INFO (MainThread) [hassio.host.services] Update service information
18-12-29 13:37:34 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
18-12-29 13:37:34 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
18-12-29 13:37:34 INFO (MainThread) [hassio.host.services] Reload local service hassos-apparmor.service
18-12-29 13:37:34 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
18-12-29 13:37:34 INFO (MainThread) [hassio.hassos] Detect HassOS 1.13 on host system
18-12-29 13:37:34 INFO (SyncWorker_1) [hassio.docker.hassos_cli] Found HassOS CLI homeassistant/amd64-hassio-cli with version 7
18-12-29 13:37:34 INFO (SyncWorker_0) [hassio.docker.interface] Attach to image homeassistant/qemux86-64-homeassistant with version 0.84.6
18-12-29 13:37:34 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/git/7ad98f9c repository
18-12-29 13:37:34 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/git/a0d7b954 repository
18-12-29 13:37:34 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/core repository
18-12-29 13:37:34 INFO (MainThread) [hassio.addons] Load add-ons: 50 all - 50 new - 0 remove
18-12-29 13:37:34 INFO (SyncWorker_4) [hassio.docker.interface] Attach to image homeassistant/amd64-addon-ssh with version 4
18-12-29 13:37:34 INFO (SyncWorker_5) [hassio.docker.interface] Attach to image homeassistant/amd64-addon-mosquitto with version 4
18-12-29 13:37:34 INFO (SyncWorker_6) [hassio.docker.interface] Attach to image homeassistant/amd64-addon-configurator with version 2
18-12-29 13:37:34 INFO (SyncWorker_3) [hassio.docker.interface] Attach to image homeassistant/amd64-addon-samba with version 8
18-12-29 13:37:34 INFO (SyncWorker_9) [hassio.docker.interface] Attach to image dwelch2101/zigbee2mqtt-amd64 with version 1.0.1
18-12-29 13:37:34 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
18-12-29 13:37:35 INFO (MainThread) [hassio.snapshots] Found 0 snapshot files
18-12-29 13:37:35 INFO (MainThread) [hassio.discovery] Load 1 messages
18-12-29 13:37:35 INFO (MainThread) [__main__] Run Hass.io
18-12-29 13:37:35 INFO (MainThread) [hassio.misc.dns] Start DNS port forwarding for host add-ons
18-12-29 13:37:35 INFO (MainThread) [hassio.core] Ignore Hass.io auto updates on dev channel
18-12-29 13:37:35 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
18-12-29 13:37:35 INFO (MainThread) [hassio.addons] Startup initialize run 0 add-ons
18-12-29 13:37:35 INFO (MainThread) [hassio.addons] Startup system run 1 add-ons
18-12-29 13:37:35 INFO (SyncWorker_4) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-mosquitto with version 4
18-12-29 13:37:35 INFO (MainThread) [hassio.services.mqtt] Set core_mosquitto as service provider for mqtt
18-12-29 13:37:35 INFO (MainThread) [hassio.discovery] Duplicate discovery message from core_mosquitto
18-12-29 13:37:40 INFO (MainThread) [hassio.addons] Startup services run 3 add-ons
18-12-29 13:37:41 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-12-29 13:37:42 INFO (SyncWorker_3) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-ssh with version 4
18-12-29 13:37:42 INFO (SyncWorker_5) [hassio.docker.addon] Start Docker add-on dwelch2101/zigbee2mqtt-amd64 with version 1.0.1
18-12-29 13:37:47 INFO (SyncWorker_8) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.84.6
18-12-29 13:37:57 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
18-12-29 13:37:57 INFO (MainThread) [hassio.addons] Startup application run 1 add-ons
18-12-29 13:37:58 INFO (SyncWorker_3) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-configurator with version 2
18-12-29 13:37:59 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/persistent_notification/create access from core_configurator
18-12-29 13:37:59 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
18-12-29 13:38:05 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
18-12-29 13:38:05 INFO (MainThread) [hassio.core] Hass.io is up and running`

**Description of problem:**

hassio setup + zigbee2mqtt plugin does not recognize USB-serial adapter ( CC2530 + https://www.amazon.com/ZigBee-CC2530-Baseboard-Functional-Expansion/dp/B07GWV476R ) 

from hassio root console did a dmesg first with the USB serial that is NOT working then with a USB serial that works. Windows recognize this a CH340 USB-SERIAL

![serialnotrecon](https://user-images.githubusercontent.com/5887149/50538994-69790d00-0b79-11e9-9fd6-ecaa33e413ed.png)

I suppose that udev does not recognizes the proper IDVENDOR and IDPRODUCT.

Bye.

**Comment by pvizeli** [comment]
Fixed with on HassOS within next release
