### ISSUE TITLE
connection refused to HA 192.168.x.x:8123

### ISSUE THREAD

**Issue by pcopa** [home-assistant/hassio#870]
**Home Assistant release with the issue:**
hassos_rpi3-1.13.img
V1.4.0

**Operating environment (HassOS/Generic):**
rpi3+; win10; atom

**Supervisor logs:**

**Description of problem:**
Everything seems to be working fine from setup to reinstalling all the Tasmota modules with "homeassistant.restart", but then after a RPI reboot or power fail, the system boots up as normal but I get the " refused to connect." message that won't go away.
It looks like everything is working in the background because "samba" and "tasmota assistant" are still working and the "home-assistant.log" is collecting data. The Rpi green light is blinking as normal. The web link is just refusing to connect. The only way to get rid of this is to start all over.  

This is the home-assistant.log using samba after a failing reboot.

> 2019-01-02 13:57:23 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=5 from 2019-01-02 18:46:10.327970)
2019-01-02 13:57:27 ERROR (SyncWorker_5) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2019-01-02 13:57:27 ERROR (SyncWorker_15) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2019-01-02 14:14:39 WARNING (MainThread) [homeassistant.components.binary_sensor.mqtt] No matching payload found for entity: gardoor with state_topic: tele/mrf/RESULT
2019-01-02 14:14:39 WARNING (MainThread) [homeassistant.components.binary_sensor.mqtt] No matching payload found for entity: kitmrf2 with state_topic: tele/mrf/RESULT

(The bottom warnings are normal)

I've repeated this >20 times to try an isolate the issue with no success.
Any help will be greatly appreciated

**Comment by billjwolff** [comment]
I have a similar error with the same image on a rpi3+. The web site was working fine until I added a component followed by a restart. I can't access anything now.

**Comment by billjwolff** [comment]
The component I am adding is an Insteon hub2. I think I have the YAML format correct. The Configuration validates but after restart the web page never shows.

**Comment by pcopa** [comment]
@billwolff You also have to be very patient, because I've seen it take more than 1 hour before the reconnect message disappears. As long as the green light on the Rpi blinks ever so now and then, its working.  If its out for >1 minute, its dead and needs a reboot.

**Comment by billjwolff** [comment]
I am new to HAAS but a long time computer consultant. Building the rpi3+ and doing the initial install were surprisingly easy. I just need some advice on Insteon integration. I have 4 hubs in a large house with 70 devices. Do I need to add a component in configuration for each hub?
