### ISSUE TITLE
Setup Away Mode with NMap IP tracker

### ISSUE THREAD

**Issue by Piedone86** [home-assistant/hassio#871]
**Home Assistant release with the issue:**
0.84.2

**Operating environment (HassOS/Generic):**
Hass.io on RaspberryPI 1 B

**Supervisor logs:**

**Description of problem:**
I've added NMap on Hass.Io to create an automation that set the "Away Mode" once my phone IP + my girlfriend phone IP are not connected . In reverse, once one of us come home and a single phone IP connects, the "Away Mode" should switched off. 
The "Away Mode" is currently connected to Netatmo thermostat and if I manually force it from the frontend, it switch correctly the heather off. 

The automation has been set up from the "automation" front-end composer and it's not working.
You can see in attachment the code it created.

![image](https://user-images.githubusercontent.com/46340303/50628147-174c3900-0f37-11e9-8d4d-3e63026d9f34.png)

Do you have any suggestion on this? Thanks in advance for your help

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
