### ISSUE TITLE
Feature Request: have a hassio Web UI bash terminal for each hassio addon docker

### ISSUE THREAD

**Issue by Aterfax** [home-assistant/hassio#876]
Adding the functionality to get a bash shell in each docker for Hassio addons in the Hassio Web UI would probably be very handy.

This feature was added in unraid a while back and I find use of it occasionally.

i.e. webterminal for `docker exec -it <mycontainer> bash`

**Comment by frenck** [comment]
Not sure if this should be added to the "core".
Currently, there are 3 options available:

- Via the HostOS (debug SSH access in HassOS)
- Via the Community SSH & Web Terminal add-on
- Via the Portainer addon (which has matches your wish/description).
