### ISSUE TITLE
Feature Request: have a CPU load % for each Hassio addon

### ISSUE THREAD

**Issue by Aterfax** [home-assistant/hassio#877]
Adding a CPU load % for each hassio addon would be useful in terms of seeing what addons are causing what kind of load in addition to indicating if an addion is overloaded, overloading the host or is having some kind of issue.

Would be useful to see this in the Hassio dashboard tab!

**Comment by frenck** [comment]
This feature is already available in Hass.io itself but is simply not exposed in the frontend.
I guess this issue should be filed with the Home Assistant Polymer repository.
