### ISSUE TITLE
Home Assistant does not start without Ethernet Connection on reboot.

### ISSUE THREAD

**Issue by gb53smith** [home-assistant/hassio#883]
Home Assistant 0.85.0
Hassio supervisor 141
HassOS 2.2
Raspberry PI 3

On house power restoration my router is a little slow at starting up.   When HassOS looks for a LAN connection (Ethernet cable), its not there.  As a result, Home Assistant is never started.  I have to manually cycle the power on the Raspberry PI 3 to restore Home Assistant after the router is up.
I don't remember Hassbian having this issue.  While HassOS is great for updates and addons it still must recover from power outages to be trusted with my Home Automation while on vacation.

My only work around is to provide extra hardware to power up the router and Raspberry PI  in sequence.

Is there a way in HassOS (I assume) to wait for a LAN connection or to try again in a loop?

**Comment by gb53smith** [comment]
The issue seems to be related to reboot from shutdown in general with an Ethernet connection.
An [other forum](https://forum.libreelec.tv/thread/12013-raspberry-pi-3-b-reboot-problems/) has reported a race condition in the Ethernet driver which may be in the kernel that I am using.
HASSOS DOES wait for  Ethernet connection if I follow this experimental sequence home assistant/hassio comes back on my UI.

1. hassio ho shutdown
2. wait 15 seconds
3. remove Ethernet cable from rasp pi
4. Momentarily short RUN pin on the rasp pi
5. Wait 5 minutes
6. connect Ethernet cable to rasp pi
7. Wait 2 minutes

In this sequence hassio does not come back
1. hassio ho shutdown
2. wait 15 seconds
3. power cycle
The Ethernet connect comes up for about 30 seconds and then DISCONNECTS.
A second power cycle or RUN short is required to get hassio back.

A second power cycle is very undesirable if you are on vacation and want to access hassio after a power outage.

**Comment by gb53smith** [comment]
SOLVED!!!
I rebuilt my HA system using the latest hassio image [here](https://github.com/home-assistant/hassos/releases/download/1.13/hassos_rpi3-1.13.img.gz).
Not too difficult if you have a recent snapshot saved on your Windows 10 PC.
The HassOS image version shows up under Hass.io -> SYSTEM

Now I can re-boot without the Ethernet cable, reconnect it a few minutes later 
and hassio returns.

My theory is that the image I was using had a defect in the Ethernet driver.

I would encourage everyone to use the hassos 1.13 image for their Raspberry Pi 3


CLOSED

**Comment by andrejvi** [comment]
I have this problem with my HA system, only difference is that a reboot doesnt work. So i end up flashing my sdcard back to image.

Home Assistant 2023.1.4
Supervisor 2022.12.1
Operating System 9.4
Raspberry PI 4

**Comment by Photogad** [comment]
I am also having this problem

**Comment by alexschultze** [comment]
2026 and still the same issue.

Installation method Home Assistant OS
Core 2026.5.1
Supervisor 2026.05.1
Operating System 17.3 
Raspberry PI 3B.

Boots fine with Ethernet, no proper boot without ethernet.
