### ISSUE TITLE
Cannot read property 'entity_id' of undefined

### ISSUE THREAD

**Issue by febrez** [home-assistant/hassio#887]
**Home Assistant release with the issue:**
homeassistant: 0.85.1

**Operating environment (HassOS/Generic):**
arch: armhf
channel: stable
hassos: "1.13"
machine: raspberrypi2
supervisor: "141"

**logs:**
 ERROR (MainThread) [frontend.js.latest.201901091] http://hassio:8123/frontend_latest/app-19bfb9ea.js:89:305 Uncaught TypeError: Cannot read property 'entity_id' of undefined

**Description of problem:**
Often happening

**Comment by frenck** [comment]
Could you provide some more information on where this error is produced? Which page? Browser? What were you doing at the time?

**Comment by febrez** [comment]
Here is configuration.yaml entry :
```
frontend:
  javascript_version: latest
```
I'm using lovelace in yaml mode.

**Comment by frenck** [comment]
@febrez Could you please tell a story of what you did, where it exactly broke and which browser you are using? Did you flush you cache? tried a different browser? 

Would be great if you could answer all the questions, instead of a short reply 😉  👍
