### ISSUE TITLE
Authentication via Websocket API Issues

### ISSUE THREAD

**Issue by mewt666** [home-assistant/hassio#897]
Hi, 

I'm running hass.io using docker over raspbian. I have installed node-red (v1.2.4) and have been trying to login into the node-red instance using my home assistant credentials (owner account). The API request however appears to fail during the authentication request as per the below home assistant log, right after a restart of my PI:

Jan 19 22:52:44 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:52:44 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
Jan 19 22:52:44 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:52:44 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
Jan 19 22:53:12 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:53:12 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home Assistant startup!
Jan 19 22:53:12 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:53:12 INFO (MainThread) [hassio.addons] Startup application run 1 add-ons
Jan 19 22:53:12 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:53:12 WARNING (MainThread) [hassio.addons.addon] a0d7b954_nodered already running!
Jan 19 22:53:18 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:53:18 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
Jan 19 22:53:18 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:53:18 INFO (MainThread) [hassio.core] Hass.io is up and running
Jan 19 22:53:31 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:53:31 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
Jan 19 22:53:31 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:53:31 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
Jan 19 22:53:45 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:53:45 INFO (MainThread) [hassio.auth] Auth request from a0d7b954_nodered for mewt
Jan 19 22:54:18 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:54:18 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
Jan 19 22:54:18 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:54:18 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
Jan 19 22:54:46 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:54:46 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/:
Jan 19 22:54:46 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:54:46 INFO (MainThread) [hassio.auth] Home Assistant not running, check cache
Jan 19 22:54:46 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:54:46 WARNING (MainThread) [hassio.auth] No cache hit for mewt
Jan 19 22:55:05 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:55:05 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
Jan 19 22:55:05 cirith-ungol hassio-supervisor[1696]: 19-01-19 21:55:05 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered

Node-red logs the following error:

19 Jan 21:54:18 - [info] [server:Home Assistant] WebSocket Closed http://hassio/homeassistant
19 Jan 21:54:18 - [debug] [server:Home Assistant] config server event listener closed
19 Jan 21:54:18 - [debug] [server:Home Assistant] WebSocket Connecting http://hassio/homeassistant
19 Jan 21:54:18 - [debug] [server:Home Assistant] config server event listener connecting
19 Jan 21:54:18 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
19 Jan 21:54:18 - [debug] [server:Home Assistant] config server event listener connected
19 Jan 21:54:46 - HA Auth - Failed to authenticate: mewt

Any ideas or pointers ? Is this an issue with the API or a configuration issue ?

**Comment by 12345oo54321** [comment]
Home assistant menu > Hass.io > Add-On Store 
           (add-on details) -- Node-Red 
           in "Config" be sure to remove usernames and passwords. 

  "http_node": {
    "username": "",    << no user
    "password": ""     << no pass
  },
  "http_static": {
    "username": "",
    "password": ""
  },

Reboot you'r machine and log on with Home Assistant Credentials.
Should work.

**Comment by krovachek** [comment]
> Home assistant menu > Hass.io > Add-On Store
> (add-on details) -- Node-Red
> in "Config" be sure to remove usernames and passwords.
> 
> "http_node": {
> "username": "", << no user
> "password": "" << no pass
> },
> "http_static": {
> "username": "",
> "password": ""
> },
> 
> Reboot you'r machine and log on with Home Assistant Credentials.
> Should work.

I've tried it but doesn"t work.

**Comment by mewt666** [comment]
I'm not in a position to try and fix the above problem at the moment as I changed my setup from docker on rpi to docker on an x86 pc (running ubuntu) and node-red worked immediately out of the box. (No changes to included config). I will soon be changing back to a new RPI 3 B+ and will check again if the problem persists, however it seems to me that the architecture may have played a part in this issue.

**Comment by krovachek** [comment]
Reverse the situation I changed my RPI Hassio setup to Ubuntu docker on NUC. The NodeRED is working now but this problem causes a  hanging problem during the restart of Hassio. While the NodeRed is not installed the restart time is 20 seconds, after it 2 minutes and doesn't matter if I remove the NodeRed the restart time remains 2 minutes. Before that I tried the win10+vm combo without this kind of failure.

**Comment by pvizeli** [comment]
Hassio cache the credential for logging but we don't store that. If you restart the device and home assistant is not alive, you can't log in until home assistant is up and can validate the login. Maybe we should store the logging cache to make it persistent over reboots...
