### ISSUE TITLE
Delete Snapshot does not work 

### ISSUE THREAD

**Issue by hwestrel** [home-assistant/hassio#906]
**Home Assistant release with the issue:**
0.86.3

**Operating environment (HassOS/Generic):**
Hass.io supervisor 142
System | Resin OS 2.3.0+rev1
Raspberry PI 3 B

**Supervisor logs:**

19-01-27 14:24:32 INFO (MainThread) [hassio.snapshots] Full-Snapshot aefef364 start
19-01-27 14:24:32 INFO (MainThread) [hassio.snapshots] Snapshot aefef364 store Add-ons
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_configurator
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on 7be23ff5_dropbox_sync
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_check_config
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_ssh
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_samba
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on a0d7b954_nodered
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_duckdns
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_configurator
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_mosquitto
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon 7be23ff5_dropbox_sync
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_check_config
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_samba
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon a0d7b954_nodered
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_mosquitto
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_ssh
19-01-27 14:24:33 INFO (MainThread) [hassio.addons.addon] Finish snapshot for addon core_duckdns
19-01-27 14:24:33 INFO (MainThread) [hassio.snapshots] Snapshot aefef364 store folders
19-01-27 14:24:33 INFO (SyncWorker_13) [hassio.snapshots.snapshot] Snapshot folder addons/local
19-01-27 14:24:33 INFO (SyncWorker_6) [hassio.snapshots.snapshot] Snapshot folder share
19-01-27 14:24:33 INFO (SyncWorker_11) [hassio.snapshots.snapshot] Snapshot folder homeassistant
19-01-27 14:24:33 INFO (SyncWorker_19) [hassio.snapshots.snapshot] Snapshot folder ssl
19-01-27 14:24:33 INFO (SyncWorker_6) [hassio.snapshots.snapshot] Snapshot folder share done
19-01-27 14:24:33 INFO (SyncWorker_19) [hassio.snapshots.snapshot] Snapshot folder ssl done
19-01-27 14:24:33 INFO (SyncWorker_13) [hassio.snapshots.snapshot] Snapshot folder addons/local done
19-01-27 14:25:00 INFO (SyncWorker_11) [hassio.snapshots.snapshot] Snapshot folder homeassistant done
19-01-27 14:25:00 INFO (MainThread) [hassio.snapshots] Full-Snapshot aefef364 done
-------------------
No log entry when "deleting" via GUI....
Browser tab with HA hangs..
Delete snapshot via CLI below.
-------------------
19-01-27 14:28:19 INFO (MainThread) [hassio.api.security] /snapshots access from core_ssh
19-01-27 14:28:28 INFO (MainThread) [hassio.api.security] /snapshots/aefef364/remove access from core_ssh
19-01-27 14:28:28 INFO (MainThread) [hassio.snapshots] Removed snapshot file aefef364
> df -h
Filesystem                Size      Used Available Use% Mounted on
none                     13.7G      3.7G      9.2G  29% /
tmpfs                   486.1M         0    486.1M   0% /dev
tmpfs                   486.1M         0    486.1M   0% /sys/fs/cgroup
/dev/mmcblk0p3          294.1M    216.8M     61.8M  78% /dev/init
/dev/mmcblk0p6           13.7G      3.7G      9.2G  29% /config
/dev/mmcblk0p6           13.7G      3.7G      9.2G  29% /ssl
/dev/mmcblk0p6           13.7G      3.7G      9.2G  29% /addons
/dev/mmcblk0p6           13.7G      3.7G      9.2G  29% /backup
/dev/mmcblk0p6           13.7G      3.7G      9.2G  29% /share
/dev/mmcblk0p6           13.7G      3.7G      9.2G  29% /data
/dev/mmcblk0p6           13.7G      3.7G      9.2G  29% /etc/resolv.conf
/dev/mmcblk0p6           13.7G      3.7G      9.2G  29% /etc/hostname
/dev/mmcblk0p6           13.7G      3.7G      9.2G  29% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   486.1M         0    486.1M   0% /proc/timer_list
tmpfs                   486.1M         0    486.1M   0% /proc/timer_stats
tmpfs                   486.1M         0    486.1M   0% /proc/sched_debug
tmpfs                   486.1M         0    486.1M   0% /sys/firmware

**Description of problem:**
- I can create snapshots, but not delete them via GUI. 
HA UI hangs after clicking the delete icon.
User: owner account

BUT: it I can still delete via "hassio snapshots remove" command.

**Comment by frenck** [comment]
Same answer as on your other issue. You are still running ResinOS. I strongly recommend you to upgrade to HassOS.

**Comment by hwestrel** [comment]
Solved!  upgraded to HassOS.
