### ISSUE TITLE
Can't uninstall  Add-ons

### ISSUE THREAD

**Issue by hwestrel** [home-assistant/hassio#907]
**Home Assistant release with the issue:**
0.86.3
**Operating environment (HassOS/Generic):**
Hass.io supervisor 142
System | Resin OS 2.3.0+rev1
Raspberry PI 3 B
**Supervisor logs:**
- No system log entries generated during or after failed uninstalls.

**Description of problem:**
I can install new add-ons, but not uninstall via GUI, with "owner" account.
I have tried with different addons. Like "Check Home Assistant configuration" or "configurator".
Result, Browser tab with HA hangs.
Delete via CLI, hassio addons uninstall <slug> works

**Comment by frenck** [comment]
Now sure what the issue could be, nevertheless, you are still running ResinOS.
I strongly recommend you to upgrade to HassOS.

**Comment by hwestrel** [comment]
Aha, Thanks.  I did not realize I had too. Thought it was just a name change....  I will try

**Comment by hwestrel** [comment]
Solved!  upgraded to HassOS.
