### ISSUE TITLE
Despite #20432, ASUSWRT ssh is still broken in HASSIO.

### ISSUE THREAD

**Issue by deddc23efb** [home-assistant/hassio#914]
Release 0.86.4 
Despite the cryptic "bump aioasuswrt " fix 20432 and 20361, ASUSWRT ssh access in hassio is still broken.  I couldn't find another open bug report so here you go.

**Comment by quarcko** [comment]
+1. Same bug appears in homekit_controller as well. Please fix...

**Comment by deddc23efb** [comment]
I've upgraded to hassio 0.87.0  and can confirm that the ASUSWRT presence detection is working again. I see positive detection from the AsusWrtDeviceScanner. 

I can't comment on the general ASUS sensors, I don't seem to have any.  I didn't use them for anything so I'm not sure whether they work or not.

If others are happy with this, I think the problem has been fixed.

**Comment by Jc2k** [comment]
Note that the current fix is a workaround until #903 is resolved and means that `asyncssh` is currently artificially locked at an old version - and we can no longer take security updates of `asyncssh` without introducing a regression again.

**Comment by pvizeli** [comment]
Should be fixed with new base images on alpine 3.9/ssl started with 0.88.0b0
