### ISSUE TITLE
Cannot update supervisor from 142 to 143

### ISSUE THREAD

**Issue by cyberjunky** [home-assistant/hassio#919]
**Home Assistant release with the issue:**

Home Assistant
0.87.0

Hass.io supervisor 142

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

19-02-10 03:09:25 INFO (SyncWorker_12) [hassio.docker.interface] Pull image homeassistant/amd64-hassio-supervisor:latest tag 143.
19-02-10 03:09:26 ERROR (SyncWorker_12) [hassio.docker.interface] Can't install homeassistant/amd64-hassio-supervisor:latest:143 -> 400 Client Error: Bad Request ("no such image: homeassistant/amd64-hassio-supervisor:latest:143: invalid reference format").
19-02-10 03:09:26 ERROR (MainThread) [hassio.supervisor] Update of Hass.io fails!

**Description of problem:**

Running Hass.io inside Docker on Ubuntu.
When trying to update supervisor from 142 to 143 by clicking update button, it fails with Error: unknown error. 
![error](https://user-images.githubusercontent.com/5447161/52536971-6456d280-2d61-11e9-908c-d48577163071.PNG)
See attachment.

The logs also have errors on downloading the image/wrong format.
I have this issue on two amd64 systems Ubuntu 18.04.1 LTS

**Comment by cyberjunky** [comment]
Updating system with latest Ubuntu updates and rebooting it updated the hassio to 143, issue was solved. No idea what was wrong, but I had this on 2 systems.

**Comment by pvizeli** [comment]
Some times, docker need a reboot :)
