### ISSUE TITLE
Bug, Hassio wrong audio HDMI detection, detected as input device. Ubuntu docker.

### ISSUE THREAD

**Issue by yevon** [home-assistant/hassio#926]
**Home Assistant release with the issue:**
Lastest 0.87.1

**Operating environment (HassOS/Generic):**
Ubuntu 18.04, docker with hass.io

**Supervisor logs:**

**Description of problem:**

serial:
/dev/ttyS31
/dev/ttyS15
/dev/ttyS13
/dev/ttyS19
/dev/ttyS26
/dev/ttyS2
/dev/ttyS11
/dev/ttyS10
/dev/ttyS1
/dev/ttyS27
/dev/ttyS4
/dev/ttyS20
/dev/ttyS23
/dev/ttyS18
/dev/ttyS14
/dev/ttyS3
/dev/ttyS21
/dev/ttyS7
/dev/ttyACM0
/dev/ttyS5
/dev/ttyS29
/dev/ttyS30
/dev/ttyS8
/dev/ttyS12
/dev/ttyS25
/dev/ttyS9
/dev/ttyS24
/dev/ttyS28
/dev/ttyS6
/dev/ttyS17
/dev/ttyS22
/dev/ttyS0
/dev/ttyS16

input:
Video Bus
HD-Audio Generic HDMI/DP,pcm=9
HD-Audio Generic HDMI/DP,pcm=3
HD-Audio Generic Mic
Power Button
HD-Audio Generic HDMI/DP,pcm=7
HD-Audio Generic HDMI/DP,pcm=8
Logitech K600 TV
HD-Audio Generic Front Line Out

disk:

gpio:

gpiochip256

audio:

**Comment by pvizeli** [comment]
Yeah, with docker 18.09.1 they block the audio access :( we working on a solution they enable audio again

**Comment by yevon** [comment]
Ok perfect if it is a known issue, thanks!

**Comment by yevon** [comment]
Any progress on this one? or any other thread were I con follow this?

**Comment by kuradi** [comment]
> 
> 
> Yeah, with docker 18.09.1 they block the audio access :( we working on a solution they enable audio again

are there any updates?

**Comment by pvizeli** [comment]
Rerun the installer and it's fix it

**Comment by yevon** [comment]
I've done it, and it didn't fix it. My audio devices are still detected as input devices instead of audio.

**Comment by kuradi** [comment]
> 
> 
> Rerun the installer and it's fix it

it means "update to 0.90"  or what?
if yes, i did but still same: no audio device.

**Comment by yevon** [comment]
Hi kuradi. I did rerun the hassio installer but it didn't work at all. I had to manually stop supervisor service with something similar to:

Full backup of hassio.

Sudo systemctl stop supervisor

Manually uninstall all hassio related dockers and all related docker images through portainer.

Rerun hassio docker installer.

All data was ok except hassio plugins, I had to restore them from the hassio backup previously made.

Now I can see some audio devices listed as "HDA intel audio device 0-9". But none of them work when I try to play some music with spotify connect plugin for example, it says that it cannot connect to the device.

**Comment by kuradi** [comment]
so basically problem still exist....

**Comment by yevon** [comment]
Not exactly same problem, now audio device list appears, but I'm not able to reproduce sound, I want to check if is something related to my setup or something related to hassio. But it should appear as "HDMI device", not HDA intel audio device 0-9.

**Comment by kuradi** [comment]
i got it working! so thank you guys.

**Comment by yevon** [comment]
Hi kuradi, can you post your hardware list and how did you solve it? I still cannot play any audio through hassio and docker on ubuntu 18.04

**Comment by kuradi** [comment]
> 
> 
> Hi kuradi, can you post your hardware list and how did you solve it? I still cannot play any audio through hassio and docker on ubuntu 18.04

i did as you suggested - removed all hassio related dockers and made new install. thats it.

hardware below

    serial:
        /dev/ttyS12
        /dev/ttyS18
        /dev/ttyS14
        /dev/ttyS28
        /dev/ttyS21
        /dev/ttyS13
        /dev/ttyS9
        /dev/ttyS17
        /dev/ttyS23
        /dev/ttyS31
        /dev/ttyS20
        /dev/ttyS29
        /dev/ttyS24
        /dev/ttyS10
        /dev/ttyS11
        /dev/ttyS30
        /dev/ttyS25
        /dev/ttyS4
        /dev/ttyS19
        /dev/ttyS0
        /dev/ttyS6
        /dev/ttyS2
        /dev/ttyS8
        /dev/ttyS16
        /dev/ttyS1
        /dev/ttyS26
        /dev/ttyS3
        /dev/ttyS5
        /dev/ttyS15
        /dev/ttyS27
        /dev/ttyS22
        /dev/ttyS7
    input:
        Sleep Button
        HDA Intel PCH Headphone Front
        USB USB Keyboard
        HDA Intel PCH Front Headphone Surround
        Lid Switch
        HDA Intel PCH Mic
        Power Button
        ITE8713 CIR transceiver
        Video Bus
        USB OPTICAL MOUSE
        HDA Intel PCH HDMI/DP,pcm=3
    disk:
        /dev/sda2
        /dev/sda
        /dev/sda1
    gpio:
        gpiochip228
        gpiochip414
        gpiochip314
        gpiochip225
        gpiochip341
    audio:
        0:
            name: HDA-Intel - HDA Intel PCH
            type: PCH
            devices:
                [object Object]
                [object Object]
                [object Object]
                [object Object]
                [object Object]
                [object Object]

**Comment by yevon** [comment]
What plugin have you used to test the audio? Text to speech? Mopidy? Spotify? What HDA-Intel device of your list are you using?. I have a very similar hardware list, but I still cannot play any audio.

**Comment by kuradi** [comment]
> 
> 
> What plugin have you used to test the audio? Text to speech? Mopidy? Spotify? What HDA-Intel device of your list are you using?. I have a very similar hardware list, but I still cannot play any audio.

mopidy addon https://github.com/bestlibre/hassio-addons/tree/master/mopidy
![audio](https://user-images.githubusercontent.com/31483391/55510082-1aee7980-5666-11e9-85a2-0f408ce2acfe.jpg)

**Comment by yevon** [comment]
Ok thanks, I discovered that I had another issue that I already reported. I coudn't play audio through two active plugins at the same time, I have to disable one of them in order to hear anithing.

**Comment by SilverWx** [comment]
Any news about this problem ?
My hassio doesn't recognize virtual sound card in VMware
