### ISSUE TITLE
Cannot install hassio.

### ISSUE THREAD

**Issue by alexchern** [home-assistant/hassio#946]
Clean install hassos-rpi2-2.10.img.gz image on the LAN connected RP 2. Stuck at:

**udevd[8]: starting eudev-3.2.7**

Tried to flush the image twice, same results....
Nothing else on the network - disabled WiFi.

Any ideas?

Thanks,

Alex

**Comment by pvizeli** [comment]
What you see in supervisor logs? `su logs` and home assistant `ha logs`

**Comment by alexchern** [comment]
Thank you for your help.
I have no idea where to find these logs. I cannot log in, as it is probably not fully up yet. Tried to find them on the SD card, no luck on Windows. If I figure out the IP, can I connect? How, with Putty? What are the credentials? So far, this is what I see:
![20190311_210153](https://user-images.githubusercontent.com/9559649/54151611-e0693680-4443-11e9-8f05-09fcd04e576b.jpg)

Once again, thank you for your help.

Alex

**Comment by alexchern** [comment]
Well, I ended up configuring static IP. Now I'm able to log in....

Alex
