### ISSUE TITLE
Automation's Stopped working after upgrading to 0.89.1

### ISSUE THREAD

**Issue by ajdezigns** [home-assistant/hassio#948]
**Home Assistant release with the issue:**

arch: armv7l
dev: false
docker: true
hassio: true
os_name: Linux
python_version: 3.7.2
timezone: America/Toronto
version: 0.89.1
virtualenv: false

**Operating environment (HassOS/Generic):**

System: HassOS 2.10
Deployment: production

**Supervisor logs:**

19-03-12 19:15:13 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh

**Description of problem:**

Automation's Stopped working after upgrading to 0.89.1 unsure why

**Comment by frenck** [comment]
This is not an issue related to Hass.io, but a change to Home Assistant which was done a while back.
see documentation about Automations on how to use the `initial_state` option with automations.

Closing issue.
