### ISSUE TITLE
Mosquitto broker (Hassio addon) breaks after 4.0->4.1 upgrade

### ISSUE THREAD

**Issue by GreenhouseAU** [home-assistant/hassio#950]
**Home Assistant release with the issue:**
0.86.4

**Operating environment (HassOS/Generic):**
Hassio

**Description of problem:**
MQTT broker has been working perfectly for the last year and then immediately breaks after 4.0->4.1 update. In the log, it goes something like:

New connection from 192.168.0.80 on port 1883.
Connection timeout.....(forget exact wording)

Nothing else has changed apart from the addon update.

**Comment by Vorchikhin** [comment]
I have the same problem too. Just backup to 4.0 version and it's working now.

**Comment by igorantolic** [comment]
No need to go back to 4.0. This is temporary solution, but not long-term.
Better just follow instructions how to adjust security. You don't need to change anything on your devices, but just add 2 files to \\hassio\share\mosquitto (where hassio is name or IP address of your own hassio server).
1) in \share create folder mosquitto
2) inside that new folder add new file named "acl.conf" and put in that file only one line:
   acl_file /share/mosquitto/acl
   be sure not to have extra space after last word
3) create also in same folder file "acl", with only one line
   topic readwrite #
   again, no spaces before start, nor after last char "#"
4) in hassio dashboard
    http://hassio.local:8123/hassio/dashboard (replace hassio.local again with your name of server)
    open Mosquitto broker, and 
4.a) in CONFIG add customize params which points to our folder we created
  "anonymous": true,
  "customize": {
    "active": true,
    "folder": "mosquitto"
  },
4.b) just click restart (of MQTT server)

Simply explained, you just gave all MQTT users (in my case anonymous, FULL rights on ALL topics.
If you want to improve security modify /share/mosquitto/acl according to detailed instructions you will find on internet
