### ISSUE TITLE
Crashed Hass.io by trying to download a snapshot 

### ISSUE THREAD

**Issue by lancelon** [home-assistant/hassio#952]
Home Assistant release with the issue: Can't currently login to see, but it's about three weeks old. Will update when I can login!

Operating environment (HassOS/Generic): HassOS

Supervisor logs: Will update when I can login!

Description of problem: Tried to download a snapshot over DuckDNS. I'm currently sat outside my home LAN. It failed immediately, and now Hass.io is unresponsive.

**Comment by frenck** [comment]
I'm closing this one, since there is nothing in here we can do to help/analyze your issue.
Feel feel to re-open when ready to provide additional logs and details.
