### ISSUE TITLE
snapshots done via gui and service call are diferent

### ISSUE THREAD

**Issue by jarzebskim** [home-assistant/hassio#954]
I created partial snapshot from GUI with homeassitant and share folders selected. All files and directories are in snapshot file but when I created service call with the same folders the snapshot file is smaller and some files and direcotries are missing. 

Snapshot from GUI:

![snapshot_gui](https://user-images.githubusercontent.com/48404550/54475501-35190280-47f2-11e9-9b3c-db71c3d40433.png)

Snapshot: Service call

![snapshot_services](https://user-images.githubusercontent.com/48404550/54475506-3fd39780-47f2-11e9-8911-3b31e41f87fc.png)

File sizes:

![size](https://user-images.githubusercontent.com/48404550/54475508-45c97880-47f2-11e9-9fa3-297b5577da6a.png)

snapshot comparsion:

![files](https://user-images.githubusercontent.com/48404550/54475511-4feb7700-47f2-11e9-93de-2f54b5394f43.png)

Home Assistant release with the issue:**
version | 0.89.2

**Operating environment (HassOS/Generic):**
rasspbian with docker 

**Hass.io supervisor**
Version | 148

**Supervisor logs:**
19-03-16 12:25:45 INFO (MainThread) [hassio.snapshots] Snapshot e30061a2 store folders
19-03-16 12:25:45 INFO (SyncWorker_2) [hassio.snapshots.snapshot] Snapshot folder share
19-03-16 12:25:45 INFO (SyncWorker_4) [hassio.snapshots.snapshot] Snapshot folder homeassistant
19-03-16 12:25:45 INFO (SyncWorker_2) [hassio.snapshots.snapshot] Snapshot folder share done
19-03-16 12:26:01 INFO (SyncWorker_4) [hassio.snapshots.snapshot] Snapshot folder homeassistant done
19-03-16 12:26:01 INFO (MainThread) [hassio.snapshots] Partial-Snapshot e30061a2 done
19-03-16 12:26:36 INFO (MainThread) [hassio.auth] Auth request from a0d7b954_nodered for emdzej
19-03-16 12:26:39 INFO (MainThread) [hassio.auth] Success login from emdzej
19-03-16 12:27:58 INFO (MainThread) [hassio.snapshots] Partial-Snapshot c2f11674 start
19-03-16 12:27:58 INFO (MainThread) [hassio.snapshots] Snapshot c2f11674 store folders
19-03-16 12:27:58 INFO (SyncWorker_12) [hassio.snapshots.snapshot] Snapshot folder homeassistant
19-03-16 12:27:58 INFO (SyncWorker_14) [hassio.snapshots.snapshot] Snapshot folder share
19-03-16 12:27:58 INFO (SyncWorker_14) [hassio.snapshots.snapshot] Snapshot folder share done
19-03-16 12:28:00 WARNING (SyncWorker_12) [hassio.snapshots.snapshot] Can't snapshot folder homeassistant: [Errno 2] No such file or directory: '/data/homeassistant/home-assistant_v2.db-shm'
19-03-16 12:28:00 INFO (MainThread) [hassio.snapshots] Partial-Snapshot c2f11674 done

**Comment by jarzebskim** [comment]
Update: Snapshot from GUI also not working from time to time. Also warning occurs:

No such file or directory: '/data/homeassistant/home-assistant_v2.db-shm'

**Comment by SalkinDK** [comment]
sam problem here.
#779

**Comment by Motive313** [comment]
I'm still having this issue. With a quick google search, I've found 3 threads about others experiencing this issue still.
