### ISSUE TITLE
Set own ntp server

### ISSUE THREAD

**Issue by Poeschl** [home-assistant/hassio#957]
Is there a possibility to set my own ntp server for time syncing?

I'm in a restricted network where the routes to the default ntp servers like `pool.ntp.org`  @are blocked.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassos/blob/dev/Documentation/configuration.md

**Comment by truglodite** [comment]
> https://github.com/home-assistant/hassos/blob/dev/Documentation/configuration.md

The documentation is a bit vague for this newb. Going from the "Local" section, if I ssh in (via ssh plugin) I have no /etc/systemd/ folder. The "Automatic" section seems to tell me to make a usb drive named 'CONFIG' with the list of folders and files, including 'timesyncd.conf'. 

Do all folders/files have to be created (left empty/blank) even if I only edit timesyncd.conf, or do I just need that one file on there? What exactly should be in this file? 

Putting it all together, if I want hassos to use an existing NTP server at 192.168.0.3, it seems I just need to boot up with a usb named "CONFIG" plugged in, with just a file named "timesyncd.conf", with only the contents:
```
[Time]
NTP=192.168.0.3
FallbackNTP=192.168.0.3
```
Correct? I also happen to be running hassos off a USB ssd via dev 3.4, not on an sd. Will this still work the same? Luckily I do have one spare USB port on my pi3 to try this with.
