### ISSUE TITLE
build.json: does not match regular expression for dictionary value

### ISSUE THREAD

**Issue by andre2007** [home-assistant/hassio#973]
Supervisor 150
Hassos 2.11

I have plugin with build.json

```json
{
    "build_from": {
	"armhf" : "bestlibre/armhf-debian-base:stretch",
    "armv7" : "bestlibre/armhf-debian-base:stretch",
	"aarch64": "bestlibre/aarch64-debian-base:stretch",
	"amd64" : "debian:stretch",
	"i386" : "i386/debian:stretch"
    }
}
```

Following error is thrown 
Can't parse /data/addons/local/hello_world3/build.json: does not match regular expression for dictionary value @ data['build_from']['amd64']. Got 'debian:stretch'

**Comment by frenck** [comment]
@andre2007 Use `amd64/debian:stretch`.

`debian:stretch` is a manifest, not an exact pointer to an architecture.
