### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)

### ISSUE THREAD

**Issue by tiagofreire-pt** [home-assistant/hassio#975]
**Home Assistant release with the issue:**

0.90.2

**Operating environment (HassOS/Generic):**

HassOS

**Supervisor logs:**

> 18-06-22 11:12:17 INFO (MainThread) [__main__] Initialize Hass.io setup
18-06-22 11:12:18 INFO (MainThread) [__main__] Setup HassIO
18-06-22 11:12:18 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/armhf-hassio-supervisor with version 150
18-06-22 11:12:18 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1
18-06-22 11:12:18 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
18-06-22 11:12:18 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1
18-06-22 11:12:18 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
18-06-22 11:12:18 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /
18-06-22 11:12:18 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: de.pengutronix.rauc - /
18-06-22 11:12:18 INFO (MainThread) [hassio.host.info] Update local host information
18-06-22 11:12:18 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
18-06-22 11:12:18 INFO (MainThread) [hassio.host.services] Update service information
18-06-22 11:12:18 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
18-06-22 11:12:18 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
18-06-22 11:12:18 INFO (MainThread) [hassio.host.services] Reload local service hassos-apparmor.service
18-06-22 11:12:18 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
18-06-22 11:12:19 INFO (SyncWorker_1) [hassio.docker.interface] Attach to image homeassistant/raspberrypi3-homeassistant with version 0.90.2
18-06-22 11:12:19 INFO (MainThread) [hassio.hassos] Detect HassOS 2.11 on host system
18-06-22 11:12:19 INFO (SyncWorker_2) [hassio.docker.hassos_cli] Found HassOS CLI homeassistant/armhf-hassio-cli with version 9
18-06-22 11:12:19 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/git/ab75e4fb repository
18-06-22 11:12:19 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/git/a0d7b954 repository
18-06-22 11:12:19 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/git/7be23ff5 repository
18-06-22 11:12:19 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/core repository
18-06-22 11:12:19 INFO (MainThread) [hassio.addons.git] Load add-on /data/addons/git/8aef3602 repository
18-06-22 11:12:20 INFO (MainThread) [hassio.addons] Load add-ons: 66 all - 66 new - 0 remove
18-06-22 11:12:20 INFO (SyncWorker_1) [hassio.docker.interface] Attach to image homeassistant/armv7-addon-samba with version 8.1
18-06-22 11:12:20 INFO (SyncWorker_0) [hassio.docker.interface] Attach to image dwelch2101/dropbox-sync-armhf with version 1.3.0
18-06-22 11:12:20 INFO (SyncWorker_10) [hassio.docker.interface] Attach to image homeassistant/armv7-addon-configurator with version 2.1
18-06-22 11:12:20 INFO (SyncWorker_2) [hassio.docker.interface] Attach to image de3cd379/armhf-addon-rfreceiver with version 1.63
18-06-22 11:12:20 INFO (SyncWorker_14) [hassio.docker.interface] Attach to image homeassistant/armv7-addon-mosquitto with version 4.1
18-06-22 11:12:20 INFO (SyncWorker_7) [hassio.docker.interface] Attach to image homeassistant/armv7-addon-ssh with version 5.3
18-06-22 11:12:20 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
18-06-22 11:12:20 ERROR (MainThread) [asyncio] SSL handshake failed on verifying the certificate
protocol: <uvloop.loop.SSLProtocol object at 0x73ff4210>
transport: <TCPTransport closed=False reading=False 0x75125410>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 609, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)
18-06-22 11:12:20 ERROR (MainThread) [asyncio] SSL error errno:1 reason: CERTIFICATE_VERIFY_FAILED
protocol: <uvloop.loop.SSLProtocol object at 0x73ff4210>
transport: <TCPTransport closed=False reading=False 0x75125410>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)
18-06-22 11:12:20 WARNING (MainThread) [hassio.updater] Can't fetch versions from https://s3.amazonaws.com/hassio-version/stable.json: Cannot connect to host s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)')]
18-06-22 11:12:20 INFO (MainThread) [hassio.snapshots] Found 3 snapshot files
18-06-22 11:12:20 INFO (MainThread) [hassio.discovery] Load 1 messages
18-06-22 11:12:21 INFO (MainThread) [__main__] Run Hass.io
18-06-22 11:12:21 INFO (MainThread) [hassio.misc.dns] Start DNS port forwarding for host add-ons
18-06-22 11:12:21 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
18-06-22 11:12:21 INFO (MainThread) [hassio.addons] Startup initialize run 0 add-ons
18-06-22 11:12:21 INFO (MainThread) [hassio.addons] Startup system run 1 add-ons
19-03-27 19:41:57 INFO (SyncWorker_4) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-mosquitto with version 4.1
19-03-27 19:41:59 INFO (MainThread) [hassio.services.mqtt] Set core_mosquitto as service provider for mqtt
19-03-27 19:41:59 INFO (MainThread) [hassio.discovery] Duplicate discovery message from core_mosquitto
19-03-27 19:42:02 INFO (MainThread) [hassio.addons] Startup services run 3 add-ons
19-03-27 19:42:08 INFO (SyncWorker_3) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-samba with version 8.1
19-03-27 19:42:09 INFO (SyncWorker_7) [hassio.docker.addon] Start Docker add-on dwelch2101/dropbox-sync-armhf with version 1.3.0
19-03-27 19:42:10 INFO (SyncWorker_1) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-ssh with version 5.3
19-03-27 19:42:15 INFO (SyncWorker_8) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant Docker application
19-03-27 19:42:18 INFO (SyncWorker_8) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.90.2
19-03-27 19:43:02 INFO (MainThread) [hassio.api.security] /homeassistant/check access from core_ssh
19-03-27 19:43:02 INFO (SyncWorker_3) [hassio.docker] Run command 'python3 -m homeassistant -c /config --script check_config' on homeassistant/raspberrypi3-homeassistant
19-03-27 19:43:08 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-03-27 19:43:08 INFO (MainThread) [hassio.addons] Startup application run 0 add-ons
19-03-27 19:43:08 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
19-03-27 19:43:08 INFO (MainThread) [hassio.core] Hass.io is up and running
19-03-27 19:43:22 INFO (MainThread) [hassio.homeassistant] Home Assistant config is valid
19-03-27 19:48:08 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API 

> token

**Description of problem:**
See log above.

**Comment by tiagofreire-pt** [comment]
`18-06-22 11:12:15 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
18-06-22 11:12:16 ERROR (MainThread) [asyncio] SSL handshake failed on verifying the certificate
protocol: <uvloop.loop.SSLProtocol object at 0x73fdbd30>
transport: <TCPTransport closed=False reading=False 0x75172bd0>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 609, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)
18-06-22 11:12:16 ERROR (MainThread) [asyncio] SSL error errno:1 reason: CERTIFICATE_VERIFY_FAILED
protocol: <uvloop.loop.SSLProtocol object at 0x73fdbd30>
transport: <TCPTransport closed=False reading=False 0x75172bd0>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)
18-06-22 11:12:16 WARNING (MainThread) [hassio.updater] Can't fetch versions from https://s3.amazonaws.com/hassio-version/stable.json: Cannot connect to host s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)')]`

**Comment by GreyMarvel** [comment]
I was getting this error when power was pulled on my device and for some reason duckdns add-on didn't start on boot , if your using hassio check that the add-on has started if not restart it using the UI.

**Comment by tiagofreire-pt** [comment]
Hi, GreyMarvel.

No, I'm not using duckdns.
I did several system reboots and the issue remains.

Thanks.

**Comment by tiagofreire-pt** [comment]
Solved, as the system date was quite off.

**Comment by Ekta246** [comment]
@tiagofreire-pt I had the same issue. Thanks! for solving this issue!
