### ISSUE TITLE
BLE errors

### ISSUE THREAD

**Issue by tiagofreire-pt** [home-assistant/hassio#977]
**Home Assistant release with the issue:**

0.90.2

**Operating environment (HassOS/Generic):**

HassOS

**Supervisor logs:**

`019-03-28 11:18:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.suculenta_moisture is taking over 10 seconds 2019-03-28 11:18:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.suculenta_temperature is taking over 10 seconds 2019-03-28 11:18:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.suculenta_conductivity is taking over 10 seconds 2019-03-28 11:18:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.suculenta_light_intensity is taking over 10 seconds 2019-03-28 11:18:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.coentros_moisture is taking over 10 seconds 2019-03-28 11:18:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.coentros_light_intensity is taking over 10 seconds 2019-03-28 11:18:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.coentros_temperature is taking over 10 seconds 2019-03-28 11:18:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.coentros_conductivity is taking over 10 seconds 2019-03-28 11:18:08 INFO (SyncWorker_1) [pygatt.backends.gatttool.gatttool] Starting BLE scan 2019-03-28 11:18:08 ERROR (SyncWorker_1) [pygatt.backends.gatttool.gatttool] Unexpected error when scanning: Set scan parameters failed: I/O error 2019-03-28 11:18:08 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pexpect/spawnbase.py", line 166, in read_nonblocking s = os.read(self.child_fd, size) OSError: [Errno 5] I/O error During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pexpect/expect.py", line 111, in expect_loop incoming = spawn.read_nonblocking(spawn.maxread, timeout) File "/usr/local/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking return super(spawn, self).read_nonblocking(size) File "/usr/local/lib/python3.7/site-packages/pexpect/spawnbase.py", line 171, in read_nonblocking raise EOF('End Of File (EOF). Exception style platform.') pexpect.exceptions.EOF: End Of File (EOF). Exception style platform. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 315, in scan scan.expect('foooooo', timeout=timeout) File "/usr/local/lib/python3.7/site-packages/pexpect/spawnbase.py", line 341, in expect timeout, searchwindowsize, async_) File "/usr/local/lib/python3.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list return exp.expect_loop(timeout) File "/usr/local/lib/python3.7/site-packages/pexpect/expect.py", line 117, in expect_loop return self.eof(e) File "/usr/local/lib/python3.7/site-packages/pexpect/expect.py", line 63, in eof raise EOF(msg) pexpect.exceptions.EOF: End Of File (EOF). Exception style platform. <pexpect.pty_spawn.spawn object at 0x6c5b7a50> command: /usr/bin/hcitool args: ['/usr/bin/hcitool', '-i', 'hci0', 'lescan'] buffer (last 100 chars): b'' before (last 100 chars): b'Set scan parameters failed: I/O error\r\n' after: <class 'pexpect.exceptions.EOF'> match: None match_index: None exitstatus: 1 flag_eof: True pid: 100 child_fd: 48 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile(b'foooooo') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.7/site-packages/homeassistant/components/device_tracker/bluetooth_le_tracker.py", line 96, in update_ble devs = discover_ble_devices() File "/usr/local/lib/python3.7/site-packages/homeassistant/components/device_tracker/bluetooth_le_tracker.py", line 58, in discover_ble_devices devs = adapter.scan() File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 326, in scan raise BLEError(message) pygatt.exceptions.BLEError: Unexpected error when scanning: Set scan parameters failed: I/O error `

**Description of problem:**
See errors on above log.

**Comment by balance82** [comment]
Have you solved it?
