### ISSUE TITLE
Webhook post url from within a plugin

### ISSUE THREAD

**Issue by andre2007** [home-assistant/hassio#985]
I am not able to find the correct URL to post a webhook from within a plugin container. I tried all possible combinations (by reading the plugin documentation) and received either 400 / 401 or 404.

I also posted some days ago the same question in the community but no one was able to answer the question. 
https://community.home-assistant.io/t/webhook-endpoint-address-within-a-plugin-container/108032

Is it possible at all and what is the URL? My assumption is the webhook URL should be reachable without authentication.

**Comment by pvizeli** [comment]
It's on my task list to write a document.
`http://hassio/homeassistant/api/webhook/xy` look in developer page for token handling

**Comment by andre2007** [comment]
Why is a token needed? If I call the webhook from outside, no token is needed.

**Comment by andre2007** [comment]
Are you sure about the token? With a valid token and the url you mentioned I receive 401.

```d
string token = environment.get("HASSIO_TOKEN");
auto client = new HttpClient();
auto request = client.request(arsd.http2.Uri(targetUrl), HttpVerb.POST);
request.requestParameters.headers ~= "X-HASSIO-KEY: " ~ token;
auto response = request.perform();
```

**Comment by pvizeli** [comment]
because it works over an internal API gateway. But you can also call it over your external URL without an internal API Gateway.

**Comment by andre2007** [comment]
While trying to call the external URL (post) from within the plugin container I get an connection refused exception. 

POST http://hassio:8123/api/webhook/xy

Are you sure calling the internal/external webhook API is working from within plugin container?

**Comment by frenck** [comment]
@andre2007 If you want to post directly to HA you have to post to:

`http://homeassistant:8123/api/webhook/xy`

If you want to use the bridge provided by Hass.io you'd use:

`http://hassio/homeassistant/api/webhook/xy`, which requires authentication using the HASSIO_TOKEN that is available from the add-on environment.

**Comment by andre2007** [comment]
Thanks.
