### ISSUE TITLE
Can't install Appdaemon community addon by Frenck

### ISSUE THREAD

**Issue by Notrial** [home-assistant/hassio#987]
**Home Assistant release with the issue:**
0.90.1

**Operating environment (HassOS/Generic):**
HassOS 2.11

**Supervisor logs:**
`19-03-29 08:44:18 INFO (SyncWorker_4) [hassio.docker.interface] Pull image hassioaddons/appdaemon3-armhf tag 1.7.0. 19-03-29 08:45:06 ERROR (SyncWorker_4) [hassio.docker.interface] Can't install hassioaddons/appdaemon3-armhf:1.7.0 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").`

**Description of problem:**
Can't install plugin.
First time HA crashed (required pulling the plug).
Second time it gave an error in HassOS log (please see above).

**Comment by pvizeli** [comment]
Yeah, that is a corrupt filesystem problem :(

**Comment by frenck** [comment]
@Notrial Your Docker file system has corruption. There is nothing from our end that we can do.

**Comment by Notrial** [comment]
@frenck I assume only way to resolve this is to reinstall from scratch, correct?

Thanks!
