### ISSUE TITLE
ttyAMA0 is not passed in with auto_uart for addons.

### ISSUE THREAD

**Issue by blurkis** [home-assistant/hassio#993]
**Home Assistant release with the issue:**
I have hassio up2date

**Operating environment (HassOS/Generic):**

I use standard up2date hassio on a raspberry pi3

**Supervisor logs:**

**Description of problem:**
I wanted to use esphome addon to flash a sonoff pow2 using the gpio pins on a pi3
which should work according to esphome. 
According to https://github.com/esphome/issues/issues/93 the problem is that
"This means this is an external issue in Hass.io, apparently ttyAMA0 is not passed in with auto_uart for addons."

The esphome addon supplys a dropdown of all connected devices which could be flashed. As for exampe, a nodemcu with usb-cable is listed and can be used. But ttyAMA, which if im not understanding it wrong, would be the device to flash my sonoff pow2 connected to the gpio pin on my pi3.

**Comment by pvizeli** [comment]
We use the kernel device protocol to detect what it's needed to mount into the device.
What do you see on UI hardware button?

I think your ttyAMA0 is used for bluetooth and you don't disable it.
